- synfig-core/src/modules/mod_svg/svg_parser.cpp
- synfig-core/src/modules/mod_svg/svg_parser.h
Fixed bug with locales in SVG module. The problem appeared when numeric format dosn't match with "C" format.
> Fixed locale bug in SVG module.

- synfig-studio/src/gui/cellrenderer/cellrenderer_value.cpp
value_entry is dynamicaly created into CellRenderer_ValueBase::start_editing_vfunc
near line 678 ( https://github.com/synfig/synfig/blob/master/synfig-studio/src/gui/cellrenderer/cellrenderer_value.cpp#L680 )
value_entry=manage(new ValueBase_Entry());		assert(get_canvas());
//delete value_entry;
value_entry=manage(new ValueBase_Entry());  // <---- here
value_entry->set_path(path);
value_entry->set_canvas(get_canvas());
> Fix memory leak.

- synfig-studio/src/gui/cellrenderer/cellrenderer_timetrack.cpp
This fix makes it so that dragging a waypoint on the canvas parameter of a time dilated group moves it to where you would expect it to be moved. Prior to the fix, the waypoint would be moved by the same offset within the canvas regardless of the group's speed, meaning that it would overshoot if speed > 1, undershoot if speed < 1, and go in entirely the wrong direction if speed < 0.
Dragged waypoints will not move at all if speed == 0. This behavior will obviously have to change, but I guess _what_ it should change to hasn't been decided, so this will have to do for now.
> Fix waypoints for time dilated canvases getting dragged to the wrong points

- synfig-studio/src/gui/cellrenderer/cellrenderer_timetrack.cpp
- synfig-studio/src/synfigapp/actions/timepointscopy.cpp
- synfig-studio/src/synfigapp/actions/timepointsmove.cpp
- synfig-studio/src/synfigapp/timegather.cpp
- synfig-studio/src/synfigapp/timegather.h
Hopefully this will be the last of the trouble brought on by time dilation. When a group contained another group whose contents had waypoints, and the subgroup was time-dilated, dragging one of its waypoints on the canvas parameter of the supergroup wouldn't work correctly. Usually, it would simply do nothing, but occasionally, the wrong waypoint would be moved the wrong distance.
This fix makes dragging waypoints under those circumstances work as expected. You can even drag multiple waypoints from groups with different speeds at the same time.
> Fix dragged waypoints from time-dilated subgroups not working properly

- synfig-core/src/modules/mod_png/trgt_png_spritesheet.cpp
- synfig-core/src/synfig/targetparam.h
- synfig-studio/src/gui/dialogs/dialog_spritesheetparam.cpp
While playing around with sprite sheet animation I stumbled across a little typo in the export dialog. It should read 'horizontal' instead of 'horisontal'.
> Fixed typo in export dialog

- synfig-studio/src/gui/workarearenderer/renderer_ducks.cpp
[FIX] Group transfo widget and other gradient widget has dotted line but should'nt have
> Fix 308 : Split tangent indicator - fix group & gradient

- .gitignore
`synfig-core/m4/ltargz.m4` is added as part of the autobuild process on Linux Debian/Stetch.
Add it to .gitignore
> Git should ignore synfig-core/m4/ltargz.m4

- autobuild/synfigstudio-linux-build.sh
As described on http://www.synfig.org/forums/viewtopic.php?f=13&t=10478
Linux Autobuild on Debian Strech/Sid has some issue with the libtiff-dev & libpng-dev dependency:
```
Package libtiff-dev is a virtual package provided by:
libtiff5-dev 4.0.7-5
libtiff4-dev 3.9.6-11+deb7u3
You should explicitly select one to install.
```
and
```
The following packages have unmet dependencies:
libpng-dev : Conflicts: libpng12-0-dev
Conflicts: libpng12-dev but 1.2.50-2+deb8u3 is to be installed
Conflicts: libpng3-dev
Recommends: libpng-tools but it is not going to be installed
libpng12-dev : Conflicts: libpng-dev
```
In addition, the `libfftw3` was missing.
> Fix dependencies for Debian Stretch/Sid

- synfig-core/src/modules/mod_magickpp/trgt_magickpp.cpp
Since MagickCore version 7 deprecated methods have been removed. GetExceptionInfo() can no longer be used to initialize an exception info.
With the help of @caryoscelus I'm trying to find a way to implement MagickCore's hidden InitializeExceptionInfo() method in a manner which is compatible with version 7 and 6 of ImageMagick.
> Workaround to implement MagickCore's hidden InitializeExceptionInfo() method

- README.md
Added OS specific instructions for installation.
This was sparked by my confusion after downloading Synfig on Ubuntu for the first time.
> Add Installation Info

- synfig-core/src/synfig/distance.cpp
> Use fixed-point, not scientific notation for displaying Distance values

- synfig-core/src/modules/mod_geometry/outline.cpp
**Change description**
In commit 90788ec4df1450785463c403556dfbda7d695aa2 the SAMPLES define was decreased from 50 to 10. This made the outline rough (see attachments for example). This patch reverts that change to make the outlines smooth again (the advanced outlines wasn't affected by this bug).
**Attachments**
Rendered outline in master (4aa255f9ad852e3de5a64046f243a8b9dc34d143):
Rendered outline in master with this commit:
Original .sif file:
[OutlineBug.zip](https://github.com/synfig/synfig/files/2832796/OutlineBug.zip)
> Improve outline smoothness

- synfig-core/src/synfig/rendering/renderer.cpp
- synfig-core/src/synfig/rendering/software/CMakeLists.txt
- synfig-core/src/synfig/rendering/software/Makefile_insert
- synfig-core/src/synfig/rendering/software/rendererpreviewsw.cpp
- synfig-core/src/synfig/rendering/software/rendererpreviewsw.h
- synfig-studio/src/gui/canvasview.cpp
- synfig-studio/src/gui/canvasview.h
Fixes #729 
I added the new rendering mode - "Cobra Preview" and made it the default renderer.
I verified it's working.
>So far we need only one Optimizer, which modifies how images are displayed: it disables supersampling and forces NearestNeighbour interpolation scaling method.
_The above line Implied to NEAREST INTERPOLATION so I used the OptimizerDraftTransformation_
For GUI I used Comboboxtext and replaced the Togglebutton
As I cannot directly place Combobox to Toolbar hence I placed the Combobox in a Gtk::Tool Item Container.
**The GUI looks as below:**
@morevnaproject Please review the changes made :smiley: 
PS: Want to drive your attention towards the depreciation error which says **throws is deprecated in C++ 11** while building synfig, I think in ETL
> Added Preview workarea rendering

- synfig-studio/src/gui/canvasview.cpp
Closes: #750
The "Pause" in Navigation menu now works. Consequently, the short key "Esc" which starts the "stop" action also works.
All the other options in the Navigation seem to be working fine.
> Pause in Menu->Navigation

- synfig-studio/src/gui/app.cpp
- synfig-studio/src/gui/dialogs/dialog_setup.cpp
- synfig-studio/src/gui/dialogs/dialog_setup.h
Closes: #760
The option for enabling/disabling experimental features has been added.
The default value for enabling experimental features is "false", as seen here.
https://github.com/synfig/synfig/blob/9b3fe68804dd3d5bfb5d6ac43a74fa72138b6c18/synfig-studio/src/gui/app.cpp#L306
This feature is currently being used to disable the "Brush Tool". It can be extended to isolate other experimental features as well.
Thanks for locating the code for "Brush Tool" @morevnaproject.
^_^
> Experimental features option. Disable brush tool.

- 1-setup-linux-native.sh
pacman is the package manager for many arch based distros
Headers are generally provided with binaries so *-devel isn't required
> Added support for 'pacman' package manager in linux setup script

- synfig-studio/src/gui/app.cpp
- synfig-studio/src/gui/app.h
- synfig-studio/src/gui/dialogs/dialog_setup.cpp
- synfig-studio/src/gui/dialogs/dialog_setup.h
- synfig-studio/src/gui/instance.cpp
As per #516 I added the option in preferences under **Edit -> Preferences-> Editing ** 
The button open a filechooserdialog (by default in usr/bin ) from where app can be selected
After which we can use the "Edit image in external tool " option for any image layer
PS: Works fine in linux Mint OS, ~~Windows implementation is not done yet~~
@morevnaproject please suggest possible edits if any :)
**EDIT:** Added corresponding option for windows and OS X but cannot verify it's working :/
> Added Edit Image in external tool

- synfig-studio/src/gui/canvasview.cpp
- synfig-studio/src/gui/dialogs/dialog_setup.cpp
- synfig-studio/src/gui/dialogs/dialog_setup.h
Fixes: #758 
> As per https://github.com/synfig/synfig/issues/758 navigator renderer option is now removed and it will same as that of Workarea renderer
@morevnaproject please review this PR when you have time (^_^)
> Removed option to select navigator renderer

- synfig-studio/src/gui/instance.cpp
As this can be seen in fig now on a group containing a single image layer have an external edit tool option.
And when there are more than one image layer or any kind of layer the option is not shown.
@morevnaproject please review when you have time [^_^]
> Fixed part 2 of #516

- synfig-studio/m4/gnome.m4
Remove broken, oudated, embedded copy of PKG_CHECK_MODULES from
m4/gnome.m4. Removal causes synfigstudio to pick up the current version
from the pkg-config package. The outdated version makes cross building
fail.
Bug-Debian: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=900433
From: Helmut Grohne <helmut@subdivi.de>
> Remove legacy PKG_CHECK_MODULES from m4/gnome.m4

- synfig-studio/src/gui/instance.cpp
- synfig-studio/src/gui/instance.h
Fixes #810.  "Edit image in external tool" now works correctly when called from workarea. Replaced vector with set for fast find operation. created a function for confirming if the uri belongs to image layer or not.
@morevnaproject please review :)
>  Fix "Edit image in external tool" command for workarea

- synfig-core/src/modules/mod_geometry/outline.cpp
Note that we index two nodes back from the end, which is a buffer
underflow for degenerate primitives (lines, mostly), causing a crash on
select sif's (that were fine on older Synfig versions... Now we don't
crash, but hang rendering...)
Signed-off-by: Alyssa Rosenzweig <alyssa@rosenzweig.io>
> core/geometry: Fix crash for degenerate looping primitives

- ETL/bootstrap.sh
- ETL/configure.ac
- synfig-core/bootstrap.sh
- synfig-core/configure.ac
- synfig-core/m4/subs.m4
- synfig-studio/bootstrap.sh
- synfig-studio/configure.ac
- synfig-studio/m4/subs.m4
Minor update to less warnings. Autoconf 2.60 is already 11 years old, so I think there is no problem here.
http://git.savannah.gnu.org/gitweb/?p=autoconf.git
> Update autotools files

- 2-build-cmake.sh
- autobuild/build-cmake-common.sh
**Change description:**
Currently, the 2-build-cmake.sh script doesn't support incremental builds (that means to rebuild only the changed files).
This commit adds the option "-i" which disables the steps of deleting the old build path, creating the build folders and rendering the .sif icons with synfig. This option can be useful for developers, whose want to test Synfig Studio, after some code changes. With that option it's not necessary to rebuild the entire Synfig Studio. Only the changed files will be rebuild. That saves a lot off time.
**Limitations:**
The new "-i" option can only be used, if Synfig Studio is already build as a non incremental build (with 2-build-cmake.sh) at the selected build mode (build mode = debug or release).
> Add incremental build for cmake autobuild

- synfig-core/po/POTFILES.in
- synfig-studio/po/POTFILES.in
When running `make check`, it fails due to these missing files
> update POTFILES.in - new files added

- synfig-core/src/synfig/renddesc.cpp
- synfig-core/src/synfig/renddesc.h
One could simply use assignment operator;
the "apply" method implementation is just a wrapper
for the former.
> remove redundant and unused function RendDesc::apply()

- synfig-studio/src/gui/app.cpp
- synfig-studio/src/gui/dialogs/about.cpp
- synfig-studio/src/gui/dialogs/dialog_setup.cpp
- synfig-studio/src/gui/dialogs/dialog_setup.h
- synfig-studio/src/gui/docks/dock_toolbox.cpp
- synfig-studio/src/gui/docks/dock_toolbox.h
- synfig-studio/src/gui/docks/dockable.h
- synfig-studio/src/gui/trees/layertree.cpp
- synfig-studio/src/gui/trees/layertree.h
- synfig-studio/src/gui/widgets/widget_link.cpp
- synfig-studio/src/gui/widgets/widget_vector.cpp
In my journey to convert coded-dialogs to GtkBuilder ones, I am testing for memory leaks with Valgrind.
I found these memory leaks and fixed them.
> Fix mem leaks in Studio

- synfig-studio/src/gui/mainwindow.cpp
- synfig-studio/src/gui/mainwindow.h
over Accel keys.
Inspired by :
https://github.com/GNOME/gimp/blob/732852a471f466fb0e19ab30a11710f060700c06/app/widgets/gimpwindow.c#L159
Thanks to Jehan and mitch from #gimp IRC channel
> fix #257 let Gtk::Entry & TextView key handlers have priority

- synfig-studio/src/gui/widgets/widget_compselect.cpp
Fix Coverity issue cov#308605
Maybe we should just use `std::find()` instead of `for(i=0,iter=studio::App::instance_list.begin();iter!=studio::App::instance_list.end() && ((*iter)!=x);iter++,i++)`
> Cov 308605

- synfig-core/src/tool/main.cpp
- synfig-core/src/tool/optionsprocessor.cpp
- synfig-core/src/tool/optionsprocessor.h
Create a new method SynfigCommandLineParser::process_trivial_info_options
specifically for process trivial operations from command line that don't need
synfig::Main
This new method is called before synfig::Main instantiation
Fix #281
> Don't load modules for trivial operations in cli

- synfig-core/src/modules/mod_ffmpeg/CMakeLists.txt
With cmake, the autotools definitions are not implicitly defined. This led to
the windows codepath being used everywhere, causing breakage on unix.
The necessary definitions have been manually added to the cmake build.
> fix mod_ffmpeg with cmake build

- synfig-core/src/modules/mod_svg/svg_parser.cpp
- synfig-core/src/synfig/valuenodes/valuenode_bline.cpp
- synfig-osx/launcher/darwin.c
- synfig-studio/config/package
- synfig-studio/plugins/lottie-exporter/common/Canvas.py
- synfig-studio/plugins/lottie-exporter/common/Param.py
- synfig-studio/plugins/lottie-exporter/common/misc.py
- synfig-studio/plugins/lottie-exporter/layers/group.py
- synfig-studio/plugins/lottie-exporter/layers/rotate_layer.py
- synfig-studio/plugins/lottie-exporter/properties/offsetKeyframe.py
- synfig-studio/plugins/lottie-exporter/properties/shapePropKeyframe/outline.py
- synfig-studio/plugins/lottie-exporter/settings.py
- synfig-studio/src/gui/app.cpp
- synfig-studio/src/gui/states/state_draw.cpp
- synfig-studio/src/gui/states/state_lasso.cpp
- synfig-studio/src/gui/states/state_width.cpp
- synfig-studio/src/synfigapp/vectorizer/centerlineadjustments.cpp
- synfig-studio/src/synfigapp/vectorizer/centerlinecolors.cpp
- synfig-studio/src/synfigapp/vectorizer/centerlinepolygonizer.cpp
- synfig-studio/src/synfigapp/vectorizer/centerlineskeletonizer.cpp
- synfig-studio/src/synfigapp/vectorizer/centerlinetostrokes.cpp
- synfig-studio/src/synfigapp/vectorizer/centerlinevectorizer.cpp
- synfig-studio/src/synfigapp/vectorizer/polygonizerclasses.h
- synfig-studio/src/synfigapp/vectorizer/vectorizerparameters.h
Found via `codespell -q 3 -L ,ang,ba,childs,eiter,forse,objext,pevent,shouldbe,thru,uint,unselect,vertexes --skip="./synfig-studio/po,./synfig-core/po,/synfig-core/m4,./synfig-osx/,./gtkmm-osx,./bugs,.*.eps,*.sif"`
> Fix source comment typos and some comment formatting

- 2-build-cmake.sh
- autobuild/build-cmake-common.sh
- synfig-studio/src/CMakeLists.txt
In the latest commit (a570f15844060c60ed3d12c31f0ec986112fa97d) the build of Synfig Studio with 2-build-cmake.sh fails with the following error (testet on Manjaro Linux): 
In the step of building the libsynfigapp the linking process (linking to libsynfig) fails because the linker can't find the library.
This commit fixes the error. It adds the output path to the search path for the linker.
> Fixed CMake build errors and improved the automatical build tool

- autobuild/synfigrenderer-regression-test.sh
- Now using tests repository hosted on GitLab - https://gitlab.com/synfig/synfig-tests/
- The script now providing actual information about failed tests against **current** code
> Fix regressions tests

- .travis.yml
- travis.sh
Re-format regression testing as separate Travis job (which is allowed to fail for now).
> Move regressions testing to separate Travis job

- synfig-studio/src/gui/cellrenderer/cellrenderer_timetrack.cpp
- synfig-studio/src/gui/docks/dock_timetrack.cpp
This PR adds double-clik to edit waypoints in the timetrack dock. See gif below for example
> Allow to edit waypoints using double-click. Fixes #262.

- synfig-studio/src/gui/preview.cpp
Build and tested the new default value as Fit (instead of 100%) on my Debian system.
Now the preview window opens in Fit zoom by default.
> Fix issue #998 Changed default preview zoom to Fit

- synfig-studio/src/gui/canvasview.cpp
Current Time Widget should display its text in red when there is a keyframe at current time. Otherwise its text should be black.
This behaviour got broken in 0589a7d, fixed now.
> Fix Current Time Widget behaviour

- synfig-studio/src/gui/states/state_bline.cpp
As suggested in https://github.com/synfig/synfig/pull/1007#issuecomment-554748401
Sometimes it has issues if tangent handle is on the same place as first vertex: you can't finish if first vertex is not reachable.
> finish (and loop) spline if first vertex is clicked

- synfig-studio/src/gui/instance.cpp
- synfig-studio/src/gui/instance.h
This makes logic of `gather_uri()` function cleaner.
Also, `layer_inside_switch()` function is now permits only LayerSwitch as argument.
Cleanup debugging output.
> Improve logic of gather_uri() function. Cleanup.

- synfig-studio/src/gui/workarearenderer/renderer_ducks.cpp
Now it visually separated from origin handle.
Before:
After:
> Change color for Origin handle of Group Layer

- 2-build-production.sh
If WORKDIR contains a path with a blank space, the path is wrongly interpreted. This patch adresses that issue.
> Fix case where directory path has a space

- synfig-studio/src/gui/widgets/widget_filename.cpp
- synfig-studio/src/gui/widgets/widget_filename.h
The label contents ". . ." is nearly visible, so I thought it would be good to change it.
> replace button label with open icon for widget_filename

- ETL/ETL/_stringf.h
- synfig-core/src/synfig/loadcanvas.cpp
This fixes crash on re-opening same file.
> Fix #1064: Crash when calling any plugin on Windows

- synfig-studio/src/gui/instance.cpp
When setting layer "description" I found out that the "OK" button (labeled as "Set" in code) in my language is translated as if it mean (Layer) Set.
> Avoid ambiguity in translation of Set (verb x noun)

- synfig-studio/src/synfigapp/vectorizer/centerlinetostrokes.cpp
@morevnaproject I used  `width = (width/2.5)*max(w_factor,h_factor)` I also tried sqrt(w_factor*h_factor) and results were similar considering almost same transformation along width and height. Let me know if this logic can be futher improved. 
@ice0 @blackwarthog suggestions?
Closes: #1082
> make width depend on TL/BR

- synfig-studio/src/gui/app.cpp
- synfig-studio/src/gui/ipc.cpp
Closes #680.
How to check:
1. Ensure that Synfig is not launched (otherwise you will hit #1124).
2. Drag-n-drop any Synfig file with non-latin characters on `synfigstudio.exe` binary.
3. Application should run and open file properly.
> Fix opening files with non-lating characters from commandline on Windows

- synfig-core/src/synfig/value.cpp
- synfig-core/src/synfig/value.h
Reason: c++ Rule of 5 (by using copy-swap idiom)
> define copy constructor if assignment operator is defined

- synfig-studio/src/gui/app.cpp
It's not an menu item and Dialog_Setup calls
App::restore_default_settings() method directly
> remove unused action restore-defaults-settings

- synfig-studio/src/gui/dialogs/dialog_setup.cpp
It was inserted by 366b6582272b8657c1d37909cc4c845de746cc82 . I don't know if it was supposed to be in another place...
> remove strange #include in Dialog_Setup

- synfig-studio/src/gui/autorecover.cpp
The issue #1140 introduced in 28db040 -now we need to manually call `discard_changes()` when `FilesystemTemporary` destroyed.
> Fix #1140: Clicking "Ignore" button doesn't removes backup

- synfig-studio/src/gui/dialogs/about.cpp
This fixes the building error encountered using the CMake build system on NetBeans.
EDIT: Need more insight on how synfig build works. I'm curious why not just configure CMakeLists.txt at the root directory to do all the build stuff instead of the custom build-cmake.sh script file.
> Fixes #1118 Added PACKAGE_NAME macro

- synfig-core/src/synfig/filesystemtemporary.cpp
- synfig-core/src/synfig/filesystemtemporary.h
- synfig-studio/src/gui/autorecover.cpp
- synfig-studio/src/gui/instance.cpp
- synfig-studio/src/synfigapp/instance.cpp
This is a better approach for 93f25328c15 and 28db040026 (partially reverts their changes).
It does not requires to explicitly call `FileSystemTemporary::discard_changes()`.
Instead, I just added a flag to FileSystemTemporary class (keep_files_when_destroyed),
which defines how to deal with temporary files after class instance is destroyed.
> Do not require to explicitly call FileSystemTemporary::discard_changes()

- synfig-studio/src/gui/docks/dock_soundwave.cpp
When sound dock shrinks small enough, a dock scrollbar appeared.
> don't show extra vertical scrollbar for Dock Sound

- synfig-core/configure.ac
fix #744
According to:
https://github.com/synfig/synfig/issues/744#issuecomment-469157746
"Looks like build files if FFmpeg version is older than 3.0."
And FFmpeg site says:
https://www.ffmpeg.org/olddownload.html
"FFmpeg 3.0.12 "Einstein"
It includes the following library versions:
libavutil      55. 17.103
libavcodec     57. 24.102
libavformat    57. 25.100
libavdevice    57.  0.101
libavfilter     6. 31.100
libavresample   3.  0.  0
libswscale      4.  0.100
libswresample   2.  0.101
libpostproc    54.  0.100
> upgrade minimum version of libav/FFmpeg

- synfig-studio/plugins/lottie-exporter/common/Param.py
- synfig-studio/plugins/lottie-exporter/effects/controller.py
Fixes: #1101 
@AnishGG , I looked at #1018 which had similar issue as this one and was able to resolve this.
Please have a look at this.
> [Lottie exporter] Convert methods working with radius of simple circle layer

- synfig-studio/src/gui/instance.cpp
Fixes: #1204 
@AnishGG , @ice0 , I fixed it by adding canvas->set_name() to the Save dialog box.
Please have a look at this.
> Fixed wrong filename in plugins dialog box

- synfig-studio/src/gui/canvasview.cpp
* "Set" button -> "Ok", because it would be translated as "group" meaning otherwise
* Don't concatenate strings, because several languages don't follow genitive case ordering like Noun (owner) + Noun like English and German do.
Eg., in Portuguese, we use Noun + " de " + Noun(owner). So we need full text for i18n.
> fix i18n for Set Keyframe Description dialog

- .gitignore
- CMakeLists.txt
- synfig-core/src/modules/CMakeLists.txt
Fixes on #1131. 
Changes:
- Updated `CMakeLists.txt`. Inside the build folder, it makes `bin` and `lib` (~~ETL~~, ~~include~~). Execution still require [these commands](https://github.com/synfig/synfig/issues/1131#issuecomment-586873899).
- Updated `.gitignore`.
> [CMake] Updated CMake script to change layout of build files.

- synfig-studio/plugins/lottie-exporter/common/Param.py
- synfig-studio/plugins/lottie-exporter/effects/color.py
- synfig-studio/plugins/lottie-exporter/effects/controller.py
- synfig-studio/plugins/lottie-exporter/effects/opacity.py
- synfig-studio/plugins/lottie-exporter/effects/point.py
- synfig-studio/plugins/lottie-exporter/effects/slider.py
- synfig-studio/plugins/lottie-exporter/properties/offsetKeyframe.py
- synfig-studio/plugins/lottie-exporter/properties/shapePropKeyframe/helper.py
- synfig-studio/plugins/lottie-exporter/shapes/circle.py
- synfig-studio/plugins/lottie-exporter/synfig/animation.py
Cleaned up the code for Lottie Exporter plugin and removed LGTM warning alerts. In #1199 I had focussed only on adding changes tagged as recommendations.
Link for the alerts : [LGTM warning alerts for the Lottie Exporter plugin](https://lgtm.com/projects/g/synfig/synfig/?mode=list&lang=python&severity=warning)
@AnishGG , @ice0 Please have a look at this
> [Lottie Exporter] Code cleanup for Lottie exporter plugin

- synfig-studio/plugins/lottie-exporter/properties/offsetKeyframe.py
There was a mistake in the file offsetKeyframe.py .
https://github.com/synfig/synfig/blob/b380d8a35d882f5d5d839b396a7d3912b8488c9f/synfig-studio/plugins/lottie-exporter/properties/offsetKeyframe.py#L65-L67
The above lines should be changed according to : https://github.com/synfig/synfig/blob/b380d8a35d882f5d5d839b396a7d3912b8488c9f/synfig-core/src/synfig/valuenodes/valuenode_animatedinterface.cpp#L148-L151
> [Lottie Exporter] Changes made to offsetKeyframe file

- synfig-studio/images/CMakeLists.txt
Fixes: #1132 
I've made these changes on top of changes proposed in #1232 (I'll rebase these changes onto master once it's merged).
This will reduce the cmake building commands to:
```
mkdir build-cmake && cd build-cmake
cmake ../
make -j4
make build_images -j4
./output/bin/synfigstudio 
```
Existing issues:
- Rebuilding of images everytime (#1229).
- ~~Running binaries after running `make install` doesn't seem to run, it throws~~
Once these are fixed, we can even update [documentations](https://github.com/synfig/synfig/blob/master/README-CMake.md).
> Fixes for CMake build_images target.

- synfig-studio/po/POTFILES.in
- synfig-studio/src/gui/app.cpp
- synfig-studio/src/gui/docks/CMakeLists.txt
- synfig-studio/src/gui/docks/Makefile_insert
- synfig-studio/src/gui/docks/dock_timetrack.cpp
- synfig-studio/src/gui/docks/dock_timetrack.h
- synfig-studio/src/gui/docks/dock_timetrack2.cpp
- synfig-studio/src/gui/docks/dock_timetrack2.h
- synfig-studio/src/gui/selectdraghelper.h
- synfig-studio/src/gui/widgets/CMakeLists.txt
- synfig-studio/src/gui/widgets/Makefile_insert
- synfig-studio/src/gui/widgets/widget_curves.cpp
- synfig-studio/src/gui/widgets/widget_timegraphbase.cpp
- synfig-studio/src/gui/widgets/widget_timegraphbase.h
- synfig-studio/src/gui/widgets/widget_timetrack.cpp
- synfig-studio/src/gui/widgets/widget_timetrack.h
I don't know all features of current TimeTrack, please let me know if something is missing:
key `n` and `b` to go to next or previous waypoint. By holding `shift`, user skips 5 waypoints.
(by design, it only works when only one waypoint is selected.)
> New timetrack

- synfig-studio/src/gui/widgets/widget_timetrack.cpp
> fix uninitialized row info geometry

- synfig-studio/src/gui/states/state_bline.cpp
- synfig-studio/src/gui/widgets/widget_gradient.cpp
For Widget_Gradient and Spline tool (eg., vertex context menu)
maybe fix #1274
> fix popup menu popping down right after button release

- synfig-core/src/synfig/valuenodes/valuenode_dynamiclist.cpp
- synfig-studio/src/gui/trees/canvastreestore.cpp
- synfig-studio/src/gui/trees/layerparamtreestore.cpp
If you select a vertex item of Spline parameter list and then right-click on it and choose `Remove item (Smart)`, app crashes.
Not anymore. Simple, but not the best, solution.
> Fix crash when removing a list item of a parameter

- 1-setup-osx-brew.sh
- 1-setup-windows-msys2.sh
- autobuild/build.sh
- synfig-core/configure.ac
- synfig-studio/images/Makefile.am
- synfig-studio/images/splash_screen_development.sh
- synfig-studio/src/gui/resourcehelper.cpp
This enables building image with Autotools on Windows.
I've been forced to disable Magick++, because it failed to build for me.
At the same time, ImageMagick is mandatory requirement to build images with Autotools (it is used to convert some icon files).
> [MSYS2] Enable building of images (Autotools)

- synfig-core/src/synfig/loadcanvas.cpp
This way files from version <= 1.3.11 can be correctly opened in
new version as well for those created in current Studio version.
More info:
https://github.com/synfig/synfig/issues/1284
https://github.com/synfig/synfig/issues/314#issuecomment-603703084
> fix outline vertex order for older files - again :)

- autobuild/lottie_test.sh
- synfig-studio/plugins/lottie-exporter/common/Param.py
- synfig-studio/plugins/lottie-exporter/lottie-exporter.py
- synfig-studio/plugins/lottie-exporter/plugin.xml.in
- synfig-studio/src/gui/app.cpp
- synfig-studio/src/gui/app.h
- synfig-studio/src/gui/canvasview.cpp
- synfig-studio/src/gui/iconcontroller.cpp
- synfig-studio/src/gui/instance.cpp
- synfig-studio/src/gui/instance.h
- synfig-studio/src/gui/pluginmanager.cpp
- synfig-studio/src/gui/pluginmanager.h
Adds more metadata to the plugins to support a proper export system.
I've also updated the lottie exporter to use this system.
This is said plugin description as an example:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<plugin type="exporter">
<_name>Export to Lottie format</_name>
<exec>lottie-exporter.py</exec>
<extension>.json</extension>
<description>Lottie Animation (*.json)</description>
</plugin> 
```
if the `type` attribute is present and its value is "exporter", the plugin will be added to a list of exporters. The `<extension>` and `<description>` elements are used by the new "Export" dialog to set up the file filters.
Such plugins no longer show in the Plugins menu, they are only accessible through File > Export...
> Export plugins

- 1-setup-osx-brew.sh
- synfig-studio/images/Makefile.am
- synfig-studio/images/splash_screen_development.sh
- synfig-studio/images/splash_screen_development.sif.in
Also, fix for `splash_screen_development.sif.in`:
Previously it was referencing "synfig_icon.sif", shich was in turn referencing "logo.sif".
Now `splash_screen_development.sif.in` references  "logo.sif" directly.
> Do not use "realpath" command in build process (Autotools)

- synfig-core/src/synfig/importer.cpp
- synfig-core/src/synfig/importer.h
This version with rectangle parameters aren't used anywhere
> remove useless Importer::get_frame overloaded method

- synfig-studio/images/CMakeLists.txt
> Fix for no icon in Import Image Layer for CMake Build.

- synfig-studio/src/synfigapp/actions/layerremove.cpp
- synfig-studio/src/synfigapp/actions/layerremove.h
Now it doesn't try to delete a layer that is inside a layer-group that will be deleted too.
And it should re-add them at their right place when undoing.
fix #1070
> Fix crash undoing layer deletion #1070

- synfig-core/src/modules/lyr_std/timeloop.cpp
Now this example works as described:
https://wiki.synfig.org/Time_Loop_Layer#Contrived_Example
> fixes "local time" of Time Loop layer - fix #479

- synfig-core/src/synfig/canvas.cpp
- synfig-core/src/synfig/savecanvas.cpp
- synfig-core/src/synfig/valuenode.cpp
Improves efficiency, readability maybe, and vanishes some Coverity reports
I've made some minor cleanup too
> avoid duplicated dynamic_cast (other cases)

- synfig-studio/src/gui/cellrenderer/cellrenderer_value.cpp
- synfig-studio/src/gui/cellrenderer/cellrenderer_value.h
- synfig-studio/src/gui/widgets/widget_value.cpp
- synfig-studio/src/gui/widgets/widget_value.h
Previously, to select a new value for a enum parameter (like "Blend method"), user had to:
1. click to select the desired parameter row
2. click on parameter value cell to start editor, i.e.  to show a combobox
3. click once more on the same place, now on the combobox to popup the menu
4. click (again) on the desired new value
This PR removes the step 3.
> allow enum parameter be edited with a double click instead of triple click

- synfig-studio/src/gui/canvasview.cpp
sometimes they don't fit in due to screen size vs. message length
> show workarea task messages as tooltip too

- synfig-studio/src/gui/cellrenderer/cellrenderer_timetrack.cpp
- synfig-studio/src/gui/waypointrenderer.cpp
- synfig-studio/src/gui/waypointrenderer.h
- synfig-studio/src/gui/widgets/widget_curves.cpp
- synfig-studio/src/gui/widgets/widget_timetrack.cpp
Case:
A given parameter P was converted, and its inner parameters were animated.
Timetrack panel shows a summary of those (inner parameter) waypoints in the row of parameter P.
Now it's uses double outline instead of misleading semi-transparency.
Fix #1266
> Different look for indirect waypoints 

- synfig-studio/src/gui/duckmatic.cpp
Unwanted messages appear when user works with bones.
> Cleanup unwanted console messages

- synfig-studio/src/gui/canvasview.cpp
Previously it was hidden in sub-menu:
...now it is available directly after right-click:
(no need to do complex mouse movements ^__^).
> Show interpolation type directly in waypoint's context menu.

- synfig-core/src/synfig/savecanvas.cpp
this is due to changes discussed here https://github.com/synfig/synfig/issues/1284
They will still have trouble in 1.3.x versions :/
> fix bline point order when saving for older canvas (< synfig 1.4)

- synfig-core/src/synfig/savecanvas.cpp
Complementary fix for #1347
It fixes following situation:
- user opens (creates) file in Synfig 1.4
- adds looped advanced outlines with widthpoints
- user saves file in older format
- user opens closes file and opens it again in Synfig 1.4 -> widthpoint positions are wrong.
> fix bline point order when saving for older canvas (part 2)

- synfig-core/src/synfig/loadcanvas.cpp
Closes #1307.
I have used existing functionality which displays warnings on file loading.
The warning looks a bit ugly, but can be improved later.
> Warning when opening file of older version. Closes #1307.

- synfig-studio/plugins/lottie-exporter/lottie-exporter.py
- synfig-studio/plugins/lottie-exporter/plugin.xml.in
- synfig-studio/src/gui/app.cpp
- synfig-studio/src/gui/app.h
- synfig-studio/src/gui/canvasview.cpp
- synfig-studio/src/gui/instance.cpp
- synfig-studio/src/gui/instance.h
- synfig-studio/src/gui/mainwindow.cpp
- synfig-studio/src/gui/pluginmanager.cpp
- synfig-studio/src/gui/pluginmanager.h
Implements most of the things mentioned here: https://github.com/synfig/synfig/issues/1309#issuecomment-606829467
> Rework the plugin system

- synfig-core/src/modules/lyr_std/CMakeLists.txt
- synfig-core/src/modules/lyr_std/Makefile.am
- synfig-core/src/modules/lyr_std/main.cpp
- synfig-core/src/modules/lyr_std/perspective.cpp
- synfig-core/src/modules/lyr_std/perspective.h
This is regarding issue no #1191 
- changes are made in folder synfig-core/src/modules/lyr_std
- wrap.h , wrap.cpp changed to perspective.h, perspective.cpp 
- Updated cmake.list
> warp layer is now renamed to perspective layer

- synfig-studio/src/gui/canvasview.cpp
- synfig-studio/src/gui/mainwindow.cpp
This PR is regarding issue no #1394. Now View-Toolbar menu will hide/show toolbar of all windows.
> View-Toolbar is effective for all canvases

- synfig-studio/src/gui/duck.h
- synfig-studio/src/gui/duckmatic.cpp
- synfig-studio/src/gui/states/state_bline.cpp
- synfig-studio/src/gui/states/state_polygon.cpp
It allows now to close Spline while creating it by clicking on
first vertex, even if the tangents ducks are at same place.
This bogus duck is only used while creating spline, not editing.
> make first vertex selectable when creating spline - Fix #1281

- ETL/ETL/CMakeLists.txt
- synfig-core/src/CMakeLists.txt
- synfig-studio/src/CMakeLists.txt
A few CMake related fixes that came up while creating a snap package (#1398)
All in all, basic stuff. To quote the commits:
> Add include & library dirs for each pkg_config module
> This allows building & linking with libraries in non-standard paths.
> Cmake fixes

- synfig-studio/src/gui/docks/dock_soundwave.cpp
- synfig-studio/src/gui/docks/dock_soundwave.h
- synfig-studio/src/gui/widgets/widget_soundwave.cpp
- synfig-studio/src/gui/widgets/widget_soundwave.h
- synfig-studio/src/gui/widgets/widget_time.cpp
Fix https://github.com/synfig/synfig/issues/1346
> Soundwave dock now loads sound layers from canvas

- synfig-core/src/synfig/guid.cpp
- synfig-core/src/synfig/guid.h
- synfig-core/src/synfig/layers/layer_bitmap.cpp
- synfig-core/src/synfig/loadcanvas.cpp
- synfig-core/src/synfig/node.cpp
- synfig-core/src/synfig/node.h
- synfig-core/src/synfig/transform.cpp
- synfig-core/src/synfig/valuenodes/valuenode_bone.cpp
- synfig-studio/src/gui/duck.cpp
to avoid anybody to mess with its int parameter that could only be zero.
It fixes compiler warnings about unused parameter
> hide GUID int constructor

- synfig-studio/src/gui/widgets/widget_filename.cpp
otherwise the parameter value change is only propagated when widget looses focus or user explicitly activates (by pressing Enter/Return).
If it's a Sound layer, clicking on Play button right after choose a file (and the edit-widget not yet loosing focus), it would play the previous audio.
> activate widget_filename when user chooses file via button/file dialog

- synfig-studio/src/gui/trees/layerparamtreestore.cpp
repetitive quick undo/redo after insert-item-smart could be fatal
> fix crashing when removing spline point too fast

- synfig-core/src/synfig/valuenodes/valuenode_composite.cpp
> DashItem Offset and Length variables are not consistent when editing them

- synfig-core/src/synfig/rendering/surface.cpp
- synfig-core/src/synfig/rendering/surface.h
- synfig-studio/src/gui/canvasview.cpp
- synfig-studio/src/synfigapp/canvasinterface.cpp
- synfig-studio/src/synfigapp/canvasinterface.h
This PR is regarding issue #1138 
- Modified `import_sequence()` function so that it detects and removes duplicates in the sequence.
- User is asked if they want to remove duplicates before importing a sequence.
> Detect duplicated frames when importing image sequence

- synfig-studio/src/gui/widgets/widget_timetrack.cpp
- it happened when switching tab from a doc to another
it just avoids the crash, the cause still has to be investigated
> quick workaround to crash in new timetrack

- synfig-studio/plugins/lottie-exporter/common/Param.py
Radial composite method was failing on some sample files. I will be adding that file to https://gitlab.com/synfig/synfig-tests , but due to some fork errors, I will be add it in around 7 days :'(
So I am attaching that file here: 
[radial_composite.zip](https://github.com/synfig/synfig/files/4674002/radial_composite.zip)
> [Lottie exporter] Refactor radial_composite convert method

- synfig-studio/src/gui/app.cpp
A scrollable dialog window is not intuitive because it'll be shown only
once to the user and at the most with a brief descriptive message
Moved from Gtk::ScrolledWindow to Gtk::Grid
Grid takes care of the window size automatically
Fixes #1376
> Improved warning dialog UI

- synfig-studio/src/synfigapp/actions/valuedescblinelink.cpp
> Fix #1467: "Link to Spline" places vertex into wrong position when Spline is looped

- synfig-studio/Makefile.am
- synfig-studio/configure.ac
- synfig-studio/images/Makefile.am
- synfig-studio/src/gui/Makefile.am
- synfig-studio/src/gui/app.cpp
- synfig-studio/src/gui/app.h
- synfig-studio/src/gui/resourcehelper.cpp
- synfig-studio/src/gui/resourcehelper.h
- synfig-studio/src/gui/splash.cpp
Install icons in `share/synfig/icons/classic` and enable theming instead of `share/pixmaps/(synfigstudio| or not on windows)`.
Regular images are installed in `share/synfig/images`
Other icon set (theme) can be placed in a folder inside `share/synfig/icons/` (eg. `share/synfig/icons/new-theme-folder`)
Theme can be changed at start by setting the envvar SYNFIG_ICON_THEME (eg. `SYNFIG_ICON_THEME=new-theme-folder`)
I didn't touch the CMake stuff... I can't test Windows or Mac and its installation scripts.
> Change installation folder of synfig images and icons

- synfig-studio/src/gui/docks/dock_info.cpp
* Replace deprecated Gtk::Table
* Use bold attribute to highlight the labels X, Y, R, G, B
* Make expandable only the vertical separator (position/color)
* Add tooltip for color components to clarify what the value between
brackets means
> minor improvements in Info panel

- synfig-studio/src/synfigapp/canvasinterface.cpp
Not using modules/layer_std/import/ but synfig/layers/layer_bitmap for importing sequences
This is a fix for issue #1504
> Importing Sequences build fix

- synfig-studio/images/CMakeLists.txt
The new directory matches with the autotools one
For developers using cmake, you have to manually delete the existing
pixmaps/synfigstudio directory
Fixes #1511
> Updated CMake icons directory

- synfig-studio/src/gui/workarea.cpp
> avoid deadlock when converting vector to 'dynamic'

- synfig-studio/plugins/lottie-exporter/common/Param.py
- synfig-studio/plugins/lottie-exporter/settings.py
Added support for Vector X and Vector Y convert method in Lottie exporter plugin.
> [Lottie Exporter] Added support for Vector X and Vector Y convert method

- synfig-core/src/synfig/canvas.cpp
fix #1146
And if user renames a set forcing to a nested one, it avoids forbidden renaming of higher hierarchies.
Example:
Sets
-A
-AB
-AC
by renaming A -> D:
-AB
-AC
-D
(issue 1146 fixed)
by renaming AB -> F.G.H
-AC
-D
-F
\\-G
.   \\-H
and F, F.G can be renamed too thanks commit ef57befe08f6f52cc19b2676c6313db8b4fabb88
> fix renaming a "layer set" - it affected other ones with certain names - #1146

- synfig-studio/images/CMakeLists.txt
Since splash_screen file depends on logo file,
the latter is copied to the current binary directory
fix #1524
> [CMake] Copy logo.sif to build-dir for building splash_screen.png

- 1-setup-osx-brew.sh
- synfig-core/src/CMakeLists.txt
- synfig-core/src/modules/CMakeLists.txt
- synfig-core/src/modules/lyr_freetype/CMakeLists.txt
- synfig-core/src/synfig/CMakeLists.txt
- synfig-studio/src/CMakeLists.txt
Also now you can use XCode for developing.
Generating Xcode project:
```
cmake ../synfig -GXcode
```
if you get error 
```
CMake Error:
Xcode 1.5 not supported.
```
then you need to switch tools:
```
sudo xcode-select --switch /Applications/Xcode.app/
```
> [CMake] Fixed MacOS build

- synfig-core/src/modules/mod_bmp/trgt_bmp.cpp
- synfig-core/src/modules/mod_dv/trgt_dv.cpp
- synfig-core/src/modules/mod_gif/trgt_gif.cpp
- synfig-core/src/modules/mod_jpeg/trgt_jpeg.cpp
- synfig-core/src/modules/mod_mng/trgt_mng.cpp
- synfig-core/src/modules/mod_png/trgt_png.cpp
- synfig-core/src/modules/mod_png/trgt_png_spritesheet.cpp
- synfig-core/src/modules/mod_ppm/mptr_ppm.cpp
- synfig-core/src/modules/mod_ppm/trgt_ppm.cpp
- synfig-core/src/modules/mod_yuv420p/trgt_yuv.cpp
- synfig-core/src/modules/mptr_mplayer/mptr_mplayer.cpp
- synfig-core/src/synfig/filecontainerzip.cpp
- synfig-core/src/synfig/filesystemnative.cpp
- synfig-core/src/tool/main.cpp
- synfig-studio/src/gui/app.cpp
- synfig-studio/src/gui/ipc.cpp
- synfig-studio/src/gui/main.cpp
- synfig-studio/src/gui/render.cpp
- synfig-studio/src/player/main.cpp
Closes #1517.
Previously we used `Glib::locale_to_utf8()` function, and it worked well for simple encodings (i.e. Russian). But for languages which use wide characters (UTF-16) (i.e. Arabic) this didn't worked. So now we use `g_win32_get_command_line()` function instead (https://developer.gnome.org/glib/stable/glib-Windows-Compatibility-Functions.html#g-win32-get-command-line).
But that was not enough. After adding `g_win32_get_command_line()` function the filename was converted properly, but file opening procedure still failing 
After debugging I found that we have to do similar replacement for places where we access filesystem. 
The solution is to use Glib's `g_fopen()` function instead of `fopen()` - https://people.gnome.org/~ryanl/glib-docs/glib-File-Utilities.html#g-fopen.
It is …
> Fix opening files with Arabic names

- synfig-core/src/synfig/exception.cpp
- synfig-core/src/synfig/exception.h
- synfig-studio/src/gui/exception_guard.h
- synfig-studio/src/gui/workarea.cpp
- synfig-studio/src/synfigapp/value_desc.cpp
- synfig-studio/src/synfigapp/value_desc.h
It is related to #231 . It doesn't crash anymore.
A Exported ValueNode duck, if selected, make Studio crash when user unexport the valuenode.
The duck stores a ValueDesc that refers to exported valuenode by its name. When unexported, there isn't a valuenode with that name anymore.
The perfect(?) solution would be to self'destroy' the duck if it detects its valuenode name (id) changed to empty string.
> Don't crash if exception thrown while rendering WorkArea

- synfig-studio/src/gui/trees/historytreestore.cpp
- synfig-studio/src/gui/trees/historytreestore.h
fix crash when undoing creation of a moved/changed vertex of spline
It happened because the history tree rebuilds on every
undo/redo. It doesn't do it anymore.
Long chain:
The history tree row description would call to
Action::ValueDescSet::get_local_name() and it would
make a 'long' stack until it crashes, as follow:
```
-> Action::ValueDescSet::get_local_name()
-> ValueDesc::get_description()
-> ValueDesc::is_exported()
-> ValueDesc::get_value_node()
-> LinkableValueNode::get_link()
```
AND FINALLY it crashes due to the invalid link index!
Test case:
* Create a polygon or spline.
* Click on a vertex to open context menu
* Select "Create Item"
* Move the new vertex
* Ctrl+Z (ok, vertex 'unmoved')
* Ctrl+Z (crash)
> fix crash when undoing creation of a moved/changed vertex of spline

- synfig-studio/src/gui/app.cpp
- synfig-studio/src/gui/app.h
- synfig-studio/src/gui/dialogs/dialog_setup.cpp
- synfig-studio/src/gui/dialogs/dialog_setup.h
- synfig-studio/src/gui/widgets/widget_canvastimeslider.cpp
This fixes the keyboard input **Ctrl+,** & **Ctrl+.** not responding when
thumbnail is displayed under Wayland session
By default, thumbnail preview is turned on so it doesn't affect X11
users
Wayland users can turn it off in Preferences > Editing > Thumbnail
preview section
Fixes #1144
> Added toggleable option for thumbnail preview

- synfig-studio/src/gui/canvasview.cpp
- synfig-studio/src/gui/exception_guard.h
- synfig-studio/src/gui/states/state_polygon.cpp
- synfig-studio/src/gui/states/state_stroke.cpp
a destructor shouldn't throw exception anyway:
https://rules.sonarsource.com/cpp/RSPEC-3654
fix Coverity issues CID 308620, 308960, 308965, 308978, 308612, 344421, 344423, 308639
> fix uncaught exceptions in destructors

- synfig-studio/src/synfigapp/actions/valuenodedynamiclistinsert.cpp
As stated here https://github.com/synfig/synfig/issues/280#issuecomment-591782338 , I don't know if I can just remove the assert,
so let do my work without crash :)
> don't crash debug version when rotating vertex order

- 1-setup-windows-msys2.sh
- synfig-core/src/modules/mod_mng/CMakeLists.txt
The problem was in different compilation flags, since `libmng` was compiled with the `stdcall` convention, and tried to link with the Synfig using `cdecl` convention.
After the compilation flags are added, linker "knows" how to link this library.
> Fixed libmng linking problem on 32-bit platform

- synfig-studio/images/CMakeLists.txt
- synfig-studio/src/gui/CMakeLists.txt
- synfig-studio/src/gui/synfigstudio.rc
Fixes: #1412
Toolbar (not pinned):
Toolbar (pinned):
> Setting up VERSIONINFO resource for CMake Windows builds.

- synfig-studio/src/gui/docks/dock_timetrack.cpp
Reported by tawatoons in https://forums.synfig.org/t/synfig-1-3-15-crash-on-right-clicking-waypoint/11252
It's probably due to a commit reverting for fixing another issue in Windows
> fix old timetrack crashing on waypoint right-clicking

- synfig-studio/src/gui/docks/dock_soundwave.cpp
- synfig-studio/src/gui/docks/dock_soundwave.h
- synfig-studio/src/gui/widgets/widget_keyframe_list.cpp
Its default height was 64px. Now it's 10.
Besides, I also copied the Dock_Curves code for height updating.
fix #1601
> fix big keyframe markers in Dock_SoundLayer (and any other now)

- synfig-core/src/synfig/main.cpp
Glib::locale_to_utf8() doesn't give correct result when path contains multibyte characters (i.e. Arabic symbols).
> Do not use Glib::locale_to_utf8() in synfig::get_binary_path()

- synfig-studio/src/gui/states/state_bone.cpp
Hey!
Issue #1627 
I fixed this. It is basically coz I was giving the second bone as the reference to the calculations of the parameters of the new child bone. In the video, after you changed the first bone, as pointed out in #1626 , the second bone and first bone are not in the same position. So this caused the wrong placement. I guess it works fine now as I'm using first bone. But #1626  still remains!
> [Skeleton Tool] Child bone placed incorrectly on Skeleton Deformation layer

- synfig-studio/src/gui/trees/historytreestore.cpp
Example:
On a new synfig document - without any action history actually -
an unsuccessful image importing (due to it's corrupted), Synfig
crashes (in debug version).
It doesn't occur in previous versions because it was introduced to
fix other crash type.
> fix crash on unsuccessful action with a clean history

- synfig-studio/src/gui/app.cpp
- synfig-studio/src/gui/dialogs/canvasproperties.cpp
- synfig-studio/src/gui/dialogs/dialog_input.cpp
- synfig-studio/src/gui/dialogs/dialog_keyframe.cpp
- synfig-studio/src/gui/render.cpp
- synfig-studio/ui/canvas_options.glade
Fix #1165 
The final order of buttons will be fixed (then we'll deal with different OSes):
Other | Cancel/Close | Ok/Confirm
> Make position of dialog buttons consistent

- synfig-studio/src/gui/widgets/widget_timetrack.cpp
- synfig-studio/src/gui/widgets/widget_timetrack.h
Widget_Timetrack::rebuild_param_info_list() fills param_info_map with parameter panel a newly allocated row info that would override previous value. Previous param_info_map::clear() call wouldn't deallocate them properly.
Therefore, for avoiding this problem, don't use unneeded data via pointers,
but store them directly in param_info_map.
> fix memory leak with Widget_Timetrack: row_info pointer to value

- synfig-core/src/synfig/threadpool.cpp
ThreadPools::threads is filled with threads allocated in ThreadPool::wakeup() . They're never destroyed.
They can be safely deleted after joined.
https://stackoverflow.com/questions/30090299/delete-stdthread-after-calling-join
> fix memory leak on thread pool

- 1-setup-osx-brew.sh
There was a strange message when installing formulas:
```
🍺  /usr/local/Cellar/intltool/0.51.0: 19 files, 185.8K
Checking imagemagick...
Error: Broken pipe
==> Installing dependencies for imagemagick: xz, libpng, libtiff, freetype
```
It was happening because `grep --quiet 'Not installed' ` exits right after the first occurrence of the search string, and pipe is broken. 
Now output is redirected to `/dev/null` instead of using `quiet` mode.
Also added `python` package as explicit dependency and brew formulas list is sorted.
> Fixed 'Error: Broken pipe' message, when installing brew packages on MacOS

- synfig-core/src/modules/CMakeLists.txt
> [CMake] Fixes missing images on MSYS builds.

- synfig-studio/plugins/lottie-exporter/CMakeLists.txt
- synfig-studio/plugins/lottie-exporter/Makefile.am
- synfig-studio/plugins/lottie-exporter/common/Param.py
- synfig-studio/plugins/lottie-exporter/export_without_variable_width.py
- synfig-studio/plugins/lottie-exporter/layers/driver.py
- synfig-studio/plugins/lottie-exporter/layers/shape.py
- synfig-studio/plugins/lottie-exporter/lottie-exporter.py
- synfig-studio/plugins/lottie-exporter/plugin.xml.in
- synfig-studio/plugins/lottie-exporter/properties/shapeKeyframed.py
- synfig-studio/plugins/lottie-exporter/properties/shapePropKeyframe/Makefile.am
- synfig-studio/plugins/lottie-exporter/properties/shapePropKeyframe/constant_width_outline.py
- synfig-studio/plugins/lottie-exporter/properties/shapePropKeyframe/helper.py
- synfig-studio/plugins/lottie-exporter/settings.py
Added support for exporting outlines without variable widths. A few tweaks needed but there is a huge decrease in file size on checking so far :smiley: .
@AnishGG please check
> [Lottie Exporter] Export outlines without variable widths

- cmake/InstallMSYS2.cmake
- synfig-studio/images/CMakeLists.txt
Fixes the issue raised [here](https://github.com/synfig/synfig/issues/1058#issuecomment-683697028) in #1058.
> [CMake] Fixed path for splash screen image and added Adwaita icons for MSYS2 builds.

- CMakeLists.txt
- cmake/InstallMSYS2.cmake
- cmake/SynfigIntltool.cmake
- synfig-studio/CMakeLists.txt
- synfig-studio/images/CMakeLists.txt
- [CMake] Improved cygpath detection in some situations (when you run CMake from IDE for example)
- [CMake] Added error message if MSYS2 environment not detected on Windows. Improved MSYS2 detection by using environment variable (MINGW_PREFIX)
- [CMake] `desktop_file` target disabled for Windows build. Fixes 'sed not found' error
- [CMake] Fixed splash screen image build. It could not be built because the target directory did not exist
- [CMake/MSYS2] Disabled copying of dependent libraries to build output during configuration stage. Added hacks for MSYS2 ImageMagick (required to `build_images` target).
> CMake improvements

- synfig-studio/src/gui/widgets/widget_canvastimeslider.cpp
Set transient property for thumbnail (tooltip) window.
Fixes #1414
> Corrected thumbnail position for Wayland

- synfig-studio/src/gui/widgets/widget_keyframe_list.cpp
On Wayland, it's important to explicitly define the parent-child relationships for GTK widgets.
Fixes #1724
> Corrected keyframe tooltip position for Wayland

- synfig-core/src/modules/mod_magickpp/Makefile.am
related to #1599 , but it was about the CMake building system
> make autotools use imagemagick++ cflags from pkg-config

- synfig-core/src/synfig/main.cpp
Fixes issue #1715 
Redundant warnings were being produced every time the config file synfig_modules.cfg was not found at the given location. However the **_warning should be printed only if all the locations have been checked._**
Hence this line on **main.cpp : 176** can be removed.
The final warning is already printed at line 359 which I have not modified
> Removed Warning Message if Config File is Found

- synfig-core/src/synfig/main.cpp
Fix issue #1754 
Synfig currently searches for` synfig_modules.cfg` in various paths at startup. It is also searching for it on a linux path 
`/usr/local/etc `even on a windows system. This PR adds an `#ifdef`  guard to disable the path on windows.
> Don't search for linux paths on Windows for synfig_modules.cfg

- synfig-studio/src/synfigapp/vectorizer/centerlinepolygonizer.cpp
Changes: Adding braces on `if`-`else` statement on `extractBorders`
Why: To remove dangling else warning message according to issue #1757 
Impact: No dangling else warning message
> Add braces to avoid ambiguous else on extractBorders (fixes [-Wdangling-else] warning)

- synfig-studio/src/gui/dialogs/vectorizersettings.cpp
- synfig-studio/src/gui/states/state_bone.cpp
- synfig-studio/src/gui/workarea.cpp
- synfig-studio/src/synfigapp/actions/valuedesccreatechildbone.cpp
Fix GCC Wreorder warning in the line 209. Do i have to change it elsewhere. Kindly guide 
Thanks :)
> Fix GCC Wreorder Warnings 

- synfig-studio/src/gui/dialogs/about.cpp
Sets modal on about dialog so that it behaves similar to the preferences window.
Closes #1722
> #1722: Set modal property on AboutDialog

- synfig-studio/src/gui/app.cpp
Fixes #1768 
Initially the keyboard shortcuts for:
```
canvas-zoom-in:  ctrl + "="
canvas-zoom-out:  ctrl + "-"
canvas-zoom-fit:  ctrl + shift + "z"
```
The Improved Keyboard shortcuts for : 
```
canvas-zoom-in:  "="
canvas-zoom-out:  "-"
canvas-zoom-fit:  "0"
```
> Improve Canvas Zoom Keyboard Shortcut UX

- CMakeLists.txt
- cmake/SynfigIntltool.cmake
Fixes https://github.com/synfig/synfig/issues/1785
> [MSYS/CMake] Fix hard-coded path (c:/msys64/usr/bin/perl)

- synfig-studio/src/gui/states/state_bone.cpp
- synfig-studio/src/synfigapp/actions/valuedescset.cpp
- synfig-studio/src/synfigapp/canvasinterface.cpp
- synfig-studio/src/synfigapp/canvasinterface.h
> [Skeleton Tool] Automatic change Bone Width parameter in Tool Options Panel (for Skeleton Deformation)

- synfig-studio/src/CMakeLists.txt
- synfig-studio/src/gui/CMakeLists.txt
@ice0 @rodolforg 
This will solve the issue #1766 
I've added fontconfig support in the FontFamily widget by editing its cmake files . 
Kindly review it and guide me further if i have to make some changes.
Thanks :)
> Adding FontConfig Support in FontFamily Widget

- synfig-studio/configure.ac
- synfig-studio/src/gui/CMakeLists.txt
- synfig-studio/src/gui/Makefile.am
- synfig-studio/src/gui/app.cpp
- synfig-studio/src/gui/canvasview.cpp
- synfig-studio/src/gui/dials/keyframedial.cpp
- synfig-studio/src/gui/dials/resolutiondial.cpp
- synfig-studio/src/gui/docks/dock_history.cpp
- synfig-studio/src/gui/docks/dock_info.cpp
- synfig-studio/src/gui/docks/dock_keyframes.cpp
- synfig-studio/src/gui/docks/dock_layergroups.cpp
- synfig-studio/src/gui/docks/dock_layers.cpp
- synfig-studio/src/gui/docks/dock_metadata.cpp
- synfig-studio/src/gui/docks/dock_soundwave.cpp
- synfig-studio/src/gui/modules/mod_palette/dock_paledit.cpp
- synfig-studio/src/gui/resourcehelper.cpp
- synfig-studio/src/gui/resourcehelper.h
- synfig-studio/src/gui/resources/CMakeLists.txt
- synfig-studio/src/gui/resources/Makefile.am
- synfig-studio/src/gui/resources/css/CMakeLists.txt
- synfig-studio/src/gui/resources/css/Makefile.am
- synfig-studio/src/gui/resources/css/synfig.css
- synfig-studio/src/gui/resources/css/synfig.mac.css
- synfig-studio/src/gui/widgets/widget_defaults.cpp
- synfig-studio/src/gui/widgets/widget_timetrack.cpp
Fixes #1061
Fixes #1390
- Compile OS X specific code only in its environment
- Use classes to apply changes to multiple widgets
- Use ids to apply changes to specific widgets
- Don't style dialogs
Use [Windows](https://stackoverflow.com/questions/37035936/how-to-get-native-windows-decorations-on-gtk3-on-windows-7-and-msys2) gtk3 theme to have a proper global look and feel instead of modifying UI by hand.
In my opinion, synfigstudio main window toolbar buttons need to be scaled down for every platform for space efficiency. But not the other parts of GUI ie., dialogs and their buttons. These things should be left alone. Or let third-party themes do the trick. Like this [Windows 8](https://www.gnome-look.org/p/1013223/) theme.
<strike>I need help with styling timeslider. Couldn't figure out …
> Improved css

- synfig-studio/src/gui/app.cpp
Also changed old redo shortcut from `Ctrl+r` to `Ctrl+y`
Closes #1005
> Improved redo shortcut for Linux

- ETL/configure.ac
- synfig-core/configure.ac
- synfig-studio/configure.ac
Build output is much cleaner now when using autotools
> [Autotools] Verbose mode is disabled by default

- synfig-studio/src/gui/dialogs/dialog_color.cpp
- synfig-studio/src/gui/dialogs/dialog_gradient.cpp
fix #1713
As a consequence, application shortcuts/hotkeys will only work
when those dialogs are not on focus, but this behaviour
should be expected by user.
> restore ctrl-c ctrl+v ctrl+a in Color and Gradient Dialogs

- README.md
The links to building docs were broken. This change points to the building index page.
> Update link to build docs

- synfig-core/src/synfig/valuenodes/valuenode_animatedinterface.cpp
The boolean value set in a given timepoint is kept until
a new waypoint.
As before, it ignores any set of interpolation type.
fix #1825 and #658
> fix animation interpolation for boolean values

- synfig-core/src/modules/mod_ffmpeg/trgt_ffmpeg.cpp
MPEG-1 cannot work with 'le' (pcm_s16le) audio format, it requires 'be' (pcm_s16be)
> Fixed error when output to MPEG-1 format with audio

- autobuild/osx/app-template/Contents/Info.plist
- autobuild/osx/synfig_osx_launcher.cpp
Improved Info.plist (https://developer.apple.com/documentation/bundleresources/information_property_list?language=objc)
- Multiple instances prohibited
- SynfigStudio.app will launch even if renamed
- SynfigStudio.app will launch even if contain spaces in name
> [MacOS] Fixed SynfigStudio.app won't start if renamed

- synfig-core/src/synfig/valuenodes/valuenode_blinecalctangent.cpp
Part of https://github.com/synfig/synfig/issues/1731
This fixes crash in 'Spline Tangent' converter similar to one that was addressed in 'Spline Vertex' previously.
> Fix crash in Spline Tangent converter

- 1-setup-linux-native.sh
Problem with `1-setup-linux-native.sh` when `ID_LIKE` contains space, for example, in Pop!_OS `ID_LIKE="ubuntu debian"`
```
Detecting Linux OS...
./1-setup-linux-native.sh: line 33: [: ubuntu: binary operator expected
ID_LIKE=ubuntu debian
VERSION_ID=20.10
./1-setup-linux-native.sh: line 41: [: ubuntu: binary operator expected
Checking dependencies...
WARNING: This build script does not work with package management systems other than yum, zypper, apt or pacman! You should install dependent packages manually.
REQUIRED PACKAGES: 
libpng-devel libjpeg-devel freetype-devel fontconfig-devel atk-devel pango-devel cairo-devel gtk3-devel gettext-devel libxml2-devel libxml++-devel gcc-c++ autoconf automake libtool libtool-ltdl-devel shared-mime-info OpenEXR-devel libmng-devel ImageMagick-c++-devel …
```
> Add double quotes and option when ID_LIKE=ubuntu debian in PopOS

- synfig-studio/src/gui/app.cpp
- synfig-studio/src/gui/app.h
- synfig-studio/src/gui/dialogs/dialog_setup.cpp
- synfig-studio/src/gui/dialogs/dialog_setup.h
- synfig-studio/src/gui/instance.cpp
> Restore Defaults is applied only on OK pressed

- synfig-studio/src/gui/workarearenderer/renderer_background.cpp
- synfig-studio/src/gui/workarearenderer/renderer_background.h
- synfig-studio/src/gui/workarearenderer/renderer_bbox.cpp
- synfig-studio/src/gui/workarearenderer/renderer_bbox.h
- synfig-studio/src/gui/workarearenderer/renderer_bonesetup.cpp
- synfig-studio/src/gui/workarearenderer/renderer_bonesetup.h
- synfig-studio/src/gui/workarearenderer/renderer_canvas.cpp
- synfig-studio/src/gui/workarearenderer/renderer_canvas.h
- synfig-studio/src/gui/workarearenderer/renderer_dragbox.cpp
- synfig-studio/src/gui/workarearenderer/renderer_dragbox.h
- synfig-studio/src/gui/workarearenderer/renderer_ducks.cpp
- synfig-studio/src/gui/workarearenderer/renderer_ducks.h
- synfig-studio/src/gui/workarearenderer/renderer_grid.cpp
- synfig-studio/src/gui/workarearenderer/renderer_grid.h
- synfig-studio/src/gui/workarearenderer/renderer_guides.cpp
- synfig-studio/src/gui/workarearenderer/renderer_guides.h
- synfig-studio/src/gui/workarearenderer/renderer_timecode.cpp
- synfig-studio/src/gui/workarearenderer/renderer_timecode.h
* remove unused #include
* remove extra whitespace inside method arguments
* remove unused "using namespace"
* move macro #define for rendering colors to implementation file
* remove unused (and wrong) method in Renderer_Timecode
* remove unnecessary constructors
* some other minor changes
> minor cleanup in WorkArea Renderers

- synfig-studio/src/gui/docks/dialog_tooloptions.cpp
When `Tools` without user editable options are selected, the label in the `Tool Options` window is not vertically centered.
This is unpleasant to look at.
This merge request centers the label vertically:
Before:
After:
> "This tool has no options" label now centered vertically

- synfig-studio/src/gui/dialogs/dialog_waypoint.cpp
The order of buttons in `Waypoint Editor`:
Ok | Apply | Delete | Close
is changed to:
Delete | Apply | Close | Ok
for consistency (see #1638).
> Change order of Waypoint Editor buttons to match other dialogs

- synfig-core/src/synfig/Makefile.am
Synfig fails to build with 3-step build (ETL, core, studio)
> [Autotools] Added missing `synfig_export.h` file

- synfig-core/src/synfig/valuenodes/valuenode_blinecalctangent.cpp
- synfig-core/src/synfig/valuenodes/valuenode_blinecalcwidth.cpp
Fix https://github.com/synfig/synfig/issues/1731
This is the final part. Feel free to close the linked issue after merging.
The pull request contains two commits:
* First fixes crash in 'Spline Width' converter when you try to wrap it in 'Switch'. Similar to previously addressed in 'Spline Vertex' and 'Spline Tangent' converters.
* Second addresses the regression introduced in this commit: a90d014c56f0cbee21c2ab0ef68936b9e84c49b1
It was no longer possible to convert real values to 'Spline Tangent/Width' and angle to 'Spline Tangent'. The reason is that upon creation of converter the size of spline would be zero and code will always return ValueBase of vector type so 'Bad Connection' error would be thrown (expected real, got vector). See linked issue for screenshot of the error.
> Fix crash in Spline Width and return of improper type in Spline converters

- synfig-core/src/synfig/palette.cpp
- synfig-studio/src/gui/modules/mod_palette/dock_paledit.cpp
- [Synfig Studio] Cleanup Palette editor code
- [Synfig Studio/Windows] Fixed crash when trying to save a palette to a file with a non-Latin name
- [Synfig Studio/Windows] Fixed saving/loading palette to file with non-Latin name
> [Synfig Studio/Windows] Fixed load/save operations for Palette editor

- synfig-studio/src/gui/asyncrenderer.cpp
- synfig-studio/src/gui/workarea.cpp
- synfig-studio/src/gui/workarearenderer/CMakeLists.txt
- synfig-studio/src/gui/workarearenderer/Makefile_insert
- synfig-studio/src/gui/workarearenderer/renderer_canvas.cpp
- synfig-studio/src/gui/workarearenderer/renderer_canvas.h
- synfig-studio/src/gui/workarearenderer/renderer_frameerror.cpp
- synfig-studio/src/gui/workarearenderer/renderer_frameerror.h
It now displays the exception message inside WorkArea when the current frame throws an exception.
It also displays an error dialog while animating in WorkArea
**Description**
If a frame throws an exception/error, Synfig shows its message:
- in console/prompt
- in work area at problematic frame:
- via error message dialog, while animating:
fix crash-bug reported in forums by lgolden:
https://forums.synfig.org/t/lst-file-from-papagayo-crashes-synfig/11540
> [Synfig Studio] Fixed crash when frame rendering throws exception while animating

- synfig-studio/src/gui/app.cpp
> [Synfig Studio] Center "Scale to fit Canvas" switch vertically to avoid stretching

- synfig-studio/src/gui/canvasview.cpp
> [Synfig Studio] Don't expand Interpolation widget more than allocated width

- synfig-studio/src/gui/app.cpp
> [Synfig Studio] Don't expand File Format Version dropdown

- synfig-studio/src/gui/resources/ui/preview_options.glade
With current master it's possible to increase the size of `Preview Options` dialog:
which has no benefit for user and is not pleasant to look at.
> [Synfig Studio] Disabled resizing of the Preview Options dialog

- synfig-studio/src/gui/canvasview.cpp
- synfig-studio/src/gui/canvasview.h
- synfig-studio/src/gui/iconcontroller.cpp
Fix #1451
Fixes also a typo in `iconcontroller.cpp` required to display guides icons.
> [Synfig Studio] Add Show/Snap Guides to Toolbar

- synfig-studio/src/gui/canvasview.cpp
> [Synfig Studio] Make sure Show/Snap Guides toolbar buttons are always working

- synfig-studio/src/gui/docks/dock_toolbox.cpp
Previously, it could show the word "asterisk" instead of
character * for Star tool, for example.
> [Synfig Studio] fix states accelerator shortcut in tooltips

- synfig-core/src/synfig/rendering/opengl/internal/glsl/Makefile_insert
By default, `_DATA` files are not included in a distribution (https://www.gnu.org/software/automake/manual/html_node/Data.html)
So we need to add `dist_` prefix.
Fix https://github.com/synfig/synfig/issues/311
> [Autotools] Fixed problem with missing *.glsl files in distribution

- synfig-studio/src/gui/canvasview.cpp
- synfig-studio/src/gui/dialogs/dialog_preview.cpp
- synfig-studio/src/gui/dials/framedial.cpp
- synfig-studio/src/gui/preview.cpp
- synfig-studio/src/gui/resources/ui/preview_options.glade
Currently Preview Dialog is not consistent with other parts of Synfig's UI.
This merge request makes the tooltips used in the Preview Dialog consistent with Canvas player.
In addition the title of Preview Options was changed to Preview Settings to match its content (similar to Render Settings).
Fixes #1946
> [Synfig Studio] Make Preview tooltips and titles consistent with other dialogs

- synfig-studio/src/gui/resources/ui/dialog_workspaces.glade
Current layout:
Improved layout:
> [Synfig Studio] Improve layout of Workspaces editor

- synfig-core/src/synfig/valuenodes/valuenode_composite.cpp
> [Core] fix missing is_distance hint for vertex coordinates

- synfig-studio/src/gui/app.cpp
- synfig-studio/src/gui/modules/module.cpp
neither constructors.
The derived methods are not called, but those from the class itself.
https://scc.ustc.edu.cn/zlsc/sugon/intel/ssadiag_docs/pt_reference/references/sc_cpp_virtual_call_in_dtor.htm
https://wiki.sei.cmu.edu/confluence/display/cplusplus/OOP50-CPP.+Do+not+invoke+virtual+functions+from+constructors+or+destructors
> [Synfig Studio] destructors should not call virtual methods

- synfig-studio/src/gui/docks/dockable.cpp
- synfig-studio/src/gui/docks/dockable.h
- synfig-studio/src/gui/docks/dockbook.cpp
Now user doesn't need to drag panel out to undock it.
Some users couldn't figure it out easily how to do it, so
here we give them an alternative way.
Discussed here: https://forums.synfig.org/t/moving-panels-in-layout/11634
And move the undocked panel near to the mouse position
> [Synfig Studio] Added ability to undock panel using the context menu command

- synfig-studio/Makefile.am
- synfig-studio/configure.ac
- synfig-studio/src/synfigapp/actions/layerduplicate.cpp
- synfig-studio/src/synfigapp/actions/layerduplicate.h
- synfig-studio/src/synfigapp/actions/valuenodeadd.cpp
- synfig-studio/src/synfigapp/canvasinterface.cpp
- synfig-studio/test/Makefile.am
- synfig-studio/test/app_layerduplicate.cpp
Two problems fixed:
- #1921
- User wants to duplicate two layers "duplicate" in different groups (user would receive a error dialog and he'd need to duplicate again, but one layer at a time in order to get work done)
And it implements a test for LayerDuplicate action (in `synfig-studio/test`folder). For Autotools, build and run it with `make check` ;)
> [Synfig Studio] Fix action LayerDuplicate with layers "duplicate" o.O

- synfig-core/src/synfig/threadpool.cpp
- synfig-core/src/synfig/threadpool.h
- synfig-studio/src/gui/app.cpp
- synfig-studio/src/gui/app.h
- synfig-studio/src/gui/dialogs/dialog_setup.cpp
- synfig-studio/src/gui/dialogs/dialog_setup.h
fix - #1410 
I am new to GTK :turtle: 
pls help me in verifying the logic 
currently, it only changes the core to 3 ( I don't know how to check [ how many cores is running ] )
> [Synfig Studio] Allow to set number of rendering threads from Preferences dialog

- ETL/ETL/_stringf.h
- synfig-core/src/modules/mod_ffmpeg/trgt_ffmpeg.cpp
This problem mentioned by @rodolforg here: https://github.com/synfig/synfig/pull/1952, so I fixed it.
> etl::absolute_path() trusting on getcwd(), that doesn't handle the famous encoding problems.
> [ETL] current_working_directory() function now works correctly with non-Latin filenames

- ETL/ETL/_surface.h
- synfig-core/src/modules/mod_magickpp/trgt_magickpp.cpp
- synfig-core/src/modules/mod_mng/trgt_mng.cpp
- synfig-core/src/synfig/blur.cpp
- synfig-core/src/synfig/color/colormatrix.cpp
- synfig-studio/src/gui/app.cpp
- synfig-studio/src/gui/canvasview.cpp
- synfig-studio/src/gui/trees/childrentreestore.cpp
- synfig-studio/src/gui/widgets/widget_timetrack.cpp
- synfig-studio/src/synfigapp/actions/valuenodesetactivebone.cpp
- synfig-studio/src/synfigapp/vectorizer/centerlinepolygonizer.cpp
- static_cast<void*> used to disable warning "clearing an object of non-trivial type...". This can be removed after synfig::Color will be trivial;
- Removed unused variables;
- Fixed warning: comparison between signed and unsigned integer expressions.
> [ETL/Core] Fixed warnings

- ETL/ETL/_smart_ptr.h
- ETL/Makefile.am
- ETL/test/benchmark.cpp
- ETL/test/clock.cpp
- autobuild/synfigstudio-release.sh
- synfig-core/Makefile.am
- synfig-core/bootstrap.sh
- synfig-studio/Makefile.am
- synfig-studio/build_tools/Makefile.am
- synfig-studio/images/Makefile.am
- synfig-studio/src/gui/Makefile.am
- Now `synfigstudio-release.sh` script can be run from any folder;
- `synfigstudio-release.sh` - creates `_release` folder and works inside it, this fixes error `configure: error: source directory already configured; run “make distclean” there first`, when you try to build Synfig after this script.
P.S.
There is still an error here: 
```
ERROR: files left after uninstall:
./share/pixmaps/sif_icon.ico
./share/pixmaps/synfig_icon.ico
./share/synfig/icons/classic/about_icon.png
./share/synfig/icons/classic/action_add_to_set_icon.png
...
./share/synfig/icons/classic/valuenode_icon.png
./share/synfig/images/installer_logo.bmp
./share/synfig/images/installer_logo_osx.png
./share/synfig/images/splash_screen.png
```
I don't know why they are not removed. 
@rodolforg Any ideas here?
> [Autotools] Fixed `make distcheck`. Reduced build output for synfigstudio-release.sh script

- synfig-studio/src/gui/trees/layertree.cpp
> [Synfig Studio] avoid dereference of invalid TreeIter on Layer TreeView

- synfig-studio/src/gui/states/state_bone.cpp
- remove debug messages
- properly check for desired property change: ValueNode_Bone
- fix checking for indices: it should be 5 or 7, not 6 or 7
- for avoiding such problems, use link names
> [Synfig Studio] Bone Tool: fix bone width on wrong situations

- synfig-studio/src/synfigapp/actions/layerduplicate.cpp
- synfig-studio/test/app_layerduplicate.cpp
If action LayerDuplicate has among the layers to be duplicated a
layer named "a" that is 'inside' of a group layer (pastecanvas)
named "g". In case of "g" is a layer included in the action layer
list too, don't duplicate the "a" twice, ie. the group and
its contents - including "a" - are duplicated, but "a" won't
be duplicated again.
It would clash the GUID of both "a" duplicates, and that leads
to crash.
A way to avoid it in a general way would be too troublesome :P
Many hierarchy levels and special GUIDs to handle.
Regular (and advanced) user normally won't need it, anyway.
Full description and minor discussion here:
https://forums.synfig.org/t/proposal-of-change-of-behavior-duplicating-both-group-and-an-inner-layer/11823
> [Synfig Studio] don't let inner layer be duplicated twice

- synfig-studio/src/gui/trees/layertree.cpp
- synfig-studio/src/gui/trees/layertree.h
LayerTree is a fake widget. Its goal is to provide the (real) layer and parameter TreeViews. It isn't supposed to add it to any dialog or container. However, it contains deprecated and unused widgets from the time it was a real "widget". 
I removed its unused/invisible/useless inner widgets and their signal handling. It speeds up a lot the layer movements by drag'n drop. For example, `studio::LayerTree::on_blend_method_changed()` was called at least 24 times while dragging a layer row in the Layer Panel.
After that, I saw `on_dirty_preview()` was empty and it wouldn't make sense to update neither Layer nor Parameter Panels if `CanvasInterface` emits this signal: `LayerTreeStore` already monitors layer changes (adding/removing/raising/lowering/…) Therefore, I removed `on_dirty_preview()` …
> [Synfig Studio] Minor cleanup on LayerTree

- synfig-studio/src/synfigapp/actions/layerduplicate.cpp
- synfig-studio/src/synfigapp/actions/layerduplicate.h
- synfig-studio/test/app_layerduplicate.cpp
Now Bone Links are properly fixed when duplicating a skeleton
layer AND layers linked to its bones
Note, however, that duplicating a skeleton doesn't duplicate
the layers linked to its bone by itself: those layers should
be included in 'layers' parameter of this action
It still doesn't work on copy and paste, but with Duplicate action.
> [Synfig Studio] fix action LayerDuplicate for skeleton and its bone links!

- synfig-core/src/synfig/value.cpp
- synfig-core/src/synfig/value.h
- synfig-core/src/synfig/valuenode.cpp
- synfig-core/src/synfig/valuenode.h
- synfig-core/src/synfig/valuenodes/valuenode_add.cpp
- synfig-core/src/synfig/valuenodes/valuenode_add.h
- synfig-core/src/synfig/valuenodes/valuenode_integer.cpp
- synfig-core/src/synfig/valuenodes/valuenode_integer.h
- synfig-core/src/synfig/valuenodes/valuenode_range.cpp
- synfig-core/src/synfig/valuenodes/valuenode_range.h
- synfig-core/src/synfig/valuenodes/valuenode_real.cpp
- synfig-core/src/synfig/valuenodes/valuenode_real.h
- synfig-core/src/synfig/valuenodes/valuenode_scale.cpp
- synfig-core/src/synfig/valuenodes/valuenode_scale.h
- synfig-studio/src/synfigapp/actions/valuedescset.cpp
Instead of limiting get_inverse() method to only a few valuenodes,
and to let synfigapp action ValueDescSet more generalistic,
LinkableValueNode now has to two methods to provide the inverse
transformation of a value.
> [Core] LinkableValueNode provides methods for inverse manipulation

- synfig-studio/src/gui/dialogs/canvasproperties.cpp
Refresh was being called by CanvasProperties directly rather than being connected to signal_show() as demonstrated in CanvasOptions.
This is my first pull request, so any feedback is appreciated.
> [Synfig Studio] The canvas properties dialog now displays values correctly after being closed with the window close button.

- synfig-studio/src/gui/states/state_bline.cpp
- synfig-studio/src/gui/states/state_circle.cpp
- synfig-studio/src/gui/states/state_draw.cpp
- synfig-studio/src/gui/states/state_eyedrop.cpp
- synfig-studio/src/gui/states/state_gradient.cpp
- synfig-studio/src/gui/states/state_lasso.cpp
- synfig-studio/src/gui/states/state_mirror.cpp
- synfig-studio/src/gui/states/state_normal.cpp
- synfig-studio/src/gui/states/state_polygon.cpp
- synfig-studio/src/gui/states/state_rectangle.cpp
- synfig-studio/src/gui/states/state_rotate.cpp
- synfig-studio/src/gui/states/state_scale.cpp
- synfig-studio/src/gui/states/state_sketch.cpp
- synfig-studio/src/gui/states/state_smoothmove.cpp
- synfig-studio/src/gui/states/state_star.cpp
- synfig-studio/src/gui/states/state_text.cpp
- synfig-studio/src/gui/states/state_width.cpp
Migrate toolbox layouts from `Gtk::Table` (deprecated) to `Gtk::Grid`.
> [Synfig Studio] Toolbox migration from Gtk::Table to Gtk::Grid

- synfig-studio/src/gui/docks/dock_info.cpp
- synfig-studio/src/gui/docks/dock_info.h
- synfig-studio/src/gui/resources/css/synfig.css
> [Synfig Studio] Stop rendering button has been moved to the right of the progress bar

- synfig-studio/src/gui/preview.cpp
> [Synfig Studio] Reset progress bar in Info window as Preview rendering is stopped

- synfig-studio/src/gui/states/state_bline.cpp
- synfig-studio/src/gui/states/state_circle.cpp
- synfig-studio/src/gui/states/state_draw.cpp
- synfig-studio/src/gui/states/state_gradient.cpp
- synfig-studio/src/gui/states/state_lasso.cpp
- synfig-studio/src/gui/states/state_polygon.cpp
- synfig-studio/src/gui/states/state_rectangle.cpp
- synfig-studio/src/gui/states/state_star.cpp
- synfig-studio/src/gui/states/state_text.cpp
Replace deprecated `Gtk::HScale` used in toolboxes with `Gtk::Scale`.
Also fine-tuned step increment so that with mouse scroll the step is of 0.1, with arrows 0.01 and with Ctrl+arrows is 0.1 instead of some predefined step increment.
> [Synfig Studio] Replace deprecated Gtk::HScale with Gtk::Scale

- synfig-studio/src/gui/dialogs/canvasproperties.cpp
- `Gtk::Table`
- `Gtk::VBox`
- `set_alignment()`
Looking into the code there's a lot of deprecated stuff that need to be replaced, I'll probably create many pull requests like this one.
Let me know if it's ok or I'm messing things up!
> [Synfig Studio] Replace Canvas Properties deprecated methods and disable window resizing

- synfig-core/src/modules/mod_particle/plant.cpp
- synfig-core/src/synfig/layer.cpp
- synfig-core/src/synfig/layer.h
- synfig-core/src/synfig/module.h
Fixed: LNK2001 Unresolved external symbol "public: static char const *
const synfig::Layer_Shape::name__"
- Global static symbols must be properly exported for the MSVC compiler to find them (functions are exported/imported automatically).
Also there is a problem here to declare these symbols as imported/exported.
The base `Layer` class should export these fields, but the derived `Layer_Shape` should import them from the `Base` class and
export them again.
So the simplest solution here is to switch from static symbols to functions.
> [MSVC] Fixed unresolved external symbol error when building `lyr_std`

- synfig-studio/src/gui/dialogs/dialog_preview.cpp
- synfig-studio/src/gui/dialogs/dialog_preview.h
- synfig-studio/src/gui/render.cpp
- `Gtk::Table`
- `Gtk::VBox`
- `set_alignment()`
> [Synfig Studio] Replace Render and Preview dialogs deprecated methods

- synfig-core/src/synfig/string_helper.cpp
- synfig-core/src/synfig/string_helper.h
- synfig-studio/src/gui/widgets/widget_vector.cpp
Example:
In Canvas Properties dialog, we have the Image Area delimited by two points:
the top left corner and the bottom right corner.
Both points use Widget_Vector to edit it.
There, you could only type real numbers by using 'dot' (.) to separate
integer from the fractional part (e.g. 4.5). However, this character
depends on locale. Brazil and Germany, for example, use 'comma' (,).
Another case: on the same dialog, the Focus Point field.
This commit also fixes synfig::remove_trailing_zeroes() - I accidentally
let two chars to be summed instead of appending them to string
> [Synfig Studio] Sometimes Widget_Vector didn't use locale for decimal separator

- synfig-studio/src/gui/canvasview.cpp
Fixes https://github.com/synfig/synfig/issues/2087
> [Synfig Studio] Exported canvas can be reopened after closing

- synfig-studio/src/gui/canvasview.cpp
- synfig-studio/src/gui/dialogs/canvasproperties.cpp
- synfig-studio/src/gui/dialogs/dialog_ffmpegparam.cpp
- synfig-studio/src/gui/dialogs/dialog_soundselect.cpp
- synfig-studio/src/gui/dialogs/dialog_spritesheetparam.cpp
- synfig-studio/src/gui/dialogs/dialog_template.cpp
- synfig-studio/src/gui/dialogs/dialog_waypoint.cpp
- synfig-studio/src/gui/dials/framedial.cpp
- synfig-studio/src/gui/dials/jackdial.cpp
- synfig-studio/src/gui/dials/keyframedial.cpp
- synfig-studio/src/gui/dials/resolutiondial.cpp
- synfig-studio/src/gui/dials/toggleducksdial.cpp
- synfig-studio/src/gui/dials/zoomdial.cpp
- synfig-studio/src/gui/preview.cpp
- synfig-studio/src/gui/renddesc.cpp
- synfig-studio/src/gui/render.cpp
- synfig-studio/src/gui/resources/css/synfig.css
- synfig-studio/src/gui/splash.cpp
- synfig-studio/src/gui/widgets/widget_defaults.cpp
- synfig-studio/src/gui/widgets/widget_keyframe_list.cpp
- synfig-studio/src/gui/widgets/widget_link.cpp
- synfig-studio/src/gui/widgets/widget_waypoint.cpp
- `set_alignment()`
- `set_padding()`
> [Synfig Studio] Replace set_alignment and set_padding deprecated methods

- synfig-studio/src/gui/docks/dockbook.cpp
even when it's a solo panel in a floating window.
Related to #2047
> [Synfig Studio] 'Undock Panel' menu item is no longer visible for already undocked panels

- synfig-studio/src/gui/app.cpp
> [Synfig Studio] Added Ctrl+E as keyboard shortcut for the "Save All" menu action

- synfig-studio/src/gui/dialogs/canvasproperties.cpp
- synfig-studio/src/gui/dialogs/dialog_color.cpp
- synfig-studio/src/gui/dialogs/dialog_ffmpegparam.cpp
- synfig-studio/src/gui/dialogs/dialog_gradient.cpp
- synfig-studio/src/gui/dialogs/dialog_soundselect.cpp
- synfig-studio/src/gui/dialogs/dialog_template.cpp
- synfig-studio/src/gui/dialogs/dialog_waypoint.cpp
- synfig-studio/src/gui/instance.cpp
- synfig-studio/src/gui/render.cpp
- `get_vbox()`
Didn't replace the method in vectorizersettings.cpp as it will be replaced in #2080
> [Synfig Studio] Replace deprecated get_vbox() method

- synfig-studio/src/gui/canvasview.cpp
- synfig-studio/src/gui/dialogs/dialog_input.cpp
- synfig-studio/src/gui/docks/dock_curves.cpp
- synfig-studio/src/gui/docks/dock_curves.h
- synfig-studio/src/gui/docks/dock_layergroups.h
- synfig-studio/src/gui/docks/dock_layers.h
- synfig-studio/src/gui/docks/dock_navigator.cpp
- synfig-studio/src/gui/docks/dock_navigator.h
- synfig-studio/src/gui/docks/dock_soundwave.cpp
- synfig-studio/src/gui/docks/dock_soundwave.h
- synfig-studio/src/gui/docks/dock_timetrack.cpp
- synfig-studio/src/gui/docks/dock_timetrack.h
- synfig-studio/src/gui/docks/dock_timetrack2.cpp
- synfig-studio/src/gui/docks/dock_timetrack2.h
- synfig-studio/src/gui/docks/dock_toolbox.h
- synfig-studio/src/gui/preview.h
- synfig-studio/src/gui/widgets/widget_defaults.cpp
- synfig-studio/src/gui/widgets/widget_defaults.h
- `Gtk::HScale`
- `Gtk::HSeparator`
- `Gtk::HScrollbar`
- `Gtk::VScrollbar`
> [Synfig Studio] Replace some other deprecated Gtk libraries

- CMakeLists.txt
- ETL/CMakeLists.txt
- synfig-core/CMakeLists.txt
- synfig-core/src/CMakeLists.txt
- synfig-studio/CMakeLists.txt
- synfig-studio/src/CMakeLists.txt
Actually we need version 3.1 at the moment
> [CMake] Bump minimum required CMake version to 3.5

- synfig-studio/src/gui/docks/dock_info.cpp
- synfig-studio/src/gui/states/state_bline.cpp
- synfig-studio/src/gui/states/state_circle.cpp
- synfig-studio/src/gui/states/state_draw.cpp
- synfig-studio/src/gui/states/state_gradient.cpp
- synfig-studio/src/gui/states/state_lasso.cpp
- synfig-studio/src/gui/states/state_polygon.cpp
- synfig-studio/src/gui/states/state_rectangle.cpp
- synfig-studio/src/gui/states/state_rotate.cpp
- synfig-studio/src/gui/states/state_scale.cpp
- synfig-studio/src/gui/states/state_sketch.cpp
- synfig-studio/src/gui/states/state_star.cpp
- synfig-studio/src/gui/states/state_text.cpp
- synfig-studio/src/gui/states/state_width.cpp
- `Gtk::HBox`
and some comments cleaning as well.
> [Synfig Studio] Replacing Gtk::HBox with Gtk::Box

- CMakeLists.txt
- ETL/CMakeLists.txt
- ETL/test/CMakeLists.txt
Now tests can be run with `make test` command.
Tests cannot be built at this time due to the lack of GLib dependency.
This will be fixed later.
> [CMake] Fixed ETL tests

- synfig-studio/src/gui/canvasview.cpp
> [Synfig Studio] Align close button of animation tabs to the right for better looking layout

- CMakeLists.txt
- synfig-core/src/CMakeLists.txt
- synfig-studio/src/CMakeLists.txt
The MLT library has already been made optional for MSVC build.
This commit disables the use of MLT if MLT library not found.
Now Synfig builds correctly on any system without MLT library.
> [CMake] Synfig now builds correctly on any system without MLT library

- 1-setup-osx-brew.sh
`pip3` is part of the python formula, so it's already installed with
`brew install python` command
This change was introduced in this commit: 2a886a8. As you can
see there is no python formula here, this is why it was not detected.
Also `Homebrew` uses `pip3` not `pip` binary.
> [MacOS] Removed unnecessary pip installation

- 1-setup-linux-native.sh
The dependencies install script has been updated to support systems that have PipeWire installed as a replacement for PulseAudio.
PipeWire is introduced in the desktop version of Fedora 34 (https://fedoraproject.org/wiki/Changes/DefaultPipeWire). 
Fixes #2140
Gather all other dependencies first then append our value with the appropriate audio-devel kit: pipewire for fedora starting from version 34 and jack for older versions
> `1-setup-linux-native.sh` script now supports PipeWire

- ETL/configure.ac
- synfig-core/configure.ac
- synfig-studio/configure.ac
- synfig-studio/org.synfig.SynfigStudio.appdata.xml.in
- synfig-studio/src/gui/CMakeLists.txt
I am starting preparations for 1.4.2 release!
* **Bump version to 1.4.2** - This is the first commit I have made, it is automatically created when I executed script `./version-bump.sh 1.4.2` from Synfig's source dir (according to instructions here - https://synfig-docs-dev.readthedocs.io/en/latest/common/release.html#update-version-number).
> [Release] Starting preparations for releasing v1.4.2

- synfig-studio/src/gui/app.cpp
Expanded support for some types of errors:
**Before**
**After**
> Improved error reporting [studio]

- synfig-core/src/synfig/string_helper.cpp
This error appears when starting Synfig:
MinGW C++ std::locale accepts "C" and "POSIX" and
it does not support other locales.
> Fixed 'locale::facet::_S_create_c_locale name not valid' error when compiling with MinGW compiler

- synfig-studio/src/gui/app.cpp
- synfig-studio/src/gui/app.h
- synfig-studio/src/gui/dialogs/dialog_setup.cpp
- synfig-studio/src/gui/dialogs/dialog_setup.h
Some other features could be done, for example:
- Own button for 'restore default shortcuts only' (instead of together with all other Synfig Studio settings)
- Save and load specific/custom accel map file (it always read/overwrite [config-folder]/accelrc)
- List all available actions (currently it lists only those with a default shortcut set in app.cpp)
- Group actions in a Tree view structure (but I'm lazy for that)
- List with better (simpler) names and maybe tooltips: right now it's the action full path. However, it would require a proper registration on every case, and this PR is just a quick implementation
- Warn user if a shortcut is used for another action
fix #422
> Basic implementation of Keyboard Shortcut Editor [studio]

- synfig-studio/src/gui/app.cpp
- synfig-studio/src/gui/canvasview.cpp
- synfig-studio/src/gui/trees/layertree.cpp
- synfig-studio/src/gui/widgets/widget_curves.cpp
- synfig-studio/src/gui/widgets/widget_timetrack.cpp
- Add Numpad Delete key to some widgets as an alternative to regular Delete key
- Remove Numpad Delete key from CanvasView accels, because deprecated Gtk::UIManager only allows one accel per action
- Restore old 'Stop' ('Pause' on GUI) : it was renamed by mistake and missed this action
> Fix some shortcuts/accels - for item deletion and animation stop

- synfig-studio/src/gui/app.cpp
- synfig-studio/src/gui/app.h
- synfig-studio/src/gui/dialogs/dialog_setup.cpp
- synfig-studio/src/gui/dialogs/dialog_setup.h
- It visually separates actions in sections (TreeView)
- Actions and sections sorted alphabetically
- It warns about user trying to bind an already-in-use shortcut
- It features a button to Restore Default Accels only (instead of resetting all Synfig Studio settings) and asks for user confirmation before restoration
> [Studio] Shortcut editor more organized and asks for user confirmation

- CMakeLists.txt
It should set `MINGW_PREFIX` to the default location `c:\msys64\mingw64\`
> Fixed incorrect behavior when passing '-DMSYS=1' to CMake [cmake]

- synfig-studio/src/gui/app.cpp
- synfig-studio/src/gui/docks/dock_canvases.cpp
* Removed explicit dock_toolbox->present()
If user explicitly undocks and closes this dock don't hesitate to keep
it hidden and let user load the dock manually from the menu bar instead
of forcing the dock as dialog
* Removed explicit present() in Dock_Canvases new_instance()
Explicitly calling present() was causing a bug where every new canvas
instance would force this dock (Canvases) to be shown as a dialog even 
though it was undocked and closed/hidden by the user.
Fixes #1803
> [Synfig Studio] Fixed closed docks bug

- synfig-studio/src/gui/resources/css/synfig.css
- synfig-studio/src/gui/states/state_bline.cpp
- synfig-studio/src/gui/states/state_bone.cpp
- synfig-studio/src/gui/states/state_circle.cpp
- synfig-studio/src/gui/states/state_draw.cpp
- synfig-studio/src/gui/states/state_gradient.cpp
- synfig-studio/src/gui/states/state_lasso.cpp
- synfig-studio/src/gui/states/state_polygon.cpp
- synfig-studio/src/gui/states/state_rectangle.cpp
- synfig-studio/src/gui/states/state_star.cpp
- synfig-studio/src/gui/states/state_text.cpp
@ice0 @Keyikedalube @rodolforg 
This PR is meant for removal of SPACES that are added with the help of  ``` alignment.h ``` .
> Replaced `Gtk::Alignment` spaces with CSS margins

- synfig-studio/src/synfigapp/actions/valuedesclink.cpp
- synfig-studio/src/synfigapp/actions/valuedesclink.h
- synfig-studio/src/synfigapp/value_desc.h
Remove useless variable member `ValueDesc::scalar`, some NULL/0 usages and old casts.
Basic explanation:
- `scalar`could have only two values: 0.0 (if invalid/useless) and 1.0 (if ValueDesc was a LinkableValueNode, the only situation when scalar had a meaning);
-  This variable was only used in action ValueDescLink, where it would be multiplied by `scalar` of another ValueDesc and checked if it would yell a negative value;
- In any case, the product of two ValueDesc::scalar could only give 0.0 or 1.0, so it would never be negative. The comparison is always false then;
- In a cascade effect, everything that depended on this comparison would never be affected and could be safely deleted.
> Clean synfigapp::ValueDesc a bit

- synfig-studio/src/gui/docks/dockbook.cpp
If a sub-canvas tab was middle clicked, hide that tab instead of force
closing the root canvas which has an unintended side effect of closing
all other exported sub-canvases.
Fixes #2203
> [Synfig Studio] Middle click on a tab now closes the root canvas only when all child canvases are closed

- synfig-studio/src/gui/trees/layertreestore.cpp
- synfig-studio/src/gui/trees/layertreestore.h
There was a mistake in 'queued' assignment in queue_rebuild().
Besides, internal class methods directly call rebuild() and it
could crash due to race condition.
> [Studio] Fixed crash in rare cases caused by race condition when rebuilding LayerTreeStore

- synfig-core/src/modules/mod_gif/trgt_gif.cpp
Test file:
[circle-move.zip](https://github.com/synfig/synfig/files/6408996/circle-move.zip)
Linked issues:
https://forums.synfig.org/t/unwanted-layer-duplicate-appearing-in-rendered-gif/11995
https://forums.synfig.org/t/noob-rendering-original-bitmap-image-remains-behind-animation-solved/11957
> [Core] Fixed incorrect background restoration on animated GIFs with transparent background

- synfig-studio/plugins/lottie-exporter/properties/shapePropKeyframe/advanced_outline.py
Fixes the issue reported here: https://forums.synfig.org/t/lottie-export-for-the-web-doesnt-work-with-advanced-outline/12173/15
> [Lottie exporter] Another fix for advanced outline

- synfig-studio/plugins/lottie-exporter/properties/shapePropKeyframe/outline.py
Fixes the issue reported here: https://forums.synfig.org/t/lottie-export-for-the-web-doesnt-work-with-advanced-outline/12173/19
> [Lottie exporter] Resolves 'nan' exception in line_intersection

- synfig-studio/src/gui/widgets/widget_waypoint.cpp
It only makes sense in this case.
Debug builds crash otherwise due to an assert in find_param_desc().
Reported by GregorysonofCarl here:
https://forums.synfig.org/t/crash-when-right-clicking-waypoints/12391/6
> [Studio] Fixed crash in debug builds when right-clicking on some waypoints

- synfig-studio/src/gui/canvasview.cpp
> [Synfig Studio] The end time in the render settings is now correctly updated when changed from the toolbar

- ETL/configure.ac
- synfig-core/configure.ac
- synfig-studio/configure.ac
- synfig-studio/org.synfig.SynfigStudio.appdata.xml.in
- synfig-studio/src/gui/CMakeLists.txt
I am starting preparations for 1.4.3 release!
* **Bump version to 1.4.3** - This is the first commit I have made, it is automatically created when I executed script `./version-bump.sh 1.4.3` from Synfig's source dir (according to instructions here - https://synfig-docs-dev.readthedocs.io/en/latest/common/release.html#update-version-number).
> [Release] Starting preparations for releasing v1.4.3

- synfig-studio/src/gui/canvasview.cpp
If you try to import a file into a not-yet-saved Synfig document,
it does nothing.
Mistake made by me in
commit 798bfbf95983ff6c01ca019ac72b390fbc259eab
> [Studio] Fixed issue with non-working import when importing to unsaved SIF file

- synfig-studio/src/synfigapp/canvasinterface.cpp
When importing a raster image without "Resize to Scale" set,
its size could be wrong, if the target canvas is not 60px/unit.
Reported-by: Arturo
https://forums.synfig.org/t/scaling-circle-with-outline/12425/4
> [Studio] fix image size when importing onto canvas with non-standard size

- ETL/configure.ac
- synfig-core/configure.ac
- synfig-studio/configure.ac
- synfig-studio/org.synfig.SynfigStudio.appdata.xml.in
I did that commit by executing the following command from source root dir  - `./version-bump.sh 1.6.0` (see https://synfig-docs-dev.readthedocs.io/en/latest/common/release.html#update-version-number)
> Bump version number for 1.6.0

- synfig-studio/src/gui/actionmanagers/layeractionmanager.cpp
- synfig-studio/src/synfigapp/actions/layerduplicate.cpp
This implements the behavior adopted for LayerDuplicate action
for Copy Layer too.
Based on PR #2050 (commit c526bf2186871d5b4133f3527b3da54390e44f78)
I changed some variable names for better reading and made them
consistent.
> [Studio] don't let inner layer be duplicated twice when copying

- .github/workflows/synfig-ci.yml
- .github/workflows/synfig-stable.yml
Version 16.04 is no longer available.
https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners
> Switched Ubuntu version on Github Workflows to 18.04

- synfig-core/src/modules/mod_geometry/advanced_outline.cpp
- synfig-core/src/synfig/valuenodes/valuenode_composite.cpp
Dash Item length and offset are measured as distances,
differently of Width Point position, that is relative to
Spline length.
The parameter hint "dash" was not used/parsed anywhere, so
I removed it.
> [core] Improve hints for Dash item parameters

- synfig-core/src/modules/mod_magickpp/Makefile.am
Fixes #2320.
This complements the change made in a583e73d4c47914284b15f4a8d7719eafddfe1b4
> Fix magick++ target missing in AppImage

- synfig-core/src/modules/mod_magickpp/Makefile.am
...because in 391f8a1540b4c9339bb1141f the @MAGICKPP_LIBS@ variable is placed in correct location now - at 'libmod_magickpp_la_LIBADD' list.
See here - 
https://github.com/synfig/synfig/blob/391f8a1540b4c9339bb1141f4067221f6cc87b8b/synfig-core/src/modules/mod_magickpp/Makefile.am#L36-L39
> Autotools: Remove @MAGICKPP_LIBS@ variable from LDFLAGS

- synfig-studio/src/gui/app.cpp
- synfig-studio/src/gui/canvasview.cpp
- synfig-studio/src/gui/dialogs/dialog_workspaces.cpp
- synfig-studio/src/gui/instance.cpp
When user presses Esc key or closes the dialog by clicking on
the X (close) button in window decoration, the dialog does not
return "RESPONSE_CANCEL", but "RESPONSE_DELETE_EVENT".
When programmatically closed, the dialog returns with
"RESPONSE_NONE".
In such cases, the dialog is supposed to be canceled, but
that was not correctly interpreted everywhere.
> [Studio] Fix dialog responses when user pressing Esc key

- ETL/ETL/_handle.h
- synfig-core/src/modules/lyr_std/perspective.cpp
- synfig-core/src/synfig/rendering/primitive/transformationaffine.h
Added explicit copy constructors to Transformations (fixes build errors)
> Made shared_objects non-copyable

- synfig-core/src/tool/optionsprocessor.cpp
- synfig-core/src/tool/optionsprocessor.h
- remove old commented-out code
- remove unneeded #include
- remove deprecated `throw` in method signature
> minor cleanup on SynfigCommandLineParser

- synfig-studio/src/synfigapp/action.h
don't require a `using namespace Action` in a file that use
such macros.
> add explicit namespace synfigapp for Action macros

- synfig-studio/src/synfigapp/canvasinterface.cpp
When "Fit to Canvas" wasn't set in Import Image dialog.
fix #2328
> Fix regression: importing image making it upside-down

- synfig-studio/src/gui/states/state_bone.cpp
If saved with pixel unit system, the value would be loaded wrong, as
if it was the Synfig unit system
> Bone Tool: fix default bone width preference loading

- synfig-studio/src/gui/timeplotdata.cpp
- synfig-studio/src/gui/timeplotdata.h
- synfig-studio/src/gui/widgets/widget_canvastimeslider.cpp
- synfig-studio/src/gui/widgets/widget_curves.cpp
- synfig-studio/src/gui/widgets/widget_timeslider.cpp
- synfig-studio/src/gui/widgets/widget_timeslider.h
- synfig-studio/src/gui/widgets/widget_timetrack.cpp
> Add margins to TimeTrack to ease handling of initial waypoint and keyframe

- synfig-core/src/synfig/string_helper.cpp
- synfig-studio/src/gui/app.cpp
- synfig-studio/src/gui/dialogs/dialog_setup.cpp
- synfig-studio/src/gui/dialogsettings.cpp
- synfig-studio/src/gui/dialogsettings.h
- synfig-studio/src/gui/docks/dockdialog.cpp
- synfig-studio/src/gui/docks/dockmanager.cpp
- synfig-studio/src/gui/mainwindow.cpp
- synfig-studio/src/gui/modules/mod_palette/dock_paledit.cpp
- synfig-studio/src/gui/states/state_bline.cpp
- synfig-studio/src/gui/states/state_bone.cpp
- synfig-studio/src/gui/states/state_brush.cpp
- synfig-studio/src/gui/states/state_circle.cpp
- synfig-studio/src/gui/states/state_draw.cpp
- synfig-studio/src/gui/states/state_gradient.cpp
- synfig-studio/src/gui/states/state_lasso.cpp
- synfig-studio/src/gui/states/state_polygon.cpp
- synfig-studio/src/gui/states/state_rectangle.cpp
- synfig-studio/src/gui/states/state_rotate.cpp
- synfig-studio/src/gui/states/state_scale.cpp
- synfig-studio/src/gui/states/state_smoothmove.cpp
- synfig-studio/src/gui/states/state_star.cpp
- synfig-studio/src/gui/states/state_text.cpp
- synfig-studio/src/gui/states/state_width.cpp
- synfig-studio/src/synfigapp/inputdevice.cpp
- synfig-studio/src/synfigapp/settings.cpp
- synfig-studio/src/synfigapp/settings.h
The problem was the LC_NUMERIC locale was changed for loading preferences and the value was set on widget before changing back to proper locale.
This PR reduces the duration of the temporary locale change.
> Fix Orientation parameter display on Text Tool Options Panel

- ChangeLog-development.md
- ChangeLog.md
- synfig-core/ChangeLog.old
- synfig-core/NEWS
- synfig-studio/ChangeLog.old
- synfig-studio/NEWS
- synfig-studio/images/CMakeLists.txt
Found via `codespell -q 3 -L aline,ang,ba,childs,dout,eiter,forse,objext,pevent,shouldbe,thru,uint,unselect,vertexes -S ./synfig-studio/po,./synfig-core/po,/synfig-core/m4,./synfig-osx/,./gtkmm-osx,./bugs,.*.eps,*.sif,./synfig-studio/plugins/lottie-exporter`
> Fix various typos

- synfig-core/src/modules/mod_svg/svg_parser.cpp
Compare it:
https://www.w3.org/TR/SVG/images/paths/arcs01.svg
Synfig from v1.2.1 to 1.4.2 do not render anything.
> Svg_parser: fix command 'a' for Path element: ellipse arcs work now

- synfig-core/src/modules/mod_svg/svg_parser.cpp
SVG 1.1: 11.3 Fill Properties
SVG 2: 13.4.1. Specifying fill paint: the ‘fill’ property
> Svg_parser: fix default fill color: black instead of none

- synfig-core/src/modules/mod_svg/svg_parser.cpp
- synfig-core/src/modules/mod_svg/svg_parser.h
instead of nodeStartBasicLayer()
> Svg_parser: better method name: initializeGroupLayerNode()

- synfig-core/src/modules/mod_svg/svg_parser.cpp
- synfig-core/src/modules/mod_svg/svg_parser.h
Now few essential elements are missing: <text>, <image>, <filter> and <use>.
> SVG importer: fix outlined rectangle and implement missing shapes

- synfig-studio/src/gui/app.cpp
- synfig-studio/src/gui/dialogs/dialog_workspaces.cpp
- synfig-studio/src/gui/docks/dock_curves.cpp
- synfig-studio/src/gui/docks/dock_curves.h
- synfig-studio/src/gui/docks/dock_soundwave.cpp
- synfig-studio/src/gui/docks/dock_timetrack2.cpp
- synfig-studio/src/gui/docks/dock_timetrack2.h
- synfig-studio/src/gui/states/state_bline.cpp
- synfig-studio/src/gui/widgets/widget_curves.cpp
- synfig-studio/src/gui/widgets/widget_curves.h
- synfig-studio/src/gui/widgets/widget_fontfamily.cpp
- synfig-studio/src/gui/widgets/widget_fontfamily.h
- synfig-studio/src/gui/widgets/widget_timetrack.cpp
- synfig-studio/src/gui/widgets/widget_timetrack.h
- synfig-studio/src/gui/workarea.cpp
Specially important for WorkArea queuing rendering.
Reasoning by Kjell Ahlstedt (gtkmm maintainer) follows below:
From the documentation of sigc::mem_fun():
```
* @note If the object type inherits from sigc::trackable, and the
* functor returned from mem_fun() is assigned to a sigc::slot, the functor
* will be automatically cleared when the object goes out of scope. Invoking
* that slot will then have no effect and will not try to use the destroyed
* instance.
```
In most examples in the gtkmm tutorial the signal handlers are members of widgets.
All widgets inherit from sigc::trackable. The automatic disconnection when a
widget is destroyed would be lost if a sigc::mem_fun() is replaced by a C++ lambda
expression. Unless it's combined with sigc::track_obj():
```c++ …
```
> Studio: avoid lambda functions for signal callbacks

- synfig-studio/src/gui/app.cpp
- synfig-studio/src/gui/dialogs/dialog_setup.cpp
- synfig-studio/src/gui/dialogs/dialog_setup.h
- synfig-studio/src/gui/instance.cpp
It is dangerous to keep Redo stack when user undoes some stuff and
performs a new action: not very action reacts well to changes of
previous status: some Actions are not stateless and stores some
info/values/pointers when their methods `set_param()` or `prepare()`
are called before perform.
App crash can happen!
So let's prevent this redo-stack-keeper by disabling it by default.
A new user preference is created (in System section) for those who
really want it enabled.
> Clear Redo History on new action by default; new user preference

- autobuild/build.sh
> Linux build: Autodetect number of threads for compilation

- synfig-studio/src/gui/cellrenderer/cellrenderer_timetrack.cpp
After PR #2384, you could click near the waypoint and drag it,
even though the mouse was not exactly over it.
> fix dragging area of a waypoint in CellRenderer_Timetrack

- synfig-studio/src/gui/states/state_bline.cpp
- synfig-studio/src/gui/states/state_bone.cpp
- synfig-studio/src/gui/states/state_circle.cpp
- synfig-studio/src/gui/states/state_draw.cpp
- synfig-studio/src/gui/states/state_lasso.cpp
- synfig-studio/src/gui/states/state_polygon.cpp
- synfig-studio/src/gui/states/state_rectangle.cpp
- synfig-studio/src/gui/states/state_star.cpp
- synfig-studio/src/gui/states/state_width.cpp
- synfig-studio/src/synfigapp/settings.cpp
- synfig-studio/src/synfigapp/settings.h
What of the two commits is best?
Many tools ignore the unit system a preference was saved - that may be different of current App preference when loaded...
So 1 pixel can become the gigantic 1u (60px).
Test it:
1. In `Preferences`, assure the Unit `System` is '`Pixels`'
2. Select `Bline Tool`
3. In `Tool Options Panel`, set `Brush Size` to `1.0 px`
4. Draw any Bline in Work Area
4. Change to `Normal Tool`
5. In `Preferences`, assure the Unit `System` is '`Units`'
6. (optional: close Synfig and reopen it)
6. Select `Bline Tool` again
7. Draw another Bline
8. It's way thicker than before. If you check `Tool Options Panel`, you'll see `Brush Size` as `1.0u`
Mentioned first here:
https://github.com/synfig/synfig/pull/2372#pullrequestreview-783987051
> Fix distance values on settings

- synfig-core/src/synfig/filesystemnative.h
- synfig-core/src/synfig/rendering/software/function/blur.cpp
- synfig-core/src/synfig/target_multi.cpp
- synfig-core/src/synfig/target_multi.h
- synfig-core/src/synfig/valuenodes/valuenode_radialcomposite.cpp
- synfig-studio/src/gui/actionmanagers/layeractionmanager.cpp
- synfig-studio/src/gui/dialogs/canvasoptions.h
- synfig-studio/src/gui/dialogs/dialog_workspaces.h
- synfig-studio/src/gui/widgets/widget_vector.cpp
- synfig-studio/src/gui/widgets/widget_vector.h
- synfig-studio/src/synfigapp/actions/layerduplicate.cpp
- warning: 'internal_read' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
- warning: variable 'mag' is uninitialized when passed as a const reference argument here [-Wuninitialized-const-reference]
- warning: loop variable 'layer' creates a copy from type 'const Layer::Handle' (aka 'const handle<synfig::Layer>') [-Wrange-loop-construct]
- warning: equality comparison with extraneous parentheses [-Wparentheses-equality]
- commented unused `blur_iir_coefficients.cpp`
> Fixed build warnings

- synfig-core/configure.ac
Version 2.2.6 was release in 2008!
https://savannah.gnu.org/forum/forum.php?forum_id=5439
> Autotools: remove code for very old libtool versions

- CMakeLists.txt
- synfig-studio/src/synfigapp/blineconvert.cpp
This issue is reproduced with Flatpak build and on Fedora.
The reason is that Fedora enables _GLIBCXX_ASSERTIONS  compile flag by default.
https://fedoraproject.org/wiki/Changes/HardeningFlags28
And Synfig crashes when reads off the end of the vector.
So I enabled this flag for CMake debug build too.
This will help us find such problems faster.
> Fixed crash when using Draw tool (Fedora/Flatpak)

- synfig-core/src/modules/lyr_freetype/lyr_freetype.cpp
- synfig-core/src/modules/lyr_freetype/lyr_freetype.h
From ice0 comment on PR #2424:
For example, currently we are using #include <harfbuzz/hb.h> instead of <hb.h>
but pkg-config returns `harfbuzz/include/harfbuzz`, not just `harfbuzz/include`.
This works fine on Linux because all system libraries is already included by compiler.
This need to be fixed. (TODO)
--
From ice0 comment on PR #2442:
Please remove prefix from `fribidi` too.
```
pkg-config --cflags fribidi
-I/usr/include/fribidi
```
>  Change #include to not... include... harfbuzz or fribidi folder

- synfig-studio/src/gui/app.cpp
- synfig-studio/src/gui/app.h
- synfig-studio/src/gui/canvasview.cpp
#2403
@ice0 This pull request allows users of the gui to select and import multiple files at once from the import dialog.  I overloaded the dialog_open_file with this:
`App::dialog_open_file(const std::string &title, std::vector<std::string> &filenames, std::string preference)`
which adds the the parameters that is a string vector.  This PR adds a lot of lines of code since I overloaded the original function.  I tried making it work a bool parameter, but to be honest I was a little confused how to make it work.  I know I can figure out how to make it work if need be to make maintaining code easier.
> Added ability to import multiple files

- synfig-studio/src/synfigapp/actions/valuedescset.cpp
Bone Tool: Correctly apply offset to Second bone when First bone of Skeleton Deformation Layer changed.
This issue is described in this comment - https://github.com/synfig/synfig/issues/1626#issuecomment-927001289
Closes #1626.
> Bone Tool: Correctly apply offset to Second bone when First bone changed

- .github/workflows/synfig-tests.yml
It is currently fails with an error:
```
E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/universe/f/flatpak/flatpak_1.0.9-0ubuntu0.3_amd64.deb  404  Not Found [IP: 52.147.219.192 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
```
> Fixed appdata.xml check CI

- synfig-studio/src/gui/cellrenderer/cellrenderer_value.cpp
- synfig-studio/src/gui/cellrenderer/cellrenderer_value.h
#2411
I added changes in ```cellrenderer_value.cpp```.  I added the ```on_key_press_event``` method to check for escape key and call ```on_editing_done()```. I also had to add the ```signal_key_press_event()``` for the value widget.
@ice0 @rodolforg Hey guys can you check out these changes? Thanks again for all the advice to get me started.
> Added ability for escape key to close  editing box in Value column in the Parameters panel

- synfig-core/src/modules/mod_ffmpeg/trgt_ffmpeg.cpp
Bug: When audio track is shorter than video track, the movie file lasts
only as long as audio track.
fix #2475
> Fix exported file with audio being smaller than it should

- synfig-core/src/modules/mod_svg/svg_parser.cpp
It happened when it coincides with first vertex - and it didn't
make sense not creating it. It isn't the same thing of closing
path, for example.
> Svg_parser: fix not creating last vertex of cubic path segment

- synfig-studio/src/synfigapp/actions/valuedescbonelink.cpp
Fix #2089
(Problems when linking Group to Bone - Origin Parameter is linked
instead of Transformation Parameter)
> BoneLink: Ask user if s/he wants to use transformation instead of origin

- synfig-core/src/synfig/loadcanvas.cpp
fix #2481 (Importing an .svg drawing corrupts the animation file)
> loadcanvas: fix loading of some non-value nodes lists

- .github/workflows/synfig-ci.yml
Currently build fails with error:
```
Error: Cache upload failed because file read failed with EBADF: bad file descriptor, read
at ReadStream.<anonymous> (/home/runner/work/_actions/actions/cache/v2.1.3/dist/save/index.js:3305:31)
at ReadStream.emit (events.js:210:5)
at internal/fs/streams.js:167:12
at FSReqCallback.wrapper [as oncomplete] (fs.js:470:5)
```
> Updated GitHub actions/cache version

- synfig-studio/src/gui/app.cpp
- synfig-studio/src/gui/canvasview.cpp
- synfig-studio/src/gui/instance.cpp
- synfig-studio/src/synfigapp/action_system.cpp
- synfig-studio/src/synfigapp/actions/valuedescbonelink.cpp
- synfig-studio/src/synfigapp/actions/valuedescset.cpp
Base class synfigapp::UIInterface has this method signature:
```
virtual Response confirmation(
const std::string &message,
const std::string &details,
const std::string &confirm,
const std::string &cancel,
Response dflt = RESPONSE_OK
) = 0;
```
Somehow the order of button label text parameters was changed for:
- `GlobalUIInterface` (app.cpp)
- `CanvasViewUIInterface` (canvasview.cpp)
And, for that reason, calls from `synfigapp::Action` may have wrong
default responses.
> make UIInterface::confirmation() implementation consistent to signature

- synfig-core/src/synfig/filesystemnative.cpp
The Windows network path looks like this: `\\NetworkPC\Share`.
`fix_slashes` changes it to `//NetworkPC/Share`, so it can't be
interpreted as a network share no more.
I removed the `fix_slashes` because glib/gio does all the translations itself.
Fix #2212
> Fixed issue with opening a file from a network folder on Windows

- synfig-studio/src/synfigapp/actions/valuedesccreatechildbone.cpp
Got a feedback from several Synfig users, who are on latest development snapshot of Synfig:
Many of them got stuck on tutorials because of missing "Create Child Bones" action.
The issue https://github.com/synfig/synfig/issues/1714 confirms that too.
So, it looks like I was wrong when [suggested to disable this](https://github.com/synfig/synfig/issues/1558). ^__^
Let's re-enable this and wait while most tutorials will be updated and people will get used to Skeleton Tool.
> Re-enable "Create Child Bone" action

- synfig-core/src/synfig/valuenodes/valuenode_bonelink.cpp
- synfig-studio/src/gui/states/state_bline.cpp
- synfig-studio/src/gui/states/state_circle.cpp
- synfig-studio/src/gui/states/state_polygon.cpp
- synfig-studio/src/gui/states/state_rectangle.cpp
- synfig-studio/src/gui/states/state_star.cpp
V656. Variables are initialized through the call to the same function.
It's probably an error or un-optimized code.
https://pvs-studio.com/en/docs/warnings/v656/
> Fixed PVS-Studio warning v656

- README.md
We have Installation instructions available separately in documentation now - https://synfig.readthedocs.io/en/latest/installation.html
> Update Installation section in Readme

- synfig-core/src/synfig/filecontainerzip.cpp
- synfig-core/src/synfig/filesystemtemporary.cpp
- synfig-core/src/synfig/loadcanvas.cpp
- synfig-core/src/synfig/zstreambuf.cpp
- synfig-core/src/synfig/zstreambuf.h
- synfig-studio/src/gui/instance.cpp
The problem was in `inflateInit2` incorrect initialization.
In this case we have no file header, quote from documentation:
> windowBits can also be –8..–15 for raw inflate. In this case, -windowBits
determines the window size. inflate() will then process raw deflate data,
not looking for a zlib or gzip header, not generating a check value, and
not looking for any check values for comparison at the end of the
stream. This is for use with other formats that use the deflate
compressed data format such as zip.
Anyway this change should be tested before the merge.
> Quick fix for zstreambuf

- synfig-studio/src/synfigapp/main.cpp
Fix #2536
P.S. 
For some reason `synfigapp::Main::~Main()` destructor is not called on Linux
> Fixed Synfig Studio crash on exit (MacOS)

- ETL/test/angle.cpp
Part of solution for https://bugs.debian.org/984053
> ETL test: avoid clash between ETL::hermite and std::hermite

- synfig-studio/src/gui/app.cpp
- synfig-studio/src/gui/canvasview.cpp
- synfig-studio/src/gui/instance.cpp
- synfig-studio/src/synfigapp/uimanager.cpp
- synfig-studio/src/synfigapp/uimanager.h
fix #2208
@rodolforg Hi Rodolfo, is this the change you are looking for?
This only creates "destructive-action" ```cancel``` button when the user tries to exit without saving.
> Add Color "destructive-action" and "suggested-action" to dialog when trying to quit before saving changes

- 1-setup-windows-msys2.sh
MSYS2 moved `libtoolize` to the new `libtool` package and renamed `mingw-w64-x86_64-libtool` to `mingw-w64-x86_64-libltdl`
This should fix the error: `*** No libtoolize nor glibtoolize found, please install the intltool package ***"` when building with autotools on MSYS2 (using `./2-build-debug.sh` script).
> [MSYS2] Updated packages list

- synfig-core/src/synfig/rendering/software/function/blur.cpp
Fixes #2544. `src_offset` is initially set as 
https://github.com/synfig/synfig/blob/17a48a42d5263012c7019749dc40ccf72d9050b5/synfig-core/src/synfig/rendering/software/task/taskblursw.cpp#L79-L80
However,  `Params::validate` expands as the target rect so as to account for the blurring, and hence the offset needs to be reevaluated.
But I'm actually confused here.
As far as I understand, each task has a surface, and a target rectangle that it should update. Tasks can have subtasks, which have their own surfaces, and rectangle which needs to be updated, and then these updates are merged to the parent surface.
In this particular case the blur task blurs the region in its subtask, and writes it to the surface on the parent task. What confuses me is this part …
> Fixed bug with src offset in blur sw task

- autobuild/synfigrenderer-regression-test.sh
We do not use Travis anymore, so let's allow to call regression test script without TRAVIS_BUILD_DIR variable.
This is useful for running tests locally.
Also, I have added condition to avoid re-downloading whole tests repository every time.
> Allow to call regression test script outside of Travis

- 2-build-msys-cmake.sh
this way 
./2-build-msys-cmake.sh    
runs release build which is the default because as @ice0  mentioned "Currently we use Release build on the Windows as default just because of long linking time for Debug build"
and 
./2-build-msys-cmake.sh debug
runs debug build
> Added the ability to set the build type from the command line to the 2-build-msys-cmake.sh script

- synfig-core/test/bline.cpp
- synfig-core/test/node.cpp
- synfig-core/test/test_base.h
Although the programming interface didn't change,
test functions are not required to return a bool value anymore
> improve output readability of unit tests with test_base.h

- .github/workflows/synfig-ci.yml
- .github/workflows/synfig-stable.yml
Version 16.04 is no longer available.
https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners
> Switched Ubuntu version on Github Workflows to 18.04 (#2322)

- synfig-osx/launcher/.cvsignore
- synfig-osx/launcher/English.lproj/.cvsignore
- synfig-osx/launcher/Synfig Studio.pbproj/.cvsignore
- synfig-osx/launcher/utils/.cvsignore
They were used on CVS only, not git
> remove old .cvsignore files

- synfig-studio/plugins/lottie-exporter/lottie-exporter.py
This fix is required after upgrade of Python version in Windows build of Synfig - https://github.com/morevnaproject/morevna-builds/pull/67
I have updated to Python version 3.8.10 ("embed" build), and after that  Lottie Exporter throws an error that it unable to find "canvas" module. The "canvas.py" file is in the same directory as main plugin file and Python should find it. But probably the "embed" version of Python have different behavior. So, I have added plugin dir to python's module search path.
Other Synfig's default plugins are okay (they do not import custom modules).
> Fix module search path for Lottie Exporter

- CMakeLists.txt
- synfig-core/src/tool/CMakeLists.txt
- synfig-studio/src/gui/CMakeLists.txt
Added option to link with tcmalloc library.
This should help debug memory leaks.
Usage:
1. install google-perf-tools package
```
sudo apt-get install google-perftools
```
2. Enable linking with tcmalloc library:
```
cmake -DENABLE_TCMALLOC=ON ...
```
This option just adds `-ltcmalloc` to `synfig` and `synfigstudio` binaries.
3. Build binaries and enable heap profiling:
```
env HEAPPROFILE=synfig ./synfig ...
```
This should create `synfig.00xx.heap` files in current folder while running.
More details about tcmalloc options here:
https://gperftools.github.io/gperftools/heapprofile.html
4. Install visualizer dependencies (gv, graphviz):
```
sudo apt install graphviz gv
```
5. Comparing profiles:
```
google-pprof --gv --base=synfig.0002.heap ./synfigstudio synfig.0004.heap
```
This will show …
> [CMake] Added option to link with tcmalloc library

- synfig-studio/src/synfigapp/value_desc.cpp
- synfig-studio/src/synfigapp/value_desc.h
Fixes #1701,  As far as I understand, the problem is that when the last waypoint is removed, the node representing the exported value is replaced, as in here
https://github.com/synfig/synfig/blob/f64f99f020f0689fb006969a7c649c101c52d066/synfig-studio/src/synfigapp/actions/waypointremove.cpp#L137-L163
The old `ValueNode` is removed from the canvas, and hence invalidating all the `ValueDesc`s that point to it. A signal is emitted of the change, for which the different tree stores handle. Many of the tree stores don't handle the event instantly, but instead wait for a period of time, then handles it as in here
https://github.com/synfig/synfig/blob/f64f99f020f0689fb006969a7c649c101c52d066/synfig-studio/src/gui/trees/childrentreestore.cpp#L299-L309 
The problem happens when the invalidated …
> Fix crash when deleting last waypoint

- synfig-core/src/modules/mod_ffmpeg/trgt_ffmpeg.cpp
Time format has been changed to the correct one.
Fix #2608
> Fixed video render with FFmpeg version 3

- synfig-core/src/modules/lyr_freetype/lyr_freetype.cpp
rename `preffix` pointer to `prefix`
> Fix typo in source

- synfig-studio/src/gui/app.cpp
SYNFIG_GTK_THEME=Adwaita /path/to/synfigstudio
> Returned back the ability to set a GTK theme using an environment variable

- synfig-studio/src/gui/app.cpp
- synfig-studio/src/gui/app.h
Original issue: https://github.com/synfig/synfig/issues/2596
The problem was the different approach to path handling between
`popen` and `Glib::spawn`.
`popen` requires the binary path to be quoted, while `Glib::spawn`
requires the path to be unquoted (it just fails with an error if the
path contains quotes).
As a result, quoted paths were handled correctly when detecting
the Python version, but didn't work when running plugins, and
vice versa.
Fixed by changing `popen` to `Glib::spawn` so paths are handled
uniformly now.
This should also fix non-working plugins in MSVC builds.
> Fixed an issue with plugins not working when path to Python contains spaces (Windows)

- synfig-studio/src/gui/_smach.h
- synfig-studio/src/gui/states/state_normal.cpp
- synfig-studio/src/gui/workarea.cpp
RESULT_ACCEPT: Current Tool/state processed and consumed the event
RESULT_REJECT: Current Tool/state processed and/or forbid the event
RESULT_ERROR: Current Tool/state processed and found an error
RESULT_OK: Current Tool/state processed or not, but let the event be
processed (too) by others in the event pipeline (WorkArea, Gtk App, etc)
> fix behavior after Tool process a key event: only proceeds when RESULT_OK

- synfig-studio/src/gui/widgets/widget_curves.cpp
Fix #2648
P.S. I didn't check the code, just guess.
> Fixed incorrect lines offset in Graphs Panel

- synfig-studio/src/gui/app.cpp
Fix #2041 
Alt + O and Alt + C to apply and cancel changes
> Added a mnemonic for the Text layer input dialog.

- synfig-studio/src/gui/dials/framedial.cpp
- synfig-studio/src/gui/dials/framedial.h
> Replaced deprecated Gtk::StockId in FrameDial icons

- synfig-studio/src/gui/dials/toggleducksdial.cpp
- synfig-studio/src/gui/dials/toggleducksdial.h
> Replaced deprecated Gtk::StockId in DuckDial icons

- synfig-studio/src/gui/canvasview.cpp
- synfig-studio/src/gui/canvasview.h
- synfig-studio/src/gui/dials/keyframedial.cpp
- synfig-studio/src/gui/dials/keyframedial.h
Before:
After:
Also made a small refactoring of the KeyFrameDial class.
P.S. Switched from `Gtk::Grid` to `Gtk::Box` due to unknown button size change.
The problem is described here: https://discourse.gnome.org/t/gtk-button-size-inside-gtk-grid-container/10015
> Replaced deprecated Gtk::StockID in KeyFrameDial

- synfig-studio/src/gui/docks/dockable.cpp
- synfig-studio/src/gui/docks/dockable.h
- synfig-studio/src/gui/states/state_bline.cpp
- synfig-studio/src/gui/states/state_bone.cpp
- synfig-studio/src/gui/states/state_draw.cpp
- synfig-studio/src/gui/states/state_polygon.cpp
- synfig-studio/src/gui/states/state_sketch.cpp
Sketch, Polygon, Spline and Bone tools visually not changed, because Gtk stocks are drawn correctly.
Draw before:
Draw after:
> Replaced deprecated Gtk::StockID in Dockables

- synfig-studio/src/gui/preview.cpp
- synfig-studio/src/gui/preview.h
Before:
After:
P.S. Jack icon will be fixed later.
> Replaced deprecated Gtk::StockID in Preview window

- synfig-studio/src/gui/states/state_bone.cpp
A single Active Bone is an information stored in WorkArea.
If it suddenly disappears (example: user delete the layer that contains
the active bone), WorkArea is not informed, so it contains invalid data.
Fix #2660
> fix(bone-tool): new bone position when active bone is invalid

- CMakeLists.txt
- ETL/test/CMakeLists.txt
- synfig-core/src/CMakeLists.txt
- synfig-core/src/modules/CMakeLists.txt
- synfig-core/src/modules/lyr_freetype/CMakeLists.txt
- synfig-core/src/modules/lyr_std/CMakeLists.txt
- synfig-core/src/modules/mod_jpeg/CMakeLists.txt
- synfig-core/src/modules/mod_mng/CMakeLists.txt
- synfig-core/src/modules/mod_openexr/CMakeLists.txt
- synfig-core/src/modules/mod_png/CMakeLists.txt
- synfig-core/src/modules/mod_svg/CMakeLists.txt
- synfig-core/src/synfig/CMakeLists.txt
- synfig-studio/src/CMakeLists.txt
- synfig-studio/src/gui/CMakeLists.txt
The combination of `<TARGET>_LIBRARIES` and `<TARGET>_LDFLAGS` doesn't work with msvc since cmake doesn't modify all the flags to be msvc-style. `<TARGET>_LINK_LIBRARIES` would work, but it was first documented in cmake 3.12.
The alternative is PkgConfig targets, which was introduced in cmake 3.6, and it is actually more modern-cmake like.
> build: Use CMake's PkgConfig imported targets

- synfig-studio/src/gui/actionmanagers/layeractionmanager.cpp
- synfig-studio/src/gui/canvasview.cpp
- synfig-studio/src/gui/states/state_bone.cpp
- synfig-studio/src/gui/states/state_brush.cpp
- synfig-studio/src/synfigapp/actions/layerduplicate.cpp
- warning: unused variable `pastecanvas` [-Wunused-variable]
- warning: suggest parentheses around assignment used as
truth value [-Wparentheses]
- warning: comparison of integer expressions of different
signedness: `int` and `std::vector<synfig::Bone>::size_type`
{aka `long unsigned int`} [-Wsign-compare]
- warning: suggest parentheses around arithmetic
in operand of `|` [-Wparentheses]
> fix: Fixed build warnings (GCC 9.4.0)

- synfig-studio/src/gui/trees/layertree.cpp
- synfig-studio/src/gui/trees/layertreestore.cpp
- synfig-studio/src/gui/trees/layertreestore.h
> refactor: Replaced deprecated Gtk::StockID in Layers panel

- synfig-studio/src/gui/canvasview.cpp
- synfig-studio/src/gui/canvasview.h
- synfig-studio/src/gui/dialogs/dialog_preview.h
- synfig-studio/src/gui/dials/jackdial.cpp
- synfig-studio/src/gui/dials/jackdial.h
- synfig-studio/src/gui/preview.cpp
- synfig-studio/src/gui/preview.h
Before (main window):
After (main window):
Before (Preview window):
After (Preview window):
> refactor: Replaced deprecated Gtk::StockID in Jack widget

- synfig-studio/src/gui/iconcontroller.cpp
- synfig-studio/src/gui/iconcontroller.h
- synfig-studio/src/gui/trees/canvastreestore.cpp
- synfig-studio/src/gui/trees/canvastreestore.h
- synfig-studio/src/gui/trees/childrentree.cpp
- synfig-studio/src/gui/trees/childrentreestore.cpp
- synfig-studio/src/gui/trees/layertree.cpp
**Link icon:**
Right click on parameter -> Export Value to project library
**Interpolation icon:** 
Right click on parameter -> Interpolation -> TCB
**Static icon:** 
Right click on parameter -> Forbid Animation
Before:
After:
> refactor: Replaced deprecated Gtk::StockID in Parameters panel

- synfig-core/src/synfig/main.cpp
- synfig-core/src/tool/optionsprocessor.cpp
- synfig-studio/src/gui/dialogs/about.cpp
Reasoning is stated here: https://reproducible-builds.org/.
UPD:
Build can be reproduced by setting environment variable `SOURCE_DATE_EPOCH`
> feat: Reproducible build

- synfig-studio/src/gui/widgets/widget_filename.cpp
- synfig-studio/src/gui/widgets/widget_filename.h
> refactor: Replaced deprecated Gtk::StockID in Filename widget

- synfig-studio/src/gui/widgets/widget_enum.cpp
- synfig-studio/src/gui/widgets/widget_enum.h
- synfig-studio/src/gui/widgets/widget_interpolation.cpp
- synfig-studio/src/gui/widgets/widget_interpolation.h
> refactor: Replaced deprecated Gtk::StockID in Widget Interpolation

- synfig-studio/src/gui/renddesc.cpp
- synfig-studio/src/gui/renddesc.h
- synfig-studio/src/gui/widgets/widget_link.cpp
- synfig-studio/src/gui/widgets/widget_link.h
> refactor: Replaced deprecated Gtk::StockID in WidgetLink

- synfig-core/src/synfig/valuenode.cpp
If an exported value node is selected in Library Panel and user right-
clicks on a sub-sub-parameter of a LinkableValueNode, Synfig Studio
hangs while checking if the selected (nested) parameter is descendant
of the selected exported value node.
fix #2688
> fix: Synfig hanging after right-click on sub-sub-parameter

- ETL/ETL/_angle.h
- ETL/ETL/_bezier.h
- ETL/ETL/_calculus.h
- ETL/ETL/_curve_func.h
- ETL/ETL/_hermite.h
- synfig-core/src/synfig/real.h
- synfig-core/src/synfig/valuenodes/valuenode_animatedinterface.cpp
- synfig-core/src/synfig/vector.h
`std::unary_function` and `std::binary_function` just need to define 3 types:
`unary_function` provides only two types - `argument_type` and `result_type` -
defined by the template parameters.
(https://en.cppreference.com/w/cpp/utility/functional/unary_function).
`binary_function` provides only three types - `first_argument_type`,
`second_argument_type` and `result_type` - defined by the template parameters.
(https://en.cppreference.com/w/cpp/utility/functional/binary_function)
Based on this code:
```
class bezier_base<synfig::Vector,float> : public std::unary_function<float,synfig::Vector>
{
public:
typedef synfig::Vector value_type;
typedef float time_type;
```
we can assume what:
```
using argument_type = time_type;
using result_type = value_type;
```
So I just replaced `argument_type` …
> refactor: removed deprecated std::unary_function and std::binary_function classes

- synfig-core/src/synfig/valuenode.cpp
- synfig-core/src/synfig/valuenode.h
- synfig-studio/src/synfigapp/actions/valuedescconnect.cpp
(fix some indentation too)
BREAKING CHANGE: Synfig API change: method renamed for better understanding
> refactor(core)!: rename ValueNode::is_descendant() to is_ancestor_of()

- ETL/test/hermite.cpp
they are actually duplicated in test/benchmark
> test(etl): remove unused methods for etl::hermite

- ETL/ETL/_stringf.h
- ETL/ETL/etl_config.h
- synfig-studio/src/gui/mainwindow.cpp
> refactor: remove `ETL_DIRECTORY_SEPARATORS`; use them directly

- synfig-core/src/synfig/debug/log.cpp
- synfig-core/src/synfig/filesystem.cpp
- synfig-core/src/synfig/filesystem.h
- synfig-core/src/synfig/filesystemnative.h
- synfig-core/src/synfig/main.cpp
- synfig-studio/src/gui/app.cpp
- synfig-studio/src/gui/duckmatic.cpp
- synfig-studio/src/gui/workspacehandler.cpp
- synfig-studio/src/synfigapp/main.cpp
- synfig-studio/src/synfigapp/settings.cpp
Finally, I found a proper solution for the problem with file paths
containing non-Latin characters in Windows.
The main problem was that we are working with UTF-8, while on Windows
filenames use UTF-16. To work with files, we use the Glibmm wrapper,
which performs correct path conversion, but in some cases we need
standard cpp `std::fstream` objects.
Unfortunately, the standard implementation does not support `std::wstring`
paths. C++17 introduced support through the use of `std::filesystem::path`,
but since we continue to support c++11, this option is not suitable for us.
Luckily, both MSVC and MinGW support a non-standard constructor overload
using wchar_t, and on Windows we can use it. All that is required is to convert
the path to UTF-16 for Windows and leave it as is for other …
> fix: Synfig does not start if the OS username contains non-Latin characters (Windows)

- synfig-studio/src/gui/canvasview.cpp
- synfig-studio/src/gui/canvasview.h
- synfig-studio/src/gui/dials/resolutiondial.cpp
- synfig-studio/src/gui/dials/resolutiondial.h
> refactor: Replaced deprecated Gtk::StockID in ResolutionDial

- synfig-studio/src/gui/cellrenderer/cellrenderer_timetrack.cpp
- synfig-studio/src/gui/widgets/widget_timetrack.cpp
- synfig-studio/src/gui/widgets/widget_timetrack.h
CellRenderer_TimeTrack (left) shows time marks for ValueNode_AnimatedFile, but Widget_TimeTrack (right) didn't:
What do you prefer? Green line or grayish circle?
And now we show the Dynamic List entry status (on/off) as CellRenderer_TimeTrack does (green/red vertical lines):
Traditional TimeTrack also hatches the time span where a Dynamic List entry is kept off. Widget_TimeTrack don't.
I don't like how it currently does. Any suggestion?
> fix: Added missing timetrack marks (animated_file timepoints and active points on/off)

- synfig-core/src/modules/mod_geometry/checkerboard.cpp
- synfig-core/src/modules/mod_yuv420p/trgt_yuv.cpp
- synfig-core/src/synfig/color/colorblendingfunctions.h
- synfig-core/src/synfig/distance.cpp
- synfig-core/src/synfig/gradient.cpp
- synfig-core/src/synfig/layers/layer_bitmap.cpp
- synfig-core/src/synfig/rendering/software/function/blur.cpp
- synfig-core/src/synfig/rendering/software/function/resample.cpp
- synfig-core/src/synfig/rendering/software/task/taskblendsw.cpp
- synfig-core/src/synfig/rendering/software/task/taskpixelgammasw.cpp
- synfig-core/src/synfig/threadpool.cpp
- synfig-core/src/synfig/valuenodes/valuenode_bline.cpp
- synfig-core/src/synfig/valuenodes/valuenode_blinecalctangent.cpp
- synfig-core/src/synfig/valuenodes/valuenode_blinecalcvertex.cpp
- synfig-core/src/synfig/valuenodes/valuenode_blinecalcwidth.cpp
- synfig-core/src/synfig/valuenodes/valuenode_modulo.cpp
- synfig-core/src/synfig/valuenodes/valuenode_range.cpp
- synfig-core/src/synfig/valuenodes/valuenode_repeat_gradient.cpp
- synfig-core/src/synfig/valuenodes/valuenode_stripes.cpp
- synfig-studio/src/gui/canvasview.cpp
- synfig-studio/src/gui/cellrenderer/cellrenderer_timetrack.cpp
- synfig-studio/src/gui/helpers.h
- synfig-studio/src/gui/preview.cpp
- synfig-studio/src/gui/timemodel.cpp
- synfig-studio/src/gui/widgets/widget_keyframe_list.cpp
- synfig-studio/src/gui/workarea.cpp
It's more readable this way.
In C++17, we can replace it with `std::clamp()`.
> refactor: make use of synfig::clamp instead of std::max(std::min())

- ETL/ETL/CMakeLists.txt
- ETL/ETL/Makefile.am
- ETL/test/CMakeLists.txt
- ETL/test/Makefile.am
- synfig-core/src/synfig/Makefile.am
- synfig-core/src/synfig/clock.h
- synfig-core/src/synfig/target_tile.cpp
- synfig-core/test/Makefile.am
- synfig-core/test/benchmark.cpp
- synfig-core/test/clock.cpp
- synfig-studio/src/gui/asyncrenderer.cpp
- synfig-studio/src/gui/canvasview.h
- synfig-studio/src/gui/preview.h
- synfig-studio/src/gui/states/state_width.cpp
- synfig-studio/src/gui/trees/childrentreestore.cpp
Moved ETL benchmark test to synfig-core due to `clock` requirement
BREAKING CHANGE: both ETL and synfig API changed:
- `etl::clock` is now `synfig::clock`
> refactor!: rename etl::clock to synfig::clock

- synfig-core/src/modules/lyr_freetype/lyr_freetype.cpp
- synfig-core/src/modules/lyr_std/import.cpp
- synfig-core/src/modules/mod_svg/layer_svg.cpp
- synfig-core/src/synfig/filesystem.cpp
- synfig-core/src/synfig/layer.cpp
- synfig-core/src/synfig/layers/layer_sound.cpp
Maybe we should fix them on canvas loading.
Probably it would be good to uniform them on saving too as well
on choosing via Widget_Filename too.
Fix #2723
> fix: layers parameter 'filename' does not accept backslash as directory separator

- synfig-core/src/modules/lyr_freetype/lyr_freetype.cpp
- synfig-core/src/modules/lyr_freetype/lyr_freetype.h
if font is relative filepath, force sync when canvas changes
Fix #2724
> fix(FreeType): Duplicating Text Layer resets Font Family parameter

- synfig-core/src/synfig/filesystemnative.cpp
- synfig-core/src/synfig/filesystemnative.h
The issue was that the `unget()` method calls the `pbackfail()`
method, which is not implemented, because of this the error
flag is set and the program goes into an infinite loop.
Fix #2720
> fix: Synfig hangs when importing palette

- synfig-core/src/modules/mod_libavcodec/trgt_av.cpp
fix #2709
[0001-fix-mod_libavcodec-fixed-build-with-FFMPEG-5.0.patch.zip](https://github.com/synfig/synfig/files/9058055/0001-fix-mod_libavcodec-fixed-build-with-FFMPEG-5.0.patch.zip)
> fix(mod_libavcodec): fixed build with FFMPEG 5.0

- synfig-core/src/modules/mod_libavcodec/trgt_av.cpp
```
error: invalid conversion from 'const AVOutputFormat*' to 'AVOutputFormat*' [-fpermissive]
259 |                 context->oformat = format;
```
`context->oformat` is `AVOutputFormat*` before FFMPEG 5.0. It builds fine with gcc on Linux, so I missed that.
> fix: mod_libavcodec didn't compile with MinGW

- synfig-studio/src/gui/trees/layergrouptree.cpp
- synfig-studio/src/gui/trees/layergrouptreestore.cpp
- synfig-studio/src/gui/trees/layergrouptreestore.h
Before:
After:
@rodolforg @morevnaproject 
P.S. Maybe rename `LayerGroupTree` to `LayerSetsTree`?
> refactor: Replaced deprecated Gtk::StockID in Sets panel

- synfig-studio/src/gui/app.cpp
- synfig-studio/src/gui/pluginmanager.cpp
It shows an error on start:
```
synfig(23672) [10:56:14] info: Init UI Manager...
synfig(23672) [10:56:14] error: building menus and toolbars failed: Error on line 1 char 10067: Document ended unexpectedly with elements still open в?" в??toolbarв?? was the last element opened
```
After adding the output with invalid XML, we can see where the problem
is:
```
<menuitem action='C:/msys64/...<Non-Latin path>...\plugins\add-skeleton-simple/plugin.xml'/>
```
The most interesting thing here is the slashes. According to the Gtk
documentation (https://docs.gtk.org/gtk3/class.UIManager.html):
> The name and action attributes must not contain “/” characters after
> parsing (since that would mess up path lookup) and must be usable
> as XML attributes when enclosed in doublequotes, thus they must
> …
> fix: Missing menu in Synfig when path to plugins contains non-Latin symbols (Windows)

- synfig-core/test/test_base.h
- synfig-studio/test/test_base.h
fix for some compilers not accepting ASSERT_EQUAL(nullptr, something)
> test: define ‘operator<<’ for operands std::string and std::nullptr_t

- synfig-core/src/synfig/layers/layer_sound.cpp
> fix: setting filename parameter of Layer Sound corrupts file

- synfig-core/src/modules/lyr_std/xorpattern.cpp
- synfig-core/src/modules/mod_example/metaballs.cpp
- synfig-core/src/modules/mod_geometry/checkerboard.cpp
- synfig-core/src/synfig/layers/layer_bitmap.cpp
- synfig-core/src/synfig/layers/layer_composite.cpp
- synfig-core/src/synfig/layers/layer_composite.h
- synfig-core/src/synfig/layers/layer_shape.cpp
- synfig-core/src/synfig/layers/layer_solidcolor.cpp
Example:
Layer_Bitmap and Layer_SolidColor ignored BLEND_BEHIND completely.
Gradient layers need some investigation
(Conical, Curve, Linear, Radial, Spiral, Noise).
They behave differently, also checking the alpha channel for some blend
methods.
BREAKING CHANGE: synfig API changed:
- add `Layer_Composite::basic_hit_check()` as a helper
> fix!: for some layers hit_check() missed some blend method influence

- .github/workflows/synfig-ci.yml
- .github/workflows/synfig-stable.yml
The macOS 10.15 Actions runner image is being deprecated
https://github.blog/changelog/2022-07-20-github-actions-the-macos-10-15-actions-runner-image-is-being-deprecated-and-will-be-removed-by-8-30-22/
> ci: bump macOS version

- synfig-studio/src/gui/app.cpp
- synfig-studio/src/gui/app.h
Steps to reproduce the problem:
1. Select Bline Tool
2. Change a parameter in Tool Options Panel (e.g. Opacity or Line Width)
3. Restart Synfig Studio
4. Select Bline Tool and see the change was not saved.
Reason:
Since #2497, we finally use Gtk::Application as base class for `App`.
`App` is destructed before `MainWindow` is closed (basically at start).
So, stuff done on quitting before merging #2497 was not done on the right time now.
As `signal-shutdown` is only called in primary instance of Gtk::Application,
it's the proper moment to delete and finish stuff on application exit.
> fix: synfig studio was not saving synfigapp settings on quit

- synfig-core/test/CMakeLists.txt
- synfig-core/test/node.cpp
To enable our tests in the CI framework (PR #2740), we'll temporarily
avoid the test deleting_node_removes_it_as_parent_from_its_children().
I don't know if it is really needed: the problem seems to exist since
ever. Maybe it makes Synfig Studio crashes, maybe not.
More investigation is needed.
I did make a quick fix for it (storing sigc::connection), but I don't
know if it would help or not or even cause more problems.
> test: Disabled failing test of `synfig::Node` class for now

- ETL/ETL/_stringf.h
`is_absolute_path` returns false with directories like `E:`. The following test will fail for example:
```
std::string file = "E:/file.sifz";
std::string file_dir = dirname(file_dir) // file_dir = E:
assert(is_absolute_path(file_dir) == true);
```
I encountered this on Windows where I save a sifz file as `E:/Synfig Animation 1.sifz`, which will cause synfig to record the most recent directory to `E:` in `settings-1.4` file as
```
pref.animation_dir=E:
```
Now if I try to open a file I get an error:
> fix: fixed a bug when saving a file to a Windows drive root path and then reusing the file dialog

- synfig-studio/src/synfigapp/actions/layerduplicate.cpp
Reverts synfig/synfig#2504
It breaks the bone duplication. It was detectable via automatic tests. Sorry for the wrong approval.
> revert: eliminate the need to set_time() on the search for bones

- ETL/ETL/_stringf.h
- ETL/test/stringf.cpp
- synfig-core/src/synfig/canvas.cpp
This method only changed backslashes to regular slashes
BREAKING CHANGE: ETL API changed:
- removed etl::unix_to_local();
use synfig::FileSystem::fix_slashes() instead
> refactor!: remove etl::unix_to_local()

- synfig-studio/src/gui/widgets/widget_coloredit.cpp
The alpha channel was reset because it was not saved.
> fix: Alpha channel resets when changing color in HSV wheel

- synfig-core/src/modules/mod_ffmpeg/trgt_ffmpeg.cpp
less (direct) external dependency
> refactor: prefer FileSystemNative rather GLib

- synfig-studio/src/gui/canvasview.cpp
- synfig-studio/src/gui/resources/css/synfig.css
- synfig-studio/src/gui/workarea.cpp
The canvas area is actually a Gtk::DrawingArea, and its default background
color is white (on light themes).
However, at start, it's not properly draw, and only the central area is
drawn by Synfig software (via workarea renderers). When Work Area itself
gains focus, it shows its white background defined by Gtk theme.
Fix #2636
> fix: Interface background became white after clicking OK in Preferences dialog

- ChangeLog-generate.sh
ChangeLog generator now parses merge commits only (the ones with #NUMBER strings in commit message).
> ci: Updated ChangeLog generator script

- .github/workflows/synfig-ci.yml
> ci: disabled `mod_magickpp` in macOS builds

- synfig-studio/src/gui/canvasview.cpp
The issue was introduced by this commit (87cc5d2)
When the list of selected layers was empty, then
clicking on the layer opened an empty menu.
Now the logic has changed:
If the layer is in the list of selected layers, then
actions are applied to them, if not, then the selection
is removed from them and the layer that was clicked
becomes selected (and actions applied to it).
fix #2779
> fix: Right-clicking a layer on a just opened file shows empty menu

- synfig-core/src/modules/mod_imagemagick/mptr_imagemagick.cpp
- synfig-core/src/synfig/filesystemtemporary.cpp
- synfig-core/src/synfig/filesystemtemporary.h
it uses application name "convert" to convert the desired image
into another temporary one with a well-known format (PNG).
This temporary image would then be really imported
(via another module - not very clever; what if it is not loaded?)
The problem is the temporary file is automatically named without any
extension.
In the end, Synfig can't load it, as it depends on the extension to select
the Importer.
Tested with a XPM file because XPM seems to be only loaded by imagemagick
https://filesamples.com/formats/xpm
BREAKING CHANGE: Synfig library API changed:
- Two methods of FileSystemTemporary has a new optional parameter: extension:
- generate_system_temporary_filename
- generate_system_temporary_filename_base
> fix!: mod_imagemagick didn't import anything

- synfig-core/po/POTFILES.in
they were removed in c67b5d3f34eb8413dc9d2fcb0f657a2f743174a0
(PR #2775)
> build: remove nonexistent files listed in synfig-core/po/POTFILES.in

- ETL/ChangeLog.old
- ETL/NEWS
- perf/scripts/view_comparison_graph.py
- synfig-core/src/modules/mod_svg/svg_parser.cpp
- synfig-core/src/modules/mod_svg/svg_parser.h
- synfig-core/src/synfig/node.h
- synfig-core/src/synfig/valuenodes/valuenode_derivative.h
- synfig-osx/launcher/utils/dumpkeymap.man
- synfig-studio/AUTHORS
- synfig-studio/docs/bones_gui.txt
- synfig-studio/src/gui/docks/dockable.cpp
- synfig-studio/src/gui/docks/dockbook.cpp
- synfig-studio/src/gui/duckmatic.cpp
- synfig-studio/src/gui/states/state_normal.cpp
- synfig-studio/src/synfigapp/vectorizer/centerlineskeletonizer.cpp
Found via `codespell -q 3 -L aline,ang,ba,childs,dout,eiter,forse,objext,pard,parms,pevent,propertyst,ro,shouldbe,thru,uint,unselect,vertexes -S ./synfig-studio/po,./synfig-core/po,/synfig-core/m4,./synfig-osx/,./gtkmm-osx,./bugs,.*.eps,*.sif,./synfig-studio/plugins/lottie-exporter`
> chore: fix various typos

- synfig-core/src/modules/mod_ffmpeg/trgt_ffmpeg.cpp
> fix: Synfig reports ffmpeg missing even if it exists (Windows)

- synfig-studio/src/gui/trees/layerparamtreestore.cpp
Calling rebuild() causes two bugs:
1. Parameters panel collapses items on edit (GH#386), when we
we have Animation Mode enabled and are editing parameter that
wasn't previously animated.
'Solution' seems to be to call queue_refresh()
2. Crash (or emit Gtk warning) when we animate a parameter (like
previous case) that uses a combobox for editing (GH#2390), as
Active Layer Name of Switch Layer or Bone Parent in Bones list
of Skeleton Layer.
'Solution' seems to be to call queue_rebuild()
However, when a value node is replaced (via RHandle::replace()),
it already calls Node::signal_changed() so the row is refreshed
by other signal slot.
Fix #386
Fix #2390
> fix: avoid rebuild ParamTreeStore when animating a parameter

- synfig-studio/src/gui/trees/layerparamtreestore.cpp
After merging synfig/synfig#2729
I didn't notice this the first time:
https://user-images.githubusercontent.com/5604544/186569950-b23b4c5b-3f1f-42c7-b60d-07a843db12aa.mp4
> fix: params panel doesn't update after layer switch

- synfig-studio/src/gui/states/state_text.cpp
This happens when the "Multiline text" option is enabled
> fix: pressing the cancel button still adds the text layer

- synfig-core/src/synfig/base_types.cpp
- synfig-core/src/synfig/context.h
- synfig-core/src/synfig/rect.h
- synfig-studio/src/gui/_smach.h
And copy assignment operator returns reference, not a copy.
> fix: "rule of two" : copy constructor and copy assignment operator

- synfig-studio/src/gui/workarea.cpp
- synfig-studio/src/gui/workarea.h
Unfortunately, there is no direct replacement for the arrow icon, so I replaced it with the recommended one.
Original:
`go-next-symbolic` icon:
Recommended (`pan-end-symbolic` icon):
> refactor: replaced deprecated Gtk::Arrow with Gtk::Button with icon

- synfig-core/configure.ac
A bit of history on this fix:
MSYS team removed removed shared libdl.dll and libdl.dll.a
commit: https://github.com/msys2/MINGW-packages/commit/c27ad107f7df624604c96f45d124b761b6fc0aa9
discussion: https://github.com/msys2/MINGW-packages/issues/7548
When compiling synfig it shows the warning:
```
*** Warning: linker path does not have real file for library -ldl.
*** I have the capability to make that library automatically link in when
*** you link to this library.  But I can only do this if you have a
*** shared version of the library, which you do not appear to have
*** because I did check the linker path looking for a file starting
*** with libdl and none of the candidates passed a file format test
*** using a file magic. Last file checked: C:/msys64/mingw64/lib/libdl.a
```
This happens …
> build(autotools): fix MSYS2 build

- synfig-core/src/tool/optionsprocessor.cpp
The problem was double conversion of command line options from local codepage to UTF-8.
Arguments was already converted in main()
> fix: Synfig CLI does not open file if path contains non-Latin characters (Windows)

- synfig-studio/src/gui/CMakeLists.txt
- synfig-studio/src/gui/synfigstudio.rc
MSYS2/Windows only.
The problem occurred when trying to compile Windows resources using the `winres.exe` tool.
If the path to an icon in a resource contains non-Latin characters, then winres.exe cannot
compile this resource. Solved by using a relative path to the icon.
> build(cmake): fixed build when path contains non-Latin characters (MSYS2)

- synfig-core/src/modules/lyr_std/import.cpp
- synfig-core/src/synfig/importer.cpp
Problem detected on creating PR #2491, when I wrongly assumed that could redirect stderr to stdout (FFmpeg import does not like it, as it always write to stderr the FFmpeg version info)
> fix: prevent crash or hang when have problems getting frame on importing

- synfig-core/src/synfig/rendering/opengl/internal/shaders.cpp
- synfig-core/src/synfig/rendering/opengl/task/taskcontourgl.cpp
- synfig-core/src/synfig/rendering/opengl/task/tasktransformationaffinegl.cpp
Since 9c7e20221bd6d2d33db24a90090bf4b05614e58f, `ETL_DIRECTORY_SEPARATOR` is now defined in <ETL/stringf>.
As it will be 'soon' removed anyway, I just changed to `"/"`.
Fixed a couple of typos too.
> fix: broken opengl build (due to ETL_DIRECTORY_SEPARATOR) and typos

- synfig-studio/src/gui/app.cpp
before:
https://user-images.githubusercontent.com/100296264/186509747-ac2fdcf4-c8d9-4640-b8d2-006553db931c.mp4
After:
https://user-images.githubusercontent.com/100296264/186509792-8eb58113-f5e8-4531-8db7-b08615ce9d78.mp4
One thing I'm not sure about though... with the current implementation if the user manually resized the dialog to a greater vertical size, if he then deletes a line then the dialog is auto-adjusted to the size fitting to the number of lines he has, is this okay? or should it be that if it's manually resized the size of the resize is the new minimum size?
Also I just thought of this, should this auto shrink be only when we are deleting the last line?
p.s. excuse the horrendous video quality I had to compress to upload xD.
> feat: Added support for scrolling through text in text paragraph dialog

- 1-setup-linux-native.sh
1) We don't need Python development files. We need only python3 binaries for the plugin system.
2) `python3` package is unnecessary, it will be installed as a dependency for `python3-lxml`.
fix #2832
> build: updated dependencies for Debian 11 based distros

- synfig-core/po/POTFILES.in
- synfig-core/src/modules/mod_dv/trgt_dv.cpp
- synfig-core/src/modules/mod_dv/trgt_dv.h
- synfig-core/src/modules/mod_ffmpeg/mptr_ffmpeg.cpp
- synfig-core/src/modules/mod_ffmpeg/mptr_ffmpeg.h
- synfig-core/src/modules/mod_ffmpeg/trgt_ffmpeg.cpp
- synfig-core/src/modules/mod_ffmpeg/trgt_ffmpeg.h
- synfig-core/src/modules/mod_imagemagick/mptr_imagemagick.cpp
- synfig-core/src/modules/mod_imagemagick/mptr_imagemagick.h
- synfig-core/src/modules/mod_imagemagick/trgt_imagemagick.cpp
- synfig-core/src/modules/mod_imagemagick/trgt_imagemagick.h
- synfig-core/src/synfig/CMakeLists.txt
- synfig-core/src/synfig/Makefile.am
- synfig-core/src/synfig/filesystem.cpp
- synfig-core/src/synfig/filesystem.h
- synfig-core/src/synfig/os.cpp
- synfig-core/src/synfig/os.h
- synfig-studio/src/gui/app.cpp
fix #2108
Known issues (they exist even before this PR)
- ImageMagick importer still doesn't use wchar (argument starting with "png32:) (it already didn't work correctly before)
- Windows package does not provide ImageMagick converter.exe (packaging issue; https://github.com/synfig/synfig/pull/2491#issuecomment-1248258741)
- I believe Windows RunPipe version didn't and doesn't provide exit status :( (I tested once by providing an intentionally malformed ffmpeg call) (it already didn't work correctly before)
> refactor: move non-portable popen code to one place

- ETL/ETL/_boxblur.h
- ETL/ETL/_gaussian.h
- ETL/ETL/_pen.h
- ETL/ETL/_surface.h
- synfig-core/src/synfig/blur.cpp
- synfig-core/src/synfig/color.h
- synfig-core/src/synfig/rendering/software/function/packedsurface.h
- synfig-core/src/synfig/rendering/software/function/resample.cpp
- synfig-core/src/synfig/surface.cpp
- synfig-core/src/synfig/surface.h
It is not actually used. The only non-primitive type that uses it is `synfig::Color`, but `synfig::ColorAccumulator` is a `typedef` to `Color`.
A previous work makes us free to really removed:
7832633f8fe3069e5d83be9bebe0e3258d2f1f93 (#1810, #1805)
> refactor: remove Accumulator type for etl::pen and etl::surface

- synfig-studio/src/gui/duckmatic.cpp
- For Skeleton Deformation layer, it only makes sense for rest mode bones
- For Skeleton layer, bone width is completely useless
(as for other bone info, e.g Z depth)
> fix: hide bone width handles when they are meaningless

- ChangeLog-development.md
- bugs/resolved/000010.txt
- cmake/SynfigVcpkg.cmake
- synfig-core/src/synfig/bezier.h
- synfig-core/src/synfig/node.cpp
- synfig-core/src/synfig/synfig_iterations.h
- synfig-osx/launcher/rootless-common.c
- synfig-studio/ChangeLog.old
- synfig-studio/NEWS
- synfig-studio/src/brushlib/brush.hpp
- synfig-studio/src/synfigapp/vectorizer/centerlinecolors.cpp
Found via `codespell -q 3 -L aline,ang,apendices,ba,bu,childs,dout,eiter,existant,forse,objext,pard,parms,pevent,propertyst,ro,shouldbe,thru,uint,unselect,vertexes -S ./.git,./synfig-studio/po,./synfig-core/po,/synfig-core/m4,./synfig-osx/,./gtkmm-osx,./bugs,.*.eps,*.sif,./synfig-studio/plugins/lottie-exporter`
> chore: fix typos

- synfig-studio/src/gui/render.cpp
fixes #2862 
- renames "Target" to "Module" in renderer dialog
- renames the label variable from `targetLabel` to `moduleLabel`
> refactor: rename "Target" to "Module"

- synfig-core/src/synfig/timepointcollect.cpp
quick fix #2857 .
So from what I understood changing the interpolation of a canvas parameter of a group layer should change the interpolation of itself + the waypoints of the grouped layers which have the same time.
The issue as described was that changing the interpolation of a canvas parameter of a group layer changed along with it other parameters of the group layer. This PR stops that from happening (by not allowing the other waypoints of the group to be a part of the waypoint set we have), but I dont really understand this much so there are two points here :
1.  is the current behaviour the intended behaviour ?
2. does this break anything ? 
And this is just in case previous points are good
1.  is using the layers `get_name()` method to know if its a group safe ? or should I check if …
> fix: changing interpolation of Canvas parameter changes interpolation for other waypoints

- synfig-core/src/modules/mod_magickpp/trgt_magickpp.h
fixed hang when using `mod_magickpp` with ImageMagick 7.1 library
> fix: added ImageMagick 7.1 library initialization

- synfig-studio/src/gui/canvasview.cpp
noticed it while going around the code-base. It doesn't seem to be used.
> refactor: removed unused Gtk::IconSIze

- synfig-studio/po/es.po
Simple typo fixed in the Spanish translation file
> fix(lang): Spanish translation typo

- ETL/ETL/_gaussian.h
broken compilation in synfig/tests due to dd19f7be2d0fe61bb15bc8f51ca123e24d3f9156
> refactor: avoid std::iterator_traits in ETL/gaussian

- synfig-core/test/benchmark.cpp
broke after moving ETL/surface to synfig-core
> test: fix synfig/benchmark test build

- synfig-studio/images/CMakeLists.txt
- synfig-studio/images/Makefile.am
- synfig-studio/images/action_flat_interpolation_icon.sif
- synfig-studio/images/action_innerrounded_interpolation_icon.sif
- synfig-studio/images/action_interpolate_interpolation_icon.sif
- synfig-studio/images/action_offpeak_interpolation_icon.sif
- synfig-studio/images/action_peak_interpolation_icon.sif
- synfig-studio/images/action_rounded_interpolation_icon.sif
- synfig-studio/images/action_squared_interpolation_icon.sif
- synfig-studio/src/gui/iconcontroller.cpp
- synfig-studio/src/gui/instance.cpp
Hi,
While designing a ["modern iconset" for Synfig](https://forums.synfig.org/t/modern-iconset-light-and-dark/13560), I realized the "width interpolation" icons were so simple, they didn't clearly represent what they actually do and there were 2 ones missing: "off-peek" and "inner rounded" interpolation.
This PR tries to update and fulfill those gaps:
I not only added the icons in .sif format but changed the files needed to make it all work (tested under macOS).
I hope you like it.
> feat: New and updated icons for  "width interpolation"

- synfig-studio/src/gui/dialogs/dialog_canvasdependencies.cpp
FreeType layer have a hidden filename parameter...
> fix: don't list empty filenames on Canvas Dependencies dialog

- synfig-studio/src/gui/iconcontroller.cpp
- synfig-studio/src/gui/resources/ui/studio_menubar.xml
- synfig-studio/src/gui/states/state_eyedrop.cpp
Fixes #2900 
should the eye-drop state be renamed as well?
> refactor(UI): rename Eyedrop Tool to Eyedropper Tool

- .github/workflows/conventional-commits-style.yml
The main feature of these PR is the ability to automatically start the check after editing the title of the PR, so no need to restart this check manually.
This is made possible by the GitHub Actions event system.
In this case, we use the `PR edited` event.
```
pull_request:
types: [opened, edited]
```
P.S.
PR title is extracted from GitHub Actions JSON file located at ${GITHUB_EVENT_PATH}
https://docs.github.com/en/actions/learn-github-actions/environment-variables
> GITHUB_EVENT_PATH
> The path to the file on the runner that contains the full event webhook payload. 
> For example, /github/workflow/event.json.
> ci: added conventional commits style check for PR titles

- .github/workflows/synfig-ci.yml
- .github/workflows/synfig-stable.yml
- .github/workflows/synfig-tests.yml
The old actions are deprecated and will stop working soon.
> [Ubuntu 20.04 Focal (CMake+Ninja)](https://github.com/synfig/synfig/actions/runs/3548808344/jobs/5961404035)
Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: actions/checkout@v2, actions/cache@v2
> ci: bump GitHub actions

- .github/workflows/synfig-ci.yml
- .github/workflows/synfig-stable.yml
- .github/workflows/synfig-tests.yml
Ubuntu 18.04 is being deprecated and will be removed by 2022/12/01
https://github.blog/changelog/2022-08-09-github-actions-the-ubuntu-18-04-actions-runner-image-is-being-deprecated-and-will-be-removed-by-12-1-22/
> ci(Github Actions): bump Ubuntu version

- synfig-studio/src/gui/dialogs/dialog_canvasdependencies.cpp
> fix: canvas dependencies dialog crashes with empty filenames or without extension

- .github/workflows/conventional-commits-style.yml
`synchronize` event is fired when you add commits to PR.
At first I thought that there is no reason to add this event, because this change does not change PR title.
But it resets PR statuses, so this check needs to be run again.
> ci: added `synchronize` to the list of processed events

- synfig-studio/src/gui/states/state_eyedrop.cpp
Fixes #2899 
not sure if this is a "refactor" or a "feature". Anyways, pretty straightforward reordereding of condition statement.
> feat: eyedropper tool now takes fill color instead of outline color by default

- synfig-core/src/modules/mod_ffmpeg/trgt_ffmpeg.cpp
error introduced by me in #2915 (c91ce50797be72fa56b59f4aa36c986ef504e7b4)
> fix(ffmpeg): logic for detection of image-only videos was inverted

- README.md
Now it should be clearly visible on the front page.
> chore: added license description in readme

- .gitignore
Adds `/build-cmake/` folder to **.gitignore** file as it is needed under macOS when compiling with Cmake
> chore: added /build-cmake/ folder to .gitignore 

- synfig-studio/src/gui/instance.cpp
- synfig-studio/src/gui/instance.h
tiff, ppm (& variations) and webp
> fix: allow to open external editor for tiff, ppm (& variations) and webp extensions

- synfig-core/src/synfig/timepointcollect.cpp
- synfig-core/src/synfig/timepointcollect.h
- synfig-studio/src/gui/widgets/widget_timetrack.cpp
Fixes #2875 , and adds on to #2858.
So the issue #2858  was fixing was that editing the canvas parameter of a group changed along with it the groups other parameters of the same time. So the fix was to not allow the canvas waypoint to change any of the groups parameters, which in fact was not general enough as if the group has a group beneath it, then in that case the canvas parameter should change the child groups parameters as well (but not its own).
Here is a video demonstration: (note: I'm changing the interpolation via the menu on right click but for some reason windows recorder doesn't record windows on top the window we are in)
https://user-images.githubusercontent.com/100296264/201393112-a217d37d-2b39-4b4f-bf59-c37c11420179.mp4
@morevnaproject, waiting for you review :) also if …
> fix: no context menu when right-clicking on waypoint 

- synfig-studio/src/gui/app.cpp
- synfig-studio/src/gui/app.h
- synfig-studio/src/gui/dialogs/dialog_workspaces.cpp
- synfig-studio/src/gui/mainwindow.cpp
- synfig-studio/src/gui/mainwindow.h
Workspace layout only matters/applies to `MainWindow`, no need to bloat `App` class with this stuff.
> refactor: move workspace methods from App to MainWindow

- synfig-studio/src/gui/dialogs/vectorizersettings.cpp
- replaced deprecated Gtk::VBox with Gtk::Box
- replaced deprecated get_v_box() with get_content_area()
before:
after:
also tested before and after layout and expansion is the same as it was.
> refactor: removed deprecated `Gtk::VBox` and `get_vbox()`

- synfig-studio/images/CMakeLists.txt
- synfig-studio/images/Makefile.am
- synfig-studio/images/layer_distortion_skeletondeformation_icon.sif
- synfig-studio/images/layer_other_filtergroup_icon.sif
- synfig-studio/images/layer_other_freetime_icon.sif
- synfig-studio/images/layer_other_ghostgroup_icon.sif
- synfig-studio/images/layer_other_switch_icon.sif
- synfig-studio/images/sound_icon.sif
- synfig-studio/src/gui/docks/dock_soundwave.cpp
- synfig-studio/src/gui/iconcontroller.cpp
Hi,
I have created some new icons and more, let me explain myself:
- **switch group**: updated as it had a filter icon inside the folder that didn't make sense (as there is a new filter group icon)
- **filter group**: new icon using the filter icon inside the folder
- **ghost group**: new icon, [after discussing it a little bit](https://forums.synfig.org/t/modern-iconset-light-and-dark/13560/22?u=pablogil) I finally included the one I think fits better
- **free time**: new icon
- **skeleton deformation**: used bones with blueish colors as all "deformations" seem to follow that rule
- **sound group**: here I just duplicated the "layer_other_sound_icon" to let Sound Panel to have it's own and unique icon. By now I didn't edit it, but it might be done in the future
Cheers
> feat: missing icons and more

- synfig-core/src/modules/lyr_freetype/lyr_freetype.cpp
FC_WEIGHT_SEMILIGHT and FC_WEIGHT_DEMILIGHT were added in https://cgit.freedesktop.org/fontconfig/commit/fontconfig/fontconfig.h?id=be6506ca04ccce10868a8cd51d89e586284d149b
Release Notes:
https://github.com/freedesktop/fontconfig/blob/2.11.91/README
(Debian 9 uses 2.11.1)
> fix: support FontConfig older than version 2.11.91

- synfig-core/src/synfig/blur.cpp
- synfig-core/src/synfig/blur/gaussian.h
the gaussian_blur_5x5_() method already initializes it
And it was wrong anyway; it initializes the same array 4 times, and left the other 3 uninitialized.
> refactor: remove useless initialization in blur

- synfig-studio/src/gui/app.cpp
fixes #2891 
ctrl + d and ctrl + shift + d, are both already being used for unselect all layer and ducks. I semi-arbitrarily chose ctrl+u as its what comes after the d in duplicate, and anyway the user can change it. But if there is a better initial key pair please let me know :).
> feat: added hotkey for duplicate layer button

- synfig-studio/src/gui/states/state_draw.cpp
- synfig-studio/src/gui/states/state_lasso.cpp
Documentation recommended `signal_button_press_event()` but `signal_clicked()` also does the job and even has a similar prototype.
https://docs.gtk.org/gtk3/signal.Button.pressed.html
p.s. I'm not sure though but it seems like these buttons aren't even used. Should they just be removed ?... I saw a button with the same name made in the refresh toobar method.
> refactor: replaced deprecated `signal_pressed()`  with `signal_clicked()`

- synfig-studio/src/gui/canvasview.cpp
- synfig-studio/src/gui/canvasview.h
- synfig-studio/src/gui/mainwindow.cpp
As it doesn't toggle the visibility itself, so it was a misleading name
> refactor: rename CanvasView::toggle_show_toolbar() to set_show_toolbars()

- synfig-core/src/synfig/layer.cpp
- synfig-core/src/synfig/layers/layer_motionblur.cpp
- synfig-core/src/synfig/layers/layer_solidcolor.cpp
- synfig-core/src/synfig/rendering/software/rendererdraftsw.cpp
- synfig-studio/src/gui/app.cpp
- synfig-studio/src/gui/iconcontroller.cpp
Following the layer naming convention elsewhere.
studio::layer_icon_name() does not need to compare to the layer name aliases because every call actually uses the Layer::get_name(), i.e. the official name, not their aliases.
> refactor: use camelcase for MotionBlur and SolidColor layer names

- synfig-studio/src/gui/canvasview.cpp
`#include <gtkmm/hvseparator.h>` was an old directive which included 
- horizontal and vertical separators (both deprecated and not used in synfig)
-  `#include <gtkmm/separator.h>`
> refactor: replaced deprecated `hvseparator` include directive by `separator`

- .github/workflows/synfig-ci.yml
Was previously disabled due to a crash (macOS) or hang (Linux)
Fixed by #2876
> ci: enabled ImageMagick

- synfig-core/src/synfig/node.h
- synfig-core/src/synfig/soundprocessor.cpp
- synfig-studio/src/gui/dials/jackdial.h
- synfig-studio/src/gui/dials/keyframedial.h
Fix #2964
Details about crash on Ubuntu 16.04:
```
gdb --args /root/projects/build/output/Debug/bin/synfig about_icon.sif -o root/projects/build/output/Debug/share/synfig/icons/classic/128x128/about_icon.png --time 0f
```
```
Thread 1 "synfig" received signal SIGSEGV, Segmentation fault.
0x00007f9a608883f0 in ?? ()
(gdb) bt
#0  0x00007f9a608883f0 in ?? ()
#1  0x00007f9a63db3719 in mlt_property_close () from /usr/lib/x86_64-linux-gnu/libmlt.so.6
#2  0x00007f9a63db5860 in mlt_properties_close () from /usr/lib/x86_64-linux-gnu/libmlt.so.6
#3  0x00007f9a63dc6811 in mlt_factory_close () from /usr/lib/x86_64-linux-gnu/libmlt.so.6
#4  0x00007f9a67f38e73 in synfig::SoundProcessor::subsys_stop () at /root/projects/synfig/synfig-core/src/synfig/soundprocessor.cpp:296
#5  0x00007f9a67e7207b in …
```
> fix: build on Ubuntu 16.04

- synfig-studio/src/gui/canvasview.cpp
- synfig-studio/src/gui/workarea.cpp
- synfig-studio/src/synfigapp/main.cpp
GTK gives Synfig a GdkEvent containing a GdkDevice with the ID "Master pointer for ..." when using a tablet device. The device is not found, causing a crash elsewhere.
> fix: crash occurs under Wayland when using tablet

- synfig-studio/src/gui/workarea.cpp
Even though gdk_device_get_axis() returns true for a drawing tablet, the x/y values it gives are always 0.0. Pressure is correct, however.
> fix: drawing tablet didn't work on Wayland

- synfig-core/src/synfig/CMakeLists.txt
- synfig-core/src/synfig/synfig-config.cmake.in
I wanted to write a program that links against installed synfig, but the default generated cmake config file links against synfig's dependencies targets without providing a way to find them.
Now something like this works:
```cmake
find_package(synfig)
target_link_libraries(main synfig::libsynfig)
```
I also took the liberty to change the cmake installation folder from "synfig-core" to "synfig", but I'm not sure if that's okay.
> build: change exported cmake targets and provide a way to find deps

- synfig-core/src/synfig/rendering/common/task/tasklayer.cpp
- synfig-core/src/synfig/rendering/surface.h
- synfig-core/src/synfig/token.h
I'm trying to understand the Cobra renderer bit by bit. I wrote a [simple program](https://github.com/theartful/exploring-synfig/tree/master/rendering/tokens) to visualize the rendering tokens, and found these two asymptomatic bugs.
I will continue exploring the rendering engine of synfig, and might find similar stuff. Please tell me if these kinds of pull requests are not welcome.
> fix: inconsequential fixes regarding synfig::rendering::Tokens

- synfig-studio/src/synfigapp/actions/valuedescset.h
Found it while working on #2953. The method creates a valuedescset action and adds it to the stack (which seems to be the undoable action list but I didn't look too much as that wasnt directly related to what I was doing).
> chore: fix typo in comment in `valuedescset.h`

- synfig-studio/src/gui/docks/dock_toolbox.cpp
- synfig-studio/src/gui/docks/dock_toolbox.h
Multiple calls (4+) to Dock_Toolbox::change_state_() occur because ToggleToolButton::set_active(), inside Dock_Toolbox::set_active_state(), would cause clicked signals.
This commit reduces the number of calls to just 2. Once for the previous tool button and a second for the new tool button. This is the normal behavior of RadioToolButtons.
> refactor: use RadioToolButton instead of ToggleToolButton for tools dock

- synfig-studio/src/gui/canvasview.cpp
- synfig-studio/src/gui/resources/css/synfig.css
- synfig-studio/src/gui/splash.cpp
Found this while looking through the code for #3014 . It also says this function heavily slows playback so I thought might as well replace it. 
I noticed there is also a synfig.mac.css, not sure if that is used for mac instead of the synfig.css or ig it is just to define an extra class for a fix. If it's not the latter I might have to redefine the classes there as well.
p.s. 
about four months back the whole style context class was deprecated from GTK and now instead for example it should just be
`versionlabel->add_class("color-white");`
the `add_class` method was moved directly to the widget base class, but it doesn't seem to be ported yet to gtkmm. I checked the docs for even the latest verision and it wasn't there.
p.s. 2
I don't know why the verision label is white while the …
> refactor: remove deprecated `Widget::override_color()`

- synfig-studio/src/gui/render.cpp
Just caught my eye... It is not really affecting anything , compiler takes care of it anyways. But just for the sake of a cleaner code base ig :)
p.s. I have been collecting various typos and little things I noticed which seem off during the past week/2 weeks while going through the code in various places. I will wait a bit longer with the typos though just so that they could all be in one compact PR.
> refactor: remove useless return statement at the end of a function

- synfig-core/src/tool/definitions.cpp
- synfig-core/src/tool/definitions.h
- synfig-core/src/tool/joblistprocessor.cpp
- synfig-core/src/tool/optionsprocessor.cpp
- synfig-core/src/tool/optionsprocessor.h
Following my post #3017 , I decided to implement the feature.
Since synfig cli already had a flag for printing benchmark time, I only added the feature to render the same target multiple times.
The total and average time are printed.
> feat: add a CLI flag(--set-repeats) for rendering the same target multiple times

- synfig-core/src/tool/joblistprocessor.cpp
- synfig-core/src/tool/joblistprocessor.h
Divided into commits for easier review.
> refactor: joblistprocessor code split into smaller functions

- synfig-core/src/synfig/os.cpp
Synfig Studio crashes when trying to run on macOS.
`getenv()` can return NULL, so we pass NULL as a `std::string&` reference.
Example code:
```
#include <string>
bool is_empty(const std::string& str) {
return str.empty();
}
int main() {
is_empty(nullptr);
return 0;
}
```
Output:
```
terminate called after throwing an instance of 'std::logic_error'
what():  basic_string: construction from null is not valid
```
Fixed by switching to Glibmm function. In this case, Glibmm returns an empty string.
Linked PR: #2998
> fix: sigsegv when `LANGUAGE`/`LANG` environment variable is not set

- synfig-core/src/synfig/valuenodes/valuenode_blinereversetangent.cpp
- synfig-core/src/synfig/valuenodes/valuenode_boneinfluence.cpp
- synfig-core/src/synfig/valuenodes/valuenode_boneweightpair.cpp
- synfig-core/src/synfig/valuenodes/valuenode_duplicate.cpp
- synfig-core/src/synfig/valuenodes/valuenode_greyed.cpp
- synfig-core/src/synfig/valuenodes/valuenode_integer.cpp
- synfig-core/src/synfig/valuenodes/valuenode_real.cpp
- synfig-core/src/synfig/valuenodes/valuenode_reference.cpp
- synfig-core/src/synfig/valuenodes/valuenode_reverse.cpp
- synfig-core/src/synfig/valuenodes/valuenode_switch.cpp
- synfig-core/src/synfig/valuenodes/valuenode_timeloop.cpp
It turned out that some necessary initialization of the parameter name dictionary (`children_vocab`) is missing in certain places. 
Previously, it worked because a new dictionary was always created when calling `link_count()` or `get_children_vocab()` method (changes made in #2831).
After the changes, some ValueNodes can work incorrectly because the parameter dictionary became empty when accessing it.
This commit fixes this issue.
P.S. 
There are also ValueNodes with a dynamic set of parameters (`ValueNode_BLine`,`ValueNode_DynamicList`, `ValueNode_StaticList`), but they should work correctly because the parameter dictionary is repopulated when the reindex() method is called.
Related PR: #2831
> fix: added a missing `init_children_vocab()` call in ValueNode constructors

- synfig-studio/src/gui/dialogs/dialog_canvasdependencies.cpp
Solve these cases:
* Suppose this file tree:
- Doc_A.sif
- mine.png
- folder/Doc_B.sif
- folder/mine.png
In addition:
- Doc_A.sif has a Layer_Import for the file "mine.png"
- folder/Doc_B.sif has a Layer_Import for the file "mine.png" (pointing to folder/mine.png)
- Doc_A.sif use a linked canvas (i.e. a Layer_PasteCanvas whose source is other file) to folder/Doc_B.sif
In this (long) situation, both mine.png will be parsed as the same file.
* If a canvas has two Layer_Import, one for the file "something.png" and the other to "./something.png", they would be shown as different resources.
> fix(canvas-dependencies): properly identify the file to avoid clash

- synfig-core/src/synfig/synfig_iterations.cpp
As `dyn_param_list` is a reference to a vector, and the vector can change in the loop, it can have invalid "iterators"/items.
Possible solutions:
1. `dyn_param_list` be a copy not a reference
2. Implement a `Layer::replace_dynamic_param()`
3. Store all the changes in another variable and postpone the actual changes until we finish the loop
The first one can create a "large" copy.
The second one is interesting, but I `git grep` the code and it does not seem to be needed anywhere else XD The existent disconnections are for replacing with a (static) ValueBase.
Therefore, I opted for the 3rd solution. It is lighter than option 1 and less 'intrusive' than the second one.
fix #3049
> fix: possible invalid memory access on replacing valuenodes

- synfig-studio/src/gui/canvasview.h
Noticed this while working on #3046. 
They are supposed to be the two initial rows of the library panel. Maybe the original author thought they would be used here. But they are neither used nor initialized with the correct rows that their name indicates.
> refactor: remove unused members of `CanvasView`

- synfig-studio/src/gui/trees/canvastreestore.cpp
- synfig-studio/src/gui/trees/childrentreestore.cpp
Brief bug description:
Clicking on the value column of any of the canvases or valuebase nodes rows causes a crash
this happens because when they are clicked a cellrenderer is in the process of creation 
but it fails in an assertion of the canvas. Now anyways I think it makes no sense to 
click on either of these and have a cellrenderer that could be used to edit anything.
As far as I understand both of these row are just for the purpose of organization (under canvases 
lies the canvases and under valuebase nodes lies all the exported valuebases etc..).
(Canvases and ValueBase Nodes rows -- old pic)
What I did:
Made the cell renderers for these two rows  to be inactive as they are  not needed. (Read next comment for more details)
Fixes #3039
> fix: crash when clicking on rows of "Library Panel" 

- synfig-core/src/synfig/valuenode.cpp
- synfig-core/src/synfig/valuenode.h
- synfig-studio/src/synfigapp/value_desc.cpp
There were two overloaded methods, and all of their arguments have default values:
* LinkableValueNode::get_description(bool show_exported_name = true)
* LinkableValueNode::get_description(int index = -1, bool show_exported_name = true)
The first one is an override of the `ValueNode::get_description` method.
There was an unnecessary ambiguity here. So I renamed the second method to `LinkableValueNode::get_link_description()` to make it explicit, and `index` argument is not optional now.
> refactor: rename method to get_link_description to avoid ambiguity

- synfig-studio/src/synfigapp/wplistconverter.cpp
prevent crash due to NaN with a bline containing only 2 points that are too close
distance[n-1] would be zero, and make the WidthPoint position to be NaN
That problem is propagated, affects `synfig::hom_to_std()` and a crash happens
How to reproduce: with Draw Tool and a drawing tablet, quickly tap twice (or more in a row) at the same point. Synfig Studio crashes.
> fix: crash with a bline containing only 2 points that are too close

- synfig-core/bootstrap.sh
- synfig-core/test/Makefile.am
- synfig-studio/bootstrap.sh
- synfig-studio/images/Makefile.am
- synfig-studio/test/Makefile.am
Fixed:
- "files left after uninstall" error for "distuninstallcheck" target
Backported fix from 1.4 branch: https://github.com/synfig/synfig/commit/e94ea8d6447f39547d762db42e4345258a62a9ae
- ERROR: files left in build directory after distclean: ./po/.intltool-merge-cache.lock
It looks like bug in `libtoolize`: https://bugs.launchpad.net/intltool/+bug/1712194
Fixed by rewriting generated `Makefile.in.in` file.
- bline.cpp:36:10: fatal error: test_base.h: No such file or directory
I'm not sure which way is preferable: using `EXTRA_DIST` or adding `test_base.h` to build the target?
> build: fix `make distcheck` build

- synfig-studio/src/gui/duckmatic.cpp
They are useful for "Link to Skeleton" with spline vertices.
Pointed by: yoSachinkr (https://github.com/synfig/synfig/pull/3044#issuecomment-1501153160)
Related to: #2778 (06f4ca8a72b1792032892194fcf602ab635c6a41)
> fix: width handles must be visible with Skeleton layer

- synfig-studio/src/gui/docks/dock_toolbox.cpp
Otherwise, the shortcut in tooltip would be updated only when software restarts.
> fix: update Tool tip when user changes its shortcut at runtime

- synfig-core/src/synfig/layers/layer_pastecanvas.cpp
- synfig-core/src/synfig/loadcanvas.cpp
- synfig-core/src/synfig/savecanvas.cpp
- synfig-core/src/synfig/timepointcollect.cpp
- synfig-studio/src/gui/actionmanagers/layeractionmanager.cpp
- synfig-studio/src/gui/canvasview.cpp
- synfig-studio/src/gui/cellrenderer/cellrenderer_timetrack.cpp
- synfig-studio/src/gui/dialogs/vectorizersettings.cpp
- synfig-studio/src/gui/duckmatic.cpp
- synfig-studio/src/gui/instance.cpp
- synfig-studio/src/gui/states/state_brush.cpp
- synfig-studio/src/gui/trees/layertreestore.cpp
- synfig-studio/src/gui/waypointrenderer.cpp
- synfig-studio/src/synfigapp/actions/layeradd.cpp
- synfig-studio/src/synfigapp/actions/layercopy.cpp
- synfig-studio/src/synfigapp/actions/layerembed.cpp
- synfig-studio/src/synfigapp/canvasinterface.cpp
- synfig-studio/src/synfigapp/instance.cpp
Instead of etl::handle<Layer_*>, etl::handle<const Layer_*> and etl::loose_handle<Layer_*>
Reason: etl::handle and alike will be moved to synfig namespace (and maybe one day it'll use an C++ standard smart pointer). It'll avoid future changes everywhere.
> refactor: prefer Layer_*::Handle and alike rather etl::handle

- synfig-core/src/synfig/filecontainerzip.cpp
- synfig-core/src/synfig/filesystemgroup.cpp
- synfig-core/src/synfig/filesystemtemporary.cpp
- synfig-core/src/synfig/gradient.cpp
- synfig-core/src/synfig/layer.h
- synfig-core/src/synfig/layers/layer_mime.cpp
- synfig-core/src/synfig/savecanvas.cpp
- synfig-core/src/synfig/valuenodes/valuenode_animatedinterface.cpp
- synfig-studio/src/gui/app.cpp
- synfig-studio/src/gui/cellrenderer/cellrenderer_value.cpp
- synfig-studio/src/gui/docks/dockmanager.cpp
- synfig-studio/src/gui/render.cpp
- synfig-studio/src/gui/states/state_bline.cpp
- synfig-studio/src/gui/states/state_draw.cpp
- synfig-studio/src/gui/states/state_lasso.cpp
- synfig-studio/src/gui/trees/keyframetreestore.cpp
- synfig-studio/src/gui/trees/layerparamtreestore.cpp
- synfig-studio/src/gui/trees/layertreestore.cpp
- synfig-studio/src/gui/widgets/widget_bonechooser.cpp
- synfig-studio/src/gui/widgets/widget_canvaschooser.cpp
- synfig-studio/src/gui/widgets/widget_enum.cpp
- synfig-studio/src/synfigapp/actions/layerfit.cpp
- synfig-studio/src/synfigapp/actions/valuedescset.cpp
- synfig-studio/src/synfigapp/canvasinterface.cpp
- synfig-studio/src/synfigapp/inputdevice.cpp
- synfig-studio/src/synfigapp/vectorizer/centerlineskeletonizer.cpp
And prefer the style of the `for` loop as discussed in the forums https://forums.synfig.org/t/trying-to-define-our-code-style/13097.
```c++
for (int a = 0; a < 30; ++a) {
}
```
(spaces surrounding operators, spaces before `(` and after and `;`, and bracket layout)
> refactor: prefer prefix ++ operators for non-primitive types (part 2)

- synfig-studio/src/gui/instance.cpp
- synfig-studio/src/gui/pluginmanager.cpp
- synfig-studio/src/gui/pluginmanager.h
Plugins can now present to user a simple (not dynamic) configuration dialog and can also get the current state of the canvas (current time and selected layers).
The dialog, if provided by the plugin, will be shown every time before the plugin actually runs.
It is static: it will not enable/disable widget according to user interaction, neither validate data unless the widgets themselves perform validation.
Synfig Studio will automatically search for a file in the plugin script folder, with the same filename, except the extension, that must be ".ui".
- The .ui file must be in Glade format, as it will be constructed via Gtk::Builder.
- Synfig Studio runs on Gtk3, not Gtk4, so write a compatible .ui file.
- Currently, we prefer to support Gtk 3.18. For now, avoid widgets provided later than …
> feat: plugins can  have simple dialog and receive current time and selected layer xpath

- synfig-core/src/synfig/filesystem_path.cpp
- synfig-core/src/synfig/filesystem_path.h
- synfig-core/src/synfig/os.cpp
- synfig-core/src/synfig/os.h
following method signature of C++17 filesystem namespace
> refactor: create filesystem::current_path() and filesystem::absolute()

- synfig-studio/src/gui/iconcontroller.cpp
or anything like that.
To reproduce:
- launch Synfig with a nonexistent icon theme folder as theme
It can happen if:
- user by manually edit the settings file to a nonexistent icon theme;or
- user set an existent icon theme, but deletes the icon theme folder without change the icon theme before
> fix: avoid crash if icon theme does not provide type_bool_icon file

- synfig-studio/src/gui/actionmanagers/layeractionmanager.cpp
- synfig-studio/src/gui/app.cpp
- synfig-studio/src/gui/canvasview.cpp
- synfig-studio/src/gui/docks/dock_canvases.cpp
- synfig-studio/src/gui/docks/dock_history.cpp
- synfig-studio/src/gui/docks/dock_toolbox.cpp
- synfig-studio/src/gui/docks/dock_toolbox.h
- synfig-studio/src/gui/iconcontroller.cpp
- synfig-studio/src/gui/iconcontroller.h
- synfig-studio/src/gui/instance.cpp
- synfig-studio/src/gui/instance.h
- synfig-studio/src/gui/mainwindow.cpp
- synfig-studio/src/gui/statemanager.cpp
- synfig-studio/src/gui/statemanager.h
Reported-by: pablogil
Via: https://forums.synfig.org/t/modern-iconset-light-and-dark/13560/31
> fix: some icons didn't follow icon theme

- synfig-studio/src/gui/app.cpp
Removed: `SYNFIG_AUTO_ADD_SKELETON_LAYER`, `SYNFIG_AUTO_ADD_MOTIONBLUR_LAYER`
> refactor: delete old debug envvars that aren't needed anymore

- synfig-core/src/synfig/time.cpp
- synfig-core/src/synfig/time.h
Time::c_str() :
- not used
- not needed
- wrong (returned value is invalid, due to be from a temp value)
> refactor(Time): change epsilon_() method to constant; remove c_str()

- synfig-studio/src/gui/docks/dock_metadata.cpp
- synfig-studio/src/gui/iconcontroller.cpp
- synfig-studio/src/gui/resources/ui/dialog_workspaces.glade
reported-by: pablogil
fix #3116
> fix: make delete icon name independent of old Gtk

- synfig-studio/src/gui/widgets/widget_defaults.cpp
As we don't have any specific icon for these actions, we use current +/- signs as fallback if icons do not exist in current icon theme
Requested-by: pablogil in https://forums.synfig.org/t/help-code-changes-in-order-to-add-an-icon/13585/19
> refactor: brush size increase/decrease buttons now use theme icons

- synfig-core/src/synfig/os.cpp
Now, if a command does not exist or cannot be run, RunPipe::open() reports failure.
Related to: PR #2491 (3793e18be9493a428ec8258e2ec8df6416efd359)
> fix: properly report failure on pipe creation on POSIX systems

- synfig-studio/src/gui/docks/dock_toolbox.cpp
- synfig-studio/src/gui/statemanager.cpp
After commit 4e7a9f38a008d2ff4ebf70ebd465d12aecc27fe6 (PR #3109)
If set, related action tooltip overrides the query_tooltip slot.
(regression from #3066)
> fix: tool tooltip didn't show the shortcut/hotkey

- synfig-studio/src/gui/render.cpp
regression introduced in c06a9a0 via #3094
fix #3128
> fix: filename was shown truncated in Render dialog

- synfig-studio/src/gui/app.cpp
regression introduced when respective StockID were replaced by icon name
fix #3131
> fix: restore shortcuts for edit cut/copy/paste and app quit

- synfig-studio/src/gui/states/state_rotate.cpp
Nothing major just something I noticed while going through this area.
> refactor: make argument name consistent in method declaration and definition

- synfig-core/src/modules/mod_geometry/advanced_outline.cpp
- synfig-core/src/synfig/rendering/primitive/contour.cpp
- synfig-studio/src/gui/dialogs/canvasresize.cpp
and let us see only the valid warnings ;)
C++17 added the [[fallthrough]] attribute.
As we stick with C++11 for now, I made alternative ways I find out here: 
https://en.cppreference.com/w/cpp/feature_test
https://stackoverflow.com/questions/45129741/gcc-7-wimplicit-fallthrough-warnings-and-portable-way-to-clear-them/52707279#52707279
https://stackoverflow.com/questions/44511436/how-to-do-an-explicit-fall-through-in-c
> refactor: add fallthrough mark in switch cases to avoid unneeded warning

- synfig-studio/src/gui/workarea.cpp
as requested in issue  [#3084](https://github.com/synfig/synfig/issues/3084)
> feat: double clicking guides opens edit dialog

- synfig-core/src/synfig/blur.cpp
...to avoid unneeded warning
PR #3143 (655a04290fba9f439eae14848ee571ba97e39941) missed them. My bad.
> refactor: add missing fallthrough mark in other switch cases

- synfig-studio/src/gui/states/state_brush.cpp
Fixes one of the two issues in #1161
Opening brush tool and then clicking cancel in the file chooser dialog crashed Synfig (before this pr). The brush tool still crashes Synfig when used though on correct files I will work on that in another PR. 
Current state after fix:
[Screencast from 08-04-2023 06:00:38 PM.webm](https://github.com/synfig/synfig/assets/100296264/8e418927-d3c2-4ac3-a5a3-b7fdaa941651)
> fix: brush tool crashes synfig if no layer is selected in the dialog

- synfig-studio/src/gui/dialogs/dialog_setup.cpp
as stated in issue [#3155](https://github.com/synfig/synfig/issues/3155)
> fix: fixed icons in Preferences dialog in Windows

- synfig-studio/src/gui/_smach.h
- synfig-studio/src/gui/docks/dock_toolbox.cpp
- synfig-studio/src/gui/statemanager.cpp
- synfig-studio/src/gui/states/state_bline.cpp
- synfig-studio/src/gui/states/state_bone.cpp
- synfig-studio/src/gui/states/state_brush.cpp
- synfig-studio/src/gui/states/state_circle.cpp
- synfig-studio/src/gui/states/state_draw.cpp
- synfig-studio/src/gui/states/state_eyedrop.cpp
- synfig-studio/src/gui/states/state_fill.cpp
- synfig-studio/src/gui/states/state_gradient.cpp
- synfig-studio/src/gui/states/state_lasso.cpp
- synfig-studio/src/gui/states/state_mirror.cpp
- synfig-studio/src/gui/states/state_normal.cpp
- synfig-studio/src/gui/states/state_polygon.cpp
- synfig-studio/src/gui/states/state_rectangle.cpp
- synfig-studio/src/gui/states/state_rotate.cpp
- synfig-studio/src/gui/states/state_scale.cpp
- synfig-studio/src/gui/states/state_sketch.cpp
- synfig-studio/src/gui/states/state_smoothmove.cpp
- synfig-studio/src/gui/states/state_star.cpp
- synfig-studio/src/gui/states/state_stroke.cpp
- synfig-studio/src/gui/states/state_text.cpp
- synfig-studio/src/gui/states/state_width.cpp
- synfig-studio/src/gui/states/state_zoom.cpp
- synfig-studio/test/smach.cpp
> refactor: replaced Gtk::StockID in tool labels with custom implementation

- synfig-core/src/synfig/filesystem_path.cpp
Currently it fails with error:
```
filesystem_path.cpp:371:24: error: no matching function for call to
'std::__cxx11::basic_string<char>::append(const string&, long unsigned int&)'
p.append(path_, a_pos);
```
> fix: build on Debian 9

- synfig-studio/src/gui/actionmanagers/layeractionmanager.cpp
- Cut icon name had a minor typo
- Copy icon was referring to "gtk-copy" and it's not valid (at least in macOS), so I guess the correct one is "edit-copy" as happens with Cut and Paste ones.
> fix: wrong Copy and Cut icon names

- synfig-core/src/modules/mod_noise/valuenode_random.cpp
> refactor: remove unnecessary `const` in internal typedef

- synfig-core/src/synfig/savecanvas.cpp
on canvas saving.
It is encoded the same any LinkableValueNode is.
> refactor: remove unneeded special XML encoding for subtract valuenode

- synfig-studio/src/gui/canvasview.cpp
- synfig-studio/src/gui/resources/css/synfig.css
Before:
After:
fix: https://github.com/synfig/synfig/issues/3160
> fix: current time widget color in dark theme

- synfig-studio/src/gui/instance.cpp
it ends string sooner (not automatic string conversion).
https://github.com/synfig/synfig/pull/2996#issuecomment-1690726833
Reported-by: pgilfernandez
> fix(plugin): requesting current_time invalidates JSON data

- synfig-studio/src/synfigapp/action_system.cpp
- synfig-studio/src/synfigapp/action_system.h
The problem was that every time any property node emitted signal_changed() during an action, it would cause the canvas to queue a render. The number of times signal_changed() happens seems to grow non-linearly with the number of objects being modified during the action. This was a killer for bulk update actions, where this could easily trigger thousands or potentially even millions of unnecessary renders. I have seen a single bulk action take almost an hour.
The fix is to temporarily block the Canvas_Interface::signal_dirty_preview() signal while an action is in progress, and then manually trigger it once the action completes. This guarantees the scene will only render once the action is done, and seems to be a dramatic performance improvement in longer animations at least in my testing. …
> perf: optimized Action_System so that the canvas only renders once during an action

- synfig-studio/src/gui/widgets/widget_curves.cpp
Reproduction steps:
1. Select an animated handle, and open the Graphs window.
2. Right click any waypoint in the Graphs window, and without selecting any menu item (or by selecting an item that's outside of the Graphs area), click in the Canvas work area. Notice the tooltip is still open.
3. Left click any other handle in the work area. Synfig crashes.
The problem was the tooltip draw event was directly referencing an iterator that gets invalidated when the new handle is selected. The next time it tries to draw, it dereferences the bad iterator and crashes.
A nice side effect of this change is the tooltip for the deleted waypoint goes away now after you delete it.
https://github.com/synfig/synfig/assets/143972888/aea7a137-3717-476a-b16a-d1a4419b84a8
The recording didn't capture the …
> fix: selecting a handle while the Graphs window tooltip is open crashes the gui

- synfig-core/src/synfig/target_scanline.cpp
- synfig-core/src/synfig/target_scanline.h
related to https://github.com/synfig/synfig/issues/2847
fix https://github.com/synfig/synfig/issues/2943
> refactor: increase the pixels per frame without render split in Target_Scanline

- synfig-studio/src/gui/resources/ui/dialog_workspaces.glade
Simple fix for https://github.com/synfig/synfig/issues/3174 as @rodolforg suggested.
Thanks
> fix: revert Custom Workspaces Editor button labels to GTK ones

- synfig-studio/src/gui/cellrenderer/cellrenderer_value.cpp
the short textual representation of a parameter that is Transformation value type (e.g. Group Layer's transformation) displayed scale vector as it was a distance (i.e. pixels or Synfig units), but it is just a multiplicative factor.
> fix: scale value of transformation on Parameters Panel is dimensionless

- autobuild/osx/app-template/Contents/Info.plist
This PR closes https://github.com/synfig/synfig/issues/3222.
After a pretty deep analysis I found out the problem was simple: a `plist` file uses XML language and ampersand symbol "&" is an special character that can't be used alone, causing the XML file to be corrupted and so on the .plist file.
It was used for the following text twice in the file:
```
<string>© 2001-2023 Synfig developers & contributors</string>
```
while they should be:
```
<string>© 2001-2023 Synfig developers &#38; contributors</string>
```
This way the .plist file works fine and shows correctly not only the icon but the version and copyright tags:
Cheers
> fix: fixed macOS Info.plist file

- synfig-core/src/synfig/canvas.cpp
- synfig-core/src/synfig/canvasfilenaming.cpp
- synfig-core/src/synfig/filesystem_path.cpp
- synfig-core/src/synfig/filesystem_path.h
- synfig-core/test/filesystem_path.cpp
- synfig-studio/src/gui/widgets/widget_filename.cpp
and implements missing lexically_proximate(), that actually do what old ETL relative() did.
relative() returns empty path if path isn't relative to base path.
It also fixes the Widget_Filename error triggered by clicking on its Open button with an absolute path (it just concatenated current path with file path). See https://github.com/synfig/synfig/pull/3214#issuecomment-1718733044 .
fix #3212
> fix: issues with importing with absolute paths from different root path

- synfig-studio/src/gui/docks/dock_children.cpp
- synfig-studio/src/gui/docks/dock_keyframes.cpp
- synfig-studio/src/gui/docks/dock_layergroups.cpp
- synfig-studio/src/gui/docks/dock_layers.cpp
- synfig-studio/src/gui/docks/dock_params.cpp
- synfig-studio/src/gui/docks/dock_timetrack2.cpp
- synfig-studio/src/gui/resources/css/synfig.css
- synfig-studio/src/gui/trees/childrentree.cpp
- synfig-studio/src/gui/trees/keyframetree.cpp
- synfig-studio/src/gui/trees/layergrouptree.cpp
- synfig-studio/src/gui/trees/layertree.cpp
- synfig-studio/src/gui/widgets/widget_timetrack.cpp
- Timetrack panel named as `timetrack_panel`
- Timetrack widgets use class `timetrack`
- Keyframes panel named as `keyframes_panel`
- Keyframes widgets use class `keyframes`
- Layers panel named as `layers_panel`
- LayerTree widgets use class `layers`
- Parameters panel named as `parameters_panel`
- ParameterTree widgets use class `parameters`
- LayerSets panel named as `layersets_panel`
- LayerSetTree widgets use class `layersets`
- Library panel named as `library_panel`
- Library widgets use class `library`
> feat: add CSS classes and id to widgets/panels to allow visual customization

- synfig-studio/src/gui/widgets/widget_timetrack.cpp
- synfig-studio/src/gui/widgets/widget_timetrack.h
You can provide it with CSS selector:
.timetrack:selected
If it doesn't exist (i.e. provides the same color as its background), it uses the same color of Parameters Panel.
> feat: widget Timetrack now can have its own color for selected row

- synfig-studio/src/gui/widgets/widget_timetrack.cpp
Odd rows have an additional class "odd".
Similarly, even rows have "even" class.
> feat: workaround to allow to alternate even/odd row colors for Timetrack

- synfig-core/src/modules/mod_ffmpeg/mptr_ffmpeg.cpp
- synfig-core/src/modules/mod_ffmpeg/trgt_ffmpeg.cpp
- synfig-core/src/synfig/main.cpp
- synfig-core/src/synfig/os.cpp
- synfig-core/src/synfig/os.h
- synfig-core/src/tool/definitions.cpp
- synfig-core/src/tool/definitions.h
- synfig-core/src/tool/main.cpp
- synfig-studio/src/gui/main.cpp
- synfig-studio/src/player/main.cpp
Set synfig::OS::fallback_binary_path once instead
> refactor: synfig::OS::get_binary_path() doesn't require a fallback anymore

- .github/workflows/synfig-ci.yml
Example output: https://github.com/ice0/crash_test/actions/runs/6526956239/job/17721247606
> ci: added backtrace output in case of build fail

- synfig-studio/src/gui/trees/layertree.cpp
and not the Z Depth...
From:
To:
> fix: column 'name' of Layers panel should be the largest one

- synfig-studio/src/gui/resources/css/synfig.css
Following PR https://github.com/synfig/synfig/pull/3242 here are the proposed styles for having alternate even/odd rows in Synfig.
These styles are compatible with both light/dark themes:
Cheers
> feat: add Layers, Parameters and Timetrack treeviews styles for even/odd rows

- .github/workflows/synfig-ci.yml
Homebrew has stopped building Big Sur bottles as of https://github.com/Homebrew/brew/pull/16019
> ci(Github Actions): bump macOS version

- synfig-studio/src/gui/app.cpp
mistake done in 4f1bd3d9d8 (#3229)
> fix: recent file list is reversing every time Synfig Studio launches

- synfig-studio/src/gui/workarea.cpp
it is provided by synfig-core/src/string_helper.h since 920d20fd (#2735)
> refactor: remove unneeded macro stratof

- synfig-studio/src/gui/app.cpp
Attempting to open a file on Windows whose full path is longer than 23 characters shows an error message "Unable to load [first 23 characters of filepath]".
Looks like this started happening after fc26742, though I'm not sure why it wasn't happening before. That version used the same `sizeof` logic except on a `char*` (size 8) instead of a `std::vector<wchar_t>` (size 24) so I would have thought the issue would have happened in that version as well. Either way I guess.
`sizeof` is a doozy of an operator.
> fix: unable to open file paths longer than 23 characters on Windows

- synfig-core/src/synfig/main.cpp
Broken since 07897538bc847153e48f525e7aefeaa4bea11fe4 (included in #2710)
Also, it now uses wide string for folder path.
> fix: missing OS namespace for MSVC compiler code

- synfig-core/src/tool/optionsprocessor.cpp
GUI works fine because it already passes the full filename to synfig::open_canvas_as(), but CLI doesn't.
GUI opens a file via:
1. App::on_open()
2. App::dialog_open() followed by App::open()
3. App::open_recent()
And all three work well.
fix #3271
> fix: layer ListImporter cannot fetch the right files on synfig CLI

- synfig-studio/src/gui/modules/mod_palette/dock_paledit.cpp
The most major memory leak in the refresh() function has been fixed, however some other memory leaks seem to still be there.
> fix: memory leak when the load default palette button is repeatedly pressed

- synfig-core/src/synfig/filesystem_path.cpp
- synfig-core/src/synfig/filesystem_path.h
- synfig-core/test/filesystem_path.cpp
- synfig-studio/src/gui/canvasview.cpp
It doesn't strip slash character '/' before drive letter
culprit: f31dd3a79b10d8e14d1f09fa85bccfd53928e855 (#3229)
fix #3279
> fix: dropped image file doesn't load (broken conversion URI to file path on Win32)

- synfig-core/src/synfig/os.h
Currently build fails with an error:
```
os.cpp:171:1: error: no declaration matches 'void synfig::OS::RunPipe::__printf__(const char*, ...)'
171 | OS::RunPipe::printf(const char* __format, ...)
| ^~
os.cpp:171:1: note: no functions named 'void synfig::OS::RunPipe::__printf__(const char*, ...)'
In file included from os.cpp:36:
os.h:129:8: note: 'struct synfig::OS::RunPipe' defined here
129 | struct RunPipe {
```
This happens because `libintl` redefines printf, so it is redefined in `os.cpp` (as it includes `synfig/localization.h -> libintl.h`) but not redefined in `os.h`.
Another way to resolve this issue is to rename the `printf` method to something like `custom_printf`.
> fix: mingw cross-build

- synfig-core/configure.ac
There are many warnings about `auto_ptr`, something like:
```
/usr/include/libxml++-2.6/libxml++/parsers/saxparser.h:224:8: warning: ‘template<class> class std::auto_ptr’ is deprecated [-Wdeprecated-declarations]
224 |   std::auto_ptr<_xmlSAXHandler> sax_handler_;
```
> build(autotools): suppress warnings from libxml++

- synfig-studio/src/gui/trees/layertree.cpp
> fix: no need to show "Icon" header text to Layers Panel

- synfig-studio/src/gui/canvasview.cpp
- synfig-studio/src/gui/dialogs/dialog_canvasdependencies.cpp
- synfig-studio/src/gui/dialogs/dialog_canvasdependencies.h
- synfig-studio/src/gui/localization.h
- synfig-studio/src/gui/resources/ui/dialog_canvasdependencies.glade
For now, it won't work on animated valuenodes or any other value node type. User is warned on those cases and no action is performed.
> feat: allow to change resource filepath in Canvas Dependencies dialog

- synfig-core/src/synfig/os.cpp
> fix: synfig::OS::RunPipeWin32::is_open() return on fail

- synfig-studio/src/gui/modules/mod_palette/dock_paledit.cpp
This PR fixes the issue mentioned in https://github.com/synfig/synfig/issues/3215
Fill Color will be passed as the argument in the `add_color` method to add the fill color instead of the outline color to the palette.
> fix: add fill-color instead of outline-color to palette

- .github/workflows/conventional-commits-style.yml
This will allow to start subjects from uppercase words. Currently it fails on something like:
```
fix: Gitlab CI pipeline fixed
build: CMake sets wrong Synfig Studio/ETL versions
```
P.S. If I understand correctly, this change does not violate the standard. 
Discussion here: https://github.com/conventional-changelog/commitlint/issues/2141
P.P.S. Puppeteer did the same: https://github.com/puppeteer/puppeteer/pull/8091/files
> ci(commitlint): disabled rule for `subject-case`

- .github/workflows/conventional-commits-style.yml
- .github/workflows/synfig-ci.yml
- .github/workflows/synfig-stable.yml
- .github/workflows/synfig-tests.yml
This is required because Node.js 16 actions are deprecated.
For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
> ci: bump github actions version

- .github/workflows/synfig-ci.yml
- .github/workflows/synfig-stable.yml
We are currently saving a lot of caches using this pattern:
`{OS}-ccache-{toolchain}-{timestamp}`
After this change there will be only one cache entry for each OS/toolchain.
Also cache entry will be saved only for the master branch.
So PR's can use this cache, but won’t change it.
> ci: changed caching logic

- synfig-core/po/POTFILES.in
- synfig-core/src/modules/mod_magickpp/CMakeLists.txt
- synfig-core/src/modules/mod_magickpp/Makefile.am
- synfig-core/src/modules/mod_magickpp/main.cpp
- synfig-core/src/modules/mod_magickpp/mptr_magickpp.cpp
- synfig-core/src/modules/mod_magickpp/mptr_magickpp.h
Suggested in discussion of #2795
https://github.com/synfig/synfig/pull/2795#issuecomment-1242883274
to allow SVG import in .lst files, without imagemagick module
it also:
fix #2008
> feat: add Magick++ as possible importer too

- synfig-core/src/tool/optionsprocessor.cpp
- synfig-studio/src/gui/dialogs/dialog_ffmpegparam.cpp
Hi,
I found out that Synfig could render WebM files (even with transparency) through FFMPEG but it wasn't clear enough for normal users so I just added VP8 and VP9 codecs to the FFMPEG "Available Video Codecs" list.
Now it's so easy to render this kind of videos for OBS or any other purpose ;-)
> feat: add WebM video format to ffmpeg codecs list

- synfig-studio/src/gui/docks/dock_info.cpp
On every mouse move on CanvasView, it reads what color is underneath the mouse pointer.
We can avoid calls to `Layer::get_color()` (that can parse all canvas layers) and their computation if DockInfo is not mapped.
'signal_map', in GTK words, is emitted 'when the widget is visible and all its parents up to the toplevel widget are also visible.'
DockInfo is not mapped when another tab/dock is being shown in its 'block' (DockBook), as it is in default workspace layout.
> perf: avoid canvas inspection when DockInfo is not shown

- synfig-studio/src/synfigapp/canvasinterface.cpp
1. Create two guide lines.
2. Delete one of them (by dragging back to ruler).
3. Delete the second one. There is no guideline anymore.
4. Undo (ctrl+Z). Wrong. The two guidelines reappear, but only one should.
5. Undo again. Error: only one guide is shown
6. Redo (ctrl+shift+Z or ctrl+Y). Error. Only one is now shown.
Due to changes in b172e3771a131dbd26879aae334b84ac26bcb6e6 (#2777)
> fix: undo didn't work properly after deleting last guide line

- synfig-core/src/modules/mod_magickpp/mptr_magickpp.cpp
There was an undefined behavior due to multiple increment of same variable in multiple function arguments. - sorry
fix #3331
> fix: importing via magick++ for version >= 7.0.1

- synfig-core/src/synfig/layers/layer_motionblur.cpp
For linear subsampling type, there is an undefined behavior when both subsample (start and end) amounts are 0.
Synfig version 1.0.2: *none* is drawn!
Synfig version 1.2.1: a pale gray rectangle is drawn
Synfig version 1.4.3: a black gray rectangle is drawn
Anyway, this commit fixes the case when both are 0, by drawing the context without any motion blur effect.
Note:
If they (the subsample amounts) are equal, but both nonzero, the canvas is normally drawn.
Behavior is not the same between 1.0.2 and >=1.2.1 though. The motion trail has a different number of 'echoes': 1.0.2 has less than the next releases.
fix #3345
> fix(MotionBlur): undefined behavior when subsample range is 0

- .github/workflows/synfig-ci-self-hosted.yml
This PR adds CI job, which builds OSX package on our local machine (self-hosted instance for GitHub Actions).
The machine is processing tasks from 04:00 GMT till 11:00 GMT.
> ci: Add CI action for OSX packaging script

- .github/workflows/synfig-ci.yml
- 1-setup-osx-brew.sh
Currently it fails with following errors:
```
glibtoolize: copying file 'libltdl/COPYING.LIB'
glibtoolize:   error: creating 'libltdl/Makefile.am' from '/usr/local/Cellar/libtool/2.4.7/share/libtool/Makefile.am' failed
glibtoolize: copying file 'libltdl/README'
glibtoolize:   error: creating 'libltdl/configure.ac' from '/usr/local/Cellar/libtool/2.4.7/share/libtool/configure.ac' failed
glibtoolize: copying file 'libltdl/aclocal.m4'
glibtoolize:   error: creating 'libltdl/Makefile.in' from '/usr/local/Cellar/libtool/2.4.7/share/libtool/Makefile.in' failed
glibtoolize: copying file 'libltdl/config-h.in'
glibtoolize:   error: creating 'libltdl/configure' from '/usr/local/Cellar/libtool/2.4.7/share/libtool/configure' failed
```
> build: fix macOS build

- ETL/Makefile.am
The "./autobuild/synfigstudio-release.sh" command was failing without this fix.
> chore: Fix generation of source packages using Autotools

- synfig-core/src/modules/lyr_std/bevel.cpp
- synfig-core/src/modules/lyr_std/bevel.h
- synfig-core/src/synfig/blur.cpp
Maybe a minor performance improvement because it now does a single memory allocation (instead of 4) per Blur call.
> refactor: clean up Bevel layer

- synfig-core/bootstrap.sh
- synfig-studio/bootstrap.sh
For compatibility with MacOS we have to make sure "sh" binary is found in "/bin/sh", not "/usr/bin/sh"
> chore: fix #3398 - Missing install-sh script on macOS

- synfig-core/src/synfig/filesystem_path.cpp
- synfig-core/test/filesystem_path.cpp
wrong hexadecimal to decimal conversion
fix #3409
> fix: drag-n-drop import when filename contains non-latin chars

- synfig-core/src/modules/mod_imagemagick/mptr_imagemagick.cpp
- synfig-core/src/modules/mod_imagemagick/trgt_imagemagick.cpp
https://learn.microsoft.com/en-us/windows/win32/api/processthreadsapi/nf-processthreadsapi-createprocessw
> If the file name does not contain an extension, .exe is appended.
> Therefore, if the file name extension is .com, this parameter must
> include the .com extension.
> If the file name ends in a period (.) with no extension, or if the
> file name contains a path, .exe is not appended.
> fix: convert.exe directory and missing extension

- synfig-core/src/synfig/valuenodes/valuenode_composite.h
- synfig-core/src/synfig/valuenodes/valuenode_radialcomposite.h
> refactor: avoid macro in header file of ValueNode_Composite

- .github/workflows/synfig-ci.yml
- synfig-core/test/test_base.h
In macOS 13, Apple updated clang to version 15, which caused Synfig to stop building.
P.S. GitHub macOS 12 deprecation notice: https://github.com/actions/runner-images/issues/10721
> fix: clang build (and bump macOS version)

- 2-build-cmake.sh
- autobuild/build.sh
- autobuild/msys2/build_mlt.sh
- autobuild/synfigstudio-release.sh
- cmake/InstallMSYS2.cmake
This PR upgrades the MLT framework from 7.2.0 to 7.28.0 in the MSYS2 environment. This update addresses issue #3026 where the MLT framework fails to build in the MSYS2 environment.
> fix: Upgraded MLT version from '7.2.0' to '7.28.0' under MSYS2 environment

- synfig-studio/src/gui/cellrenderer/cellrenderer_value.cpp
- synfig-studio/src/gui/cellrenderer/cellrenderer_value.h
- synfig-studio/src/gui/dialogs/dialog_color.cpp
- synfig-studio/src/gui/dialogs/dialog_color.h
- synfig-studio/src/gui/dialogs/dialog_gradient.cpp
- synfig-studio/src/gui/dialogs/dialog_gradient.h
- synfig-studio/src/gui/trees/layertree.cpp
Here we prevent to emit signal_edited_ for Color and Gradient dialog
windows when presented by Parameter Panel.
Those dialogs may be opened by a cell and try to update the parameter
value related to another one, as it just remembered its parameter tree
path.
Reproducible steps:
1. Create a region layer
2. Create an outline layer
3. Click on color parameter to edit it
4. Without closing color dialog, select the region layer instead
5. Try to edit the color in dialog
6. Error Message appears
fix #3288
> fix: color/gradient dialog edits the parameter that opened itself

- synfig-core/src/modules/mod_svg/svg_parser.cpp
- synfig-core/src/modules/mod_svg/svg_parser.h
It doesn't handle <textPath>, text span (<tspan>), stroke, multiple lines, and per-character transformations (offset and rotation) autowrap, font selection among options...
But it does some work, I promise ;)
> feat(SVG): naive support to Text element

- synfig-studio/src/synfigapp/value_desc.h
Note: sadly the usage is low.
By adding debug messages on copy constructor and assignment operator, it can be seen there is *a lot* of copy while clicking around, moving mouse or even after a Alt+Tab to change to other application.
> refactor: add move constructor and move assignment operator to ValueDesc

- .github/workflows/synfig-ci-self-hosted.yml
If previous build was terminated due to hard reset, then build dir remains in read-only state, which prevents next runs of CI jobs.
This is attempt to fix such situation.
> ci: Resolve error when build dir cannot be removed after previous (failed) run

- .github/workflows/show-pr-change-note.yml
This fixes the issue where contributors weren't automatically shown how their pull requests affect the release notes if the pull request was created from a forked repository. This is crucial because (as I understand) Synfig’s contribution mechanism relies entirely on forking.
The change uses the GitHub Actions event pull_request_target instead of pull_request, which:
1. Solves the above permissions issue.
2. Maintains security since it only uses the workflow defined in the main branch of the official Synfig repository, avoiding execution of untrusted code from the fork.
For more details on the difference between pull_request and pull_request_target, check [this](https://stackoverflow.com/a/74959635/12263075)
> fix(ci): show-pr-change-note not working with prs from forks

- synfig-studio/src/gui/canvasview.cpp
And so hiding toolbars was basically useless.
> fix: resolve issue with toolbar space remaining visible after hiding

- synfig-studio/src/synfigapp/actions/valuedescdisconnect.cpp
Also this fixes MSYS2 MinGW warning:
```bash
/synfig-studio/src/synfigapp/actions/valuedescdisconnect.cpp:122:104:
C:/msys64/mingw64/include/c++/14.2.0/bits/atomic_base.h:501:31: warning: 'unsigned int __atomic_load_4(const volatile void*, int)' writing 4 bytes into a region of size 0 overflows the destination [-Wstringop-overflow=]
501 |         return __atomic_load_n(&_M_i, int(__m));
|                ~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~
In static member function 'static bool synfigapp::Action::ValueDescDisconnect::is_candidate(const synfigapp::Action::ParamList&)':
cc1plus.exe: note: destination object is likely at address zero
```
> fix: prevent potential null pointer dereference in ValueDescDisconnect action

- synfig-core/src/synfig/layer.cpp
- synfig-core/src/synfig/layer.h
- synfig-core/src/synfig/rendering/common/task/tasklayer.cpp
- synfig-core/src/synfig/rendering/common/task/tasklayer.h
Some were not override, other have useless parameters.
> refactor: cleanup Layer::get_sub_renddesc*() methods

- synfig-core/src/synfig/loadcanvas.cpp
- synfig-studio/src/gui/states/state_draw.cpp
- synfig-studio/src/gui/states/state_lasso.cpp
- synfig-studio/src/gui/trees/childrentreestore.cpp
- synfig-studio/src/synfigapp/canvasinterface.cpp
- synfig-studio/src/synfigapp/canvasinterface.h
It is commented-out since initial commit in 2005.
It also removes the code on loading canvas that automatically deletes exported Value Nodes whose ID starts with "Unnamed". It can be safely removed because:
1. this code slice also dates back 2005
2. by using `git grep Unnamed`, it can be seen the only place that sets a valuenode ID as "Unnamed..." is the commented-out CanvasInterface::auto_export() this PR deletes.
> refactor: remove unused CanvasInterface::auto_export() method

- synfig-core/src/synfig/valuenodes/valuenode_bline.cpp
- synfig-core/src/synfig/valuenodes/valuenode_blinecalctangent.cpp
- synfig-core/src/synfig/valuenodes/valuenode_blinecalcvertex.cpp
- synfig-core/src/synfig/valuenodes/valuenode_blinecalcwidth.cpp
- synfig-studio/src/synfigapp/actions/valuedescblinelink.cpp
The action "Link to Spline", when used to link to a Polygon, crashes Synfig Studio.
Another commit/PR should support it.
For now, it just doesn't show the option for the user in this forbidden case anymore.
Problem backs to 1.0.2 at least.
Fix #3480
> fix: crash when trying to link to polygon instead of spline

- synfig-core/src/synfig/soundprocessor.cpp
The MLT framework we use as our audio backend for
Sound layer changed how it creates blank audio: since version 7.20 it has a MLT producer for blank. [1]
So now we have to provide a profile to our playlist producer; otherwise, synfig crashes with this error log message:
```
[mlt_producer 0x55555897c070] <playlist>
Playlist can not create blank producer without profile
```
Reported-by: Lae82 in Synfig Forums [2]
[1] https://www.mltframework.org/blog/v7.20.0_released/
[2] https://forums.synfig.org/t/setting-audio-delay-parameter-for-audio-layer-with-a-positive-value-crashes-synfig/16223
> fix: crash with positive sound delay for MLT >= 7.20

- synfig-core/src/synfig/layers/layer_bitmap.h
- synfig-studio/src/synfigapp/vectorizer/centerlinetostrokes.cpp
more should be done, but that's better than current situation
> refactor: reduce visibility of internal variable members of Layer_Bitmap

- synfig-studio/src/gui/trees/historytreestore.cpp
missing assignment to a variable after a mistake in commit b76be9e5e42018e1570aa73a1558b4db68edc398
> fix: History panel didn't show sub-actions anymore

- synfig-studio/src/gui/app.cpp
fixes : #3519
Previously, hitting the Enter key in the dialog did nothing. This update allows the Enter key to accept the user choice as if the "Add" button was clicked.
> feat(dialog): add Enter key support to accept user choice

- synfig-core/src/synfig/rendering/surface.cpp
- synfig-core/src/synfig/rendering/surface.h
- synfig-studio/src/synfigapp/canvasinterface.cpp
the main change is how we loop to detect consecutive duplicated images.
However, the idea is still the same:
1. create an animated valuenode to "layer_name" parameter of a (future) layer Switch
2. add each imported image to current canvas
3. check if it is duplicated (equal to previous image) 
3.1. If so, add it to a future remove layer action 
3.2. Otherwise add a new waypoint in the "layer_name" valuenode
4. delete the duplicated layers (if it is supposed to do so)
5. add an action to encapsulate the non-deleted import layers to a new switch layer
6. convert/link the layer_name parameter to the animated valuenode
> refactor: make code for importing image sequence more readable

- synfig-core/src/synfig/valuenodes/valuenode_blinecalctangent.cpp
- synfig-core/src/synfig/valuenodes/valuenode_blinecalcwidth.cpp
Commit https://github.com/synfig/synfig/commit/fddd3964ead305920ae2b0e6acc68b7b07268d77 introduced a bad connection error when spline tangent and spline width converters are applied to a real parameter of a layer.
Fixes  #3532
> fix: couldn't create converter to spline tangent or spline width (regression)

- synfig-studio/src/gui/main.cpp
> fix(ui): rectify wayland window icon

- synfig-studio/src/gui/widgets/widget_timetrack.cpp
When a group layer is selected, the time track will show waypoints for child layers in the group. Modifying one of these waypoints (remove, move, or duplicate) was also pulling in waypoints of sibling layers of the group, not just child layers, if the sibling also happened to have a waypoint at the same time.
Reproduction steps:
1. Create 2 circle layers, and animate the location of both circles so that both have waypoints on the same frame
2. Put one of the circles into a group layer
3. Select the group layer, and right click a waypoint in the time track. Note that it says "Remove 2 Waypoints", even though there's only one layer in the group
4. Select Remove. Both circle layers are modified, even though only one of them is in the selected group.
I'm still a bit fuzzy on the relationship …
> fix: modifying waypoints for a group layer no longer modifies sibling layers

- synfig-core/src/synfig/savecanvas.cpp
This PR fixes `Unable to resolve <val>` on project load by changing save file format to write the constant exported values first and then writing the non-constant ones.
By writing the constant value nodes first makes sure that the non-constant value nodes that depend on constant value nodes get resolved and hence the project file can be loaded without errors due to unresolved exported values.  
Fix #3538
> fix: Fix bug displaying "Unable to resolve <val>" on project load

- synfig-studio/images/CMakeLists.txt
- synfig-studio/images/Makefile.am
- synfig-studio/images/type_transformation_icon.sif
- synfig-studio/src/gui/iconcontroller.cpp
This PR adds a missing icon for type transformation.
There were several color variants you can check out here: https://forums.synfig.org/t/icon-for-transformation-type/16425
In the end, 3 people voted for colored version, so that's the one I am including here. Hope that's OK.
> fix(GUI): add missing icon for type transformation

- synfig-core/po/POTFILES.in
- synfig-core/src/synfig/valuenodes/CMakeLists.txt
- synfig-core/src/synfig/valuenodes/Makefile_insert
- synfig-core/src/synfig/valuenodes/valuenode_angle.cpp
- synfig-core/src/synfig/valuenodes/valuenode_angle.h
A new converter "Angle" that can be connected to "real" value types. Adds a sub parameter "Angle" of type "angle", so that the calculations mentioned here : https://github.com/synfig/synfig/issues/3528#issuecomment-2761450106 can be achieved.
Fix #3528
> feat: "Angle" converter for real -> angle conversions

- synfig-core/src/modules/mod_filter/halftone2.cpp
- synfig-core/src/modules/mod_filter/halftone3.cpp
- synfig-core/src/modules/mod_geometry/checkerboard.cpp
- synfig-core/src/modules/mod_gradient/lineargradient.cpp
- synfig-core/src/modules/mod_gradient/radialgradient.cpp
- synfig-core/src/synfig/rendering/software/task/taskpaintpixelsw.cpp
- synfig-core/src/synfig/rendering/software/task/taskpaintpixelsw.h
Let their names according to what they store/represent.
> refactor: rename pre_run() parameters of TaskPaintPixelSW and TaskFilterPixelSW and fix code style

- synfig-core/src/synfig/valuenodes/valuenode_bone.cpp
Reported by Coverity Scan CID 457155 and 457294
> refactor: make `debug` variable `const` in ValueNode_Bone

- synfig-core/src/modules/lyr_std/mandelbrot.cpp
- synfig-core/src/synfig/paramdesc.h
It isn't used - and exists since the first commit.
> refactor: remove the optional "group" property of layer parameters

- synfig-core/src/synfig/valuenodes/valuenode_angle.cpp
- synfig-core/src/synfig/valuenodes/valuenode_angle.h
ValueNode "Angle" name clashes with Value "Angle" (constant) name.
> fix: new ValueNode_Angle couldn't be loaded because of tag name clash

- synfig-core/src/modules/mod_geometry/advanced_outline.cpp
The incoming tangent was computed wrong (using the outgoing width)
Fix #3593
> fix(advanced outline layer): the outline on the last vertex of spline

- synfig-studio/src/gui/states/state_bline.cpp
Steps to reproduce:
1. Select the BLine Tool
2. Click on the Workarea to create the first vertex
3. Click on the Workarea twice to create two other vertices
4. Click on the first vertex (the green handle) and drag it
5. Click on the first vertex again
After step 5, a new (looped) spline is created.
However, user couldn't create a new spline after it without this fix.
Workaround:
* Press Esc after step 5
> fix(bline tool): couldn't create the spline right after user drags the first vertex

- synfig-core/src/modules/mod_geometry/advanced_outline.cpp
- synfig-core/src/synfig/rendering/primitive/bend.cpp
- synfig-core/src/synfig/rendering/primitive/bend.h
- synfig-core/src/synfig/valuenodes/valuenode_bline.cpp
- synfig-core/src/synfig/valuenodes/valuenode_blinecalcvertex.cpp
- synfig-core/test/bline.cpp
- synfig-core/test/test_base.h
- synfig-studio/test/test_base.h
Advanced outline allows user to set width along its path, not only in its vertices.
If a path has zero-length segments (possibly due to two consecutive vertices at same coordinates), the width points were placed in a wrong position.
Before:
Now:
This PR does other stuff for improving testing, and fixing some cases of single-vertex blines I found while investigating this issue.
Reported-by: Svarov in https://forums.synfig.org/t/sonic-model-wip/16286/4
> fix(advanced outline): fix rendering of width point in non-homogeneous position

- .github/ISSUE_TEMPLATE/bug-report--version-1-4.md
- .github/ISSUE_TEMPLATE/bug-report--version-1-5.md
- appveyor.yml
- version-bump.sh
And fix the missing changes that version_bump.sh script should do.
> chore: bump synfig versions for issue template & appveyor files

- synfig-core/src/modules/mod_svg/svg_parser.cpp
- synfig-core/src/modules/mod_svg/svg_parser.h
Drawing command 'c' or 's' following commands 'h' or 'v' didn't split tangents in the initial vertex of the curve.
Comparison between rendering on Inkscape, Synfig 1.5.3 and this PR:
Reported-in: https://forums.synfig.org/t/tangets-beeing-merged-when-importing-svg-filles/16714/
Reported-by: MGFP
> fix(SVG importer): tangents were merged if curve exists after straight line
