synfig-core/src/modules/mod_imagemagick/mptr_imagemagick.cpp
synfig-core/src/modules/mod_jpeg/mptr_jpeg.cpp
synfig-studio/src/gui/app.cpp

Should be tested under windowz os (especially  Fix #769 cause use of tmp file)!

Fix #767 (embed jpg) and #769 (embed svg) + several minor images things

---

synfig-core/src/tool/main.cpp

"Try 'synfig --help' for more information"

Fix 843 : On Cli Error, print how to invoke help

---

synfig-studio/src/synfigapp/actions/keyframeduplicate.cpp

* Fix keyframe waypoint::model on keyframe duplicate
* Fix keyframe active status on keyframe duplicate

Keyframe ui : Fix(s) on KeyframeDuplicate 

---

synfig-studio/src/gui/states/state_bline.cpp
synfig-studio/src/gui/states/state_circle.cpp
synfig-studio/src/gui/states/state_draw.cpp
synfig-studio/src/gui/states/state_gradient.cpp
synfig-studio/src/gui/states/state_lasso.cpp
synfig-studio/src/gui/states/state_polygon.cpp
synfig-studio/src/gui/states/state_rectangle.cpp
synfig-studio/src/gui/states/state_star.cpp
synfig-studio/src/gui/states/state_text.cpp

Better label in tooloption panel

---

synfig-studio/src/synfigapp/actions/valuedesclink.cpp

Thank's to Permutator for the tips

Fix 889 - Crash on linking regular vertice and width point center

---

synfig-core/src/synfig/distance.cpp
synfig-studio/src/gui/app.cpp
synfig-studio/src/gui/app.h
synfig-studio/src/gui/autorecover.cpp
synfig-studio/src/gui/autorecover.h
synfig-studio/src/gui/dialogs/dialog_setup.cpp
synfig-studio/src/gui/dialogs/dialog_setup.h
synfig-studio/src/gui/duck.h
synfig-studio/src/gui/states/state_brush.cpp
synfig-studio/src/gui/widgets/widget_filename.cpp
synfig-studio/src/gui/workarearenderer/renderer_ducks.cpp
synfig-studio/src/gui/workarearenderer/renderer_ducks.h
synfig-studio/src/synfigapp/settings.cpp
synfig-studio/src/synfigapp/settings.h

* tooltip displayed on transformation handle over (format selection from preference)
* new design of preference dialog based on yu redesign (http://www.synfig.org/forums/viewtopic.php?f=14&t=3648)
* handle tooltip option 
* multibrush path option
* enable/disable backup
see individal commits title/comment for more info

group handle tooltip & preference dialog redesign

---

synfig-studio/src/gui/dialogs/Makefile_insert
synfig-studio/src/gui/dialogs/dialog_setup.cpp
synfig-studio/src/gui/dialogs/dialog_setup.h
synfig-studio/src/gui/dialogs/dialog_template.cpp
synfig-studio/src/gui/dialogs/dialog_template.h
synfig-studio/src/template.h

Dialog design template (based on setup/preference redesign)
Abstract class to create in a generic way the synfig studio dialogs for ui consistency

dialog template

---

synfig-studio/src/gui/app.cpp

TODO : some StockID left in the DEFINE_ACTION menu declaration

fix936 currentfileversion +  	Gtk Deprecated + header cleanup

---

synfig-studio/src/gui/workarea.cpp

from [bob / windows](http://www.synfig.org/forums/viewtopic.php?f=15&t=9936&p=31046#p31045) !
> EDIT: My bad, everything works fine, all the guide work properly

fix 805 and 796 : guide rulers crash

---

synfig-core/src/modules/lyr_std/freetime.cpp
synfig-core/src/modules/lyr_std/stroboscope.cpp
synfig-core/src/modules/lyr_std/timeloop.cpp

I am also thinking it would be nice to put other stuff out of "Other" as well, but can't think of categorization for them atm.

Add "Time" layer category

---

synfig-studio/src/gui/dials/zoomdial.cpp
synfig-studio/src/gui/dials/zoomdial.h
synfig-studio/src/gui/workarea.cpp
synfig-studio/src/gui/workarea.h

Editable zoom level entry in zoom dial

---

synfig-core/src/modules/synfig_modules.cfg.in
synfig-core/src/synfig/main.cpp

Fix autotools module list and revert forcing default module loading.

Module loader

---

README.md

Howdy!
I just updated a url to use https instead of http
Thank you for your time! ^ _ ^

Updated URL to use https

---

synfig-studio/src/gui/widgets/widget_coloredit.cpp

Fix color wheel update issue on zero saturation

---

synfig-core/src/synfig/canvas.cpp
synfig-core/src/synfig/canvas.h
synfig-core/src/synfig/layer.cpp
synfig-core/src/synfig/layers/CMakeLists.txt
synfig-core/src/synfig/layers/Makefile_insert
synfig-core/src/synfig/layers/layer_filtergroup.cpp
synfig-core/src/synfig/layers/layer_filtergroup.h
synfig-core/src/synfig/layers/layer_pastecanvas.cpp
synfig-core/src/synfig/layers/layer_pastecanvas.h
synfig-core/src/synfig/target_scanline.cpp
synfig-core/src/synfig/target_tile.cpp
synfig-studio/src/gui/duckmatic.cpp
synfig-studio/src/gui/duckmatic.h
synfig-studio/src/gui/iconcontroller.cpp
synfig-studio/src/synfigapp/Makefile.am
synfig-studio/src/synfigapp/action.cpp
synfig-studio/src/synfigapp/actions/CMakeLists.txt
synfig-studio/src/synfigapp/actions/layerencapsulatefilter.cpp
synfig-studio/src/synfigapp/actions/layerencapsulatefilter.h

as requested here https://github.com/synfig/synfig/issues/462

Filter group

---

synfig-core/src/synfig/main.cpp
synfig-studio/src/gui/app.cpp
synfig-studio/src/synfigapp/actions/keyframeset.cpp

fixed some bugs

---

synfig-core/src/synfig/loadcanvas.cpp
synfig-studio/analyze-clang.sh
synfig-studio/analyze_cppcheck.sh
synfig-studio/src/gui/app.cpp
synfig-studio/src/gui/docks/dock_navigator.cpp
synfig-studio/src/gui/mainwindow.cpp
synfig-studio/src/gui/states/state_brush.cpp
synfig-studio/src/gui/states/state_eyedrop.cpp
synfig-studio/src/gui/states/state_fill.cpp
synfig-studio/src/gui/states/state_normal.cpp
synfig-studio/src/gui/states/state_text.cpp
synfig-studio/src/gui/workarea.cpp
synfig-studio/src/synfigapp/action.h
synfig-studio/src/synfigapp/actions/valuedescbonelink.cpp
synfig-studio/src/synfigapp/actions/valuedesccreatechildbone.cpp
synfig-studio/src/synfigapp/actions/valuedescskeletonlink.cpp

@morevnaproject Please check if nothing else broken.

Fixing bug #470 (Segfault on pressing Esc while using rotate tool)

---

synfig-studio/src/gui/app.cpp
synfig-studio/src/gui/app.h
synfig-studio/src/gui/dialogs/dialog_setup.cpp
synfig-studio/src/gui/dialogs/dialog_setup.h
synfig-studio/src/gui/render.cpp

GUI option - value persisted tested ok

648 - GUI option to enable/disable that function

---

synfig-studio/src/gui/app.cpp

Set enabled by default on restore default settings

Render done sound enabled by default on restore_default_settings

---

synfig-studio/src/gui/cellrenderer/cellrenderer_value.cpp
synfig-studio/src/gui/cellrenderer/cellrenderer_value.h
synfig-studio/src/gui/widgets/widget_canvastimeslider.cpp

https://github.com/synfig/synfig/issues/415 ;)
Parameters not accepting some values https://github.com/synfig/synfig/issues/659 https://github.com/synfig/synfig/issues/526 https://github.com/synfig/synfig/issues/520

Request 415: Stop playback on click on timeline + Fix 659/526/520

---

synfig-studio/src/gui/render.cpp

Now every-time the target changes filename will be updated with new .ext if required.

Fixed rename file extension when rendering based on 'target'

---

synfig-studio/src/brushlib/README

The earlier link - http://wiki.mypaint.info/Brushlib was expired so felt like updating it.

updated urls are included

---

synfig-studio/src/gui/canvasview.cpp

Hints for icons -Save and Save As added

---

autobuild/build.sh

Resolving Error #742 
Incompatibility with old FFmpeg

Fix building issues on Ubuntu

---

synfig-studio/src/gui/app.cpp

Fixes: #771 
@morevnaproject please review this when you have time [^_^]

Made image aspect checked by default

---

synfig-studio/src/gui/canvasview.cpp
synfig-studio/src/gui/canvasview.h
synfig-studio/src/gui/dials/framedial.cpp
synfig-studio/src/gui/dials/framedial.h
synfig-studio/src/gui/renddesc.cpp
synfig-studio/src/gui/renddesc.h

Hi @morevnaproject please review the changes

End_Time_Feature

---

synfig-studio/src/gui/app.cpp

Replaced spawn_command_line_sync() with spawn_command_line_async()
@morevnaproject please review :)

Use async call for "Edit image in external tool". Fixes #806

---

synfig-studio/src/gui/canvasview.cpp

fixes: #773 
@morevnaproject 
Please review and suggest if changes are required

fix ask for file when layer->new layer->other->sound/image is invoked

---

synfig-studio/src/gui/docks/dock_canvasspecific.cpp
synfig-studio/src/gui/docks/dock_canvasspecific.h
synfig-studio/src/gui/docks/dock_layers.cpp

and a private (not even protected) variable not used anywhere

remove some commented and unused code not touched since 2008

---

synfig-core/src/modules/mod_svg/svg_parser.cpp

Some Converity memory leak reports fixed

fix some memory leaks on svg parser

---

synfig-studio/src/gui/resourcehelper.cpp

They are installed in a different structure images are

fix ui file path for Windows

---

synfig-studio/plugins/lottie-exporter/layers/group.py
synfig-studio/src/synfigapp/vectorizer/centerlineskeletonizer.cpp

Please review as these commits change the source code

Fix source typos

---

1-setup-linux-native.sh

"which" replaced by built-in "command" command.
Updated Arch/Manjaro dependencies.

"which" replaced by built-in "command" command.

---

synfig-studio/src/gui/workarearenderer/renderer_timecode.cpp
synfig-studio/src/synfigapp/canvasinterface.cpp

They are not needed after 0589a7d commit

Remove redundant try/catch statements

---

.gitignore
synfig-studio/src/gui/canvasview.cpp
synfig-studio/src/gui/canvasview.h
synfig-studio/src/gui/dialogs/vectorizersettings.cpp
synfig-studio/src/gui/dialogs/vectorizersettings.h
synfig-studio/src/synfigapp/actions/vectorization.cpp
synfig-studio/src/synfigapp/actions/vectorization.h
synfig-studio/src/synfigapp/vectorizer/centerlinepolygonizer.cpp
synfig-studio/src/synfigapp/vectorizer/centerlineskeletonizer.cpp
synfig-studio/src/synfigapp/vectorizer/centerlinevectorizer.cpp
synfig-studio/src/synfigapp/vectorizer/centerlinevectorizer.h
synfig-studio/src/synfigapp/vectorizer/polygonizerclasses.h

The progress bar is added and works as expected.
@morevnaproject please have a look :)
This PR closes #854

Added: Progress bar for vectorization

---

1-setup-linux-native.sh

This needed to correct sound playback via MLT.
Details - https://github.com/synfig/synfig/issues/424#issuecomment-562862302

Linux build: Add libmlt-data package for Ubuntu-based distros

---

1-setup-linux-native.sh

Fixed some typos in the script

Fix some typos

---

synfig-core/configure.ac
synfig-studio/configure.ac

...because of https://github.com/morevnaproject/morevna-builds/issues/17

Remove AC_CONFIG_MACRO_DIRS

---

synfig-studio/src/synfigapp/actions/vectorization.cpp
synfig-studio/src/synfigapp/vectorizer/centerlinetostrokes.cpp

@morevnaproject please review the PR
closes: #923

Fixed incorrect location and scaling when image TL and BR manipulated

---

ETL/ETL/_smach.h
synfig-core/src/synfig/importer.cpp
synfig-core/src/synfig/target_cairo.cpp

try-catch shall use reference not value

---

synfig-core/src/synfig/rendering/renderqueue.cpp
synfig-core/src/synfig/rendering/renderqueue.h

deprecated Glib::Threads::Mutex and Cond

RenderQueue: prefer std::mutex and std::condition_variable

---

synfig-core/src/synfig/rendering/task.cpp
synfig-core/src/synfig/rendering/task.h

deprecated Glib::Threads::Mutex and Cond

Task: prefer std::mutex and std::condition_variable

---

synfig-studio/src/gui/states/state_bline.cpp

and not just with Return key (PR #1007)

finish Spline with Numpad Enter key too

---

ETL/ETL/_stringf.h
synfig-core/src/synfig/loadcanvas.cpp

Closing the file did not delete the canvas

---

ETL/test/smart_ptr.cpp

remove test for (removed) etl::loose_smart_ptr

---

synfig-studio/src/gui/canvasview.cpp

Fix typo in Import Sequence dialog

Fix typo in Import Sequence dialog

---

synfig-studio/src/gui/canvasview.cpp
synfig-studio/src/synfigapp/actions/canvasremove.cpp
synfig-studio/src/synfigapp/actions/layerembed.cpp

Fixed some typos found during the translation process.

Fix some ui typos

---

synfig-core/configure.ac

Yes, I know there's an (almost done) effort to deprecate autotools in favor of cmake, but…

Update autotools files 2

---

synfig-core/src/synfig/layers/layer_switch.cpp
synfig-core/src/synfig/target_cairo.cpp
synfig-core/src/synfig/target_cairo_tile.cpp
synfig-core/src/synfig/target_scanline.cpp
synfig-core/src/synfig/target_tile.cpp
synfig-core/src/synfig/valuenodes/valuenode_bone.cpp
synfig-studio/src/gui/dialogs/dialog_setup.cpp
synfig-studio/src/gui/renddesc.cpp
synfig-studio/src/gui/states/state_bline.cpp
synfig-studio/src/gui/states/state_circle.cpp
synfig-studio/src/gui/states/state_draw.cpp
synfig-studio/src/gui/states/state_polygon.cpp
synfig-studio/src/gui/states/state_rectangle.cpp
synfig-studio/src/gui/states/state_star.cpp
synfig-studio/src/synfigapp/actions/layerencapsulateswitch.cpp

Includes typos and fix of non-translatable strings.

Fix some typos and some non translatable strings

---

ETL/LICENSE
ETL/README
LICENSE
synfig-core/LICENSE
synfig-core/README
synfig-studio/LICENSE
synfig-studio/README

Add a separate LICENSE file. Closes #1111.

---

synfig-studio/src/gui/widgets/widget_waypoint.cpp
synfig-studio/src/gui/widgets/widget_waypoint.h

Here's how the improved waypoint dialog works
Fixes #1178 
Fixes #1189

Improved dialog waypoint UX

---

synfig-studio/src/gui/docks/dockdialog.cpp

get away, ghost dockers

---

.travis.yml
autobuild/lottie_test.sh
lottie_test.sh

Resolves: #989 
- The job is currently allowed to fail because there are around 6 tests that are failing.
One doubt:
- Where should I place the script `lottie_test.sh`? Currently, it is inside the root directory, but I suppose this is not the right place for it.

Automate Lottie exporter tests using Travis

---

synfig-studio/plugins/lottie-exporter/layers/group.py

@ice0 I have added some important comments in `python` file.
Please have a look.

[Lottie exporter] Important comments regarding effects/fill.py

---

synfig-core/src/modules/CMakeLists.txt
synfig-studio/ui/CMakeLists.txt

[CMake] Update CMake script for /share and /etc.

---

.travis.yml
autobuild/transifex-push-translations.sh

Fixes: #1150 
I was facing some merge conflict in #1223, and hence I created this new PR.
@ice0 please review ^_^

New job for running "autobuild/transifex-push-template.sh"

---

synfig-studio/src/gui/dialogs/about.cpp

This is regarding issue no #1205 
- change year 2019 to 2020

Year is fixed in About dialog

---

synfig-studio/src/gui/app.cpp

It's obvious that we'd better to change name for settings file.

Bump version for settings file

---

synfig-studio/plugins/lottie-exporter/common/Param.py
synfig-studio/plugins/lottie-exporter/settings.py

Added sine convert method for Lottie Exporter plugin.
@AnishGG , @ice0 , please review :smiley: .

[Lottie Exporter] Add support for Sine convert method

---

synfig-studio/src/gui/CMakeLists.txt
synfig-studio/src/gui/resourcehelper.cpp

Updated imagepath in case SYNFIG_ROOT is undefined.

---

1-setup-linux-native.sh

Fixes #1231 
Change the order of the Package Managers for Linux system to avoid ambiguities with apt-get

Fix issue #1231

---

synfig-studio/src/gui/canvasview.cpp
synfig-studio/src/gui/iconcontroller.cpp
synfig-studio/src/gui/instance.cpp

Fixes #1216 
Consistent order of Waypoint types: Clamped, TCB, Constant, Ease, Linear

Fix issue #1216

---

synfig-studio/src/gui/app.cpp
synfig-studio/src/gui/dialogs/dialog_setup.cpp

Update App::restore_default_settings() to reset all settings.

---

synfig-studio/plugins/lottie-exporter/common/Param.py
synfig-studio/plugins/lottie-exporter/common/misc.py
synfig-studio/plugins/lottie-exporter/settings.py
synfig-studio/plugins/lottie-exporter/shapes/circle.py

Added cos convert method for Lottie Exporter plugin.
@AnishGG , @ice0 , please review :smiley: .

[Lottie Exporter] Add support for Cos convert and Integer convert method

---

1-setup-linux-native.sh

Use /etc/os-release to detect OS

---

synfig-core/src/modules/lyr_std/shade.cpp

if Layer_Shade has no sublayers, it shouldn't try to render

---

synfig-core/src/synfig/loadcanvas.cpp

Fix new width list order for old versions

---

synfig-studio/src/gui/states/state_rectangle.cpp
synfig-studio/src/gui/states/state_star.cpp

Coverity Report ID: 308984 and 308974
and minor fix for some number typing

fix memory leaks

---

synfig-core/src/synfig/blur.cpp

Coverity Report ID: 308890, 308875, 308868, 308866, 308837, 308830, 308823,  308805

fix memory leaks for blur

---

synfig-studio/src/gui/widgets/widget_waypoint.cpp
synfig-studio/src/gui/widgets/widget_waypoint.h

Remove useless variable

---

.travis.yml
autobuild/translations-validation.sh

Fixes: #1250 
@ice0 is this what we need? Please review this
This is how it ran on the current branch(validation fails): https://travis-ci.com/github/AnishGG/synfig/builds/155064868

Job for translations validation

---

synfig-studio/src/synfigapp/actions/layercopy.cpp

Single Copy Layer visible for Bitmap layers only

---

synfig-core/src/synfig/blur.cpp

more memory leaks on blur

---

synfig-core/src/synfig/color/cairocolor.h

fix uninitialized variable

---

synfig-studio/src/gui/asyncrenderer.cpp

Fixed current_rendered_frames_count assignment

---

synfig-core/src/synfig/cairoimporter.cpp
synfig-core/src/synfig/cairoimporter.h

I really thought I sent a PR with this context before o.O

Remove unused cairoimporter method

---

synfig-studio/src/gui/canvasview.cpp
synfig-studio/src/gui/trees/layertree.cpp
synfig-studio/src/gui/trees/layertree.h
synfig-studio/src/gui/widgets/widget_value.cpp

As asked in https://github.com/synfig/synfig/pull/1325#issuecomment-612431772

Single click for parameter editing

---

synfig-studio/src/gui/cellrenderer/cellrenderer_value.cpp
synfig-studio/src/gui/widgets/widget_value.cpp
synfig-studio/src/gui/widgets/widget_value.h

canvas, bone & sublayer parameters now pops up in one single click

---

synfig-core/src/modules/mod_png/trgt_png_spritesheet.cpp
synfig-core/src/modules/mod_png/trgt_png_spritesheet.h
synfig-core/src/synfig/target_multi.cpp
synfig-core/src/synfig/target_multi.h
synfig-core/src/synfig/target_scanline.cpp
synfig-core/src/synfig/target_scanline.h
synfig-studio/src/gui/CMakeLists.txt
synfig-studio/src/gui/Makefile.am
synfig-studio/src/gui/asyncrenderer.cpp
synfig-studio/src/gui/asyncrenderer.h
synfig-studio/src/gui/progresslogger.cpp
synfig-studio/src/gui/progresslogger.h
synfig-studio/src/gui/render.cpp
synfig-studio/src/gui/render.h
synfig-studio/src/synfigapp/instance.cpp

Avoid crash on pngspritesheet exporting

---

synfig-studio/src/gui/dialogs/about.cpp

Closes: #1214 
@morevnaproject, please review and suggest if any changes required.

added vectorizer feature credits to about dialog.

---

synfig-studio/src/gui/workarea.cpp
synfig-studio/src/gui/workarea.h

And remove unused #include for WorkArea

Workarea: replace deprecated Gtk::Table

---

synfig-core/src/modules/mod_png/mptr_png.cpp

fix endianess of 16-bit PNG importing

---

synfig-core/src/synfig/valuenodes/valuenode_radialcomposite.cpp

fix readable name of Alpha parameter of Radial Composite valuenode

---

synfig-studio/src/gui/app.cpp
synfig-studio/src/gui/app.h
synfig-studio/src/gui/canvasview.cpp
synfig-studio/src/gui/canvasview.h
synfig-studio/src/gui/mainwindow.cpp
synfig-studio/src/gui/mainwindow.h

This PR is regarding issue no #733. Now  "View" -> "Toolbar" menu item is active.

Toolbar menu

---

synfig-core/src/synfig/loadcanvas.cpp

Don't show multiple warning messages about old canvas. Closes #1380.

---

synfig-studio/src/player/main.cpp
synfig-studio/src/player/visualizationwindow.cpp
synfig-studio/src/player/visualizationwindow.h

This is a PR for the issue #1215 .
I'm not sure if this is what @morevnaproject meant there. Can someone see this and let me know?
TODO: Still need to give a command line parameter for choosing.

Add option to playback animation in realtime

---

synfig-core/src/modules/lyr_freetype/lyr_freetype.cpp

 fix 'font not found' in freetype layers - fix #1407

---

synfig-studio/src/gui/widgets/widget_curves.cpp

fix time and delta values in tooltip while dragging in Graph panel

---

synfig-studio/src/gui/widgets/widget_timetrack.cpp

If zero waypoints is selected in Timetrack and user presses Delete key,
an error message popped up as synfigapp::Action is not ready (not enough parameters).

don't try to delete/move/copy zero waypoints

---

synfig-core/src/synfig/valuenodes/valuenode_bline.cpp

Fixes glitching widthpoints. Closes #1401.

---

synfig-studio/plugins/lottie-exporter/common/Param.py
synfig-studio/plugins/lottie-exporter/settings.py

Added [aTan2](https://wiki.synfig.org/Convert#aTan2) convert method for Lottie Exporter plugin.
@AnishGG , @ice0 , please review :smiley: 
Note: aTan2 convert method works with angle-valued parameters.

[Lottie Exporter] Add support for aTan2 convert method

---

synfig-core/src/modules/mod_noise/distort.cpp

Animation Speed of Noise Distort Layer set to static by default

---

synfig-studio/build_tools/autorevision.sh

REVISION_ID with 7 characters instead of 6

---

synfig-studio/plugins/lottie-exporter/common/Makefile.am
synfig-studio/plugins/lottie-exporter/common/Param.py
synfig-studio/plugins/lottie-exporter/settings.py
synfig-studio/plugins/lottie-exporter/shapes/Makefile.am
synfig-studio/plugins/lottie-exporter/synfig/Makefile.am

@AnishGG I have separated the Vector Angle convert method from the aTan2 convert method PR.
Please review it.

[Lottie Exporter] Add support for Vector Angle convert method

---

synfig-core/po/POTFILES.in
synfig-studio/po/POTFILES.in

it was not updated and make "make check" fail

fix POTFILES.in

---

synfig-core/src/synfig/valuenodes/valuenode_bline.cpp

Fix incorrect position of Widthpoints on Homogenous Advanced Outline

---

autobuild/lottie_test.sh

This PR changes the Lottie automation testing script according to this proposal: https://gitlab.com/synfig/synfig-tests/-/issues/27
Both this PR and https://gitlab.com/synfig/synfig-tests/-/merge_requests/31, combined will result in the passing of the current Lottie tests.
@morevnaproject please have a look. ^__^

Update lottie test script

---

synfig-core/test/Makefile.am
synfig-core/test/bline.cpp

add test for conversion homogeneous-standard widthpoints & loop

---

synfig-studio/images/CMakeLists.txt

build_images target's rebuilding behavior

---

synfig-studio/src/gui/resourcehelper.cpp

Fixes the issue in CMake build where app resource path is incorrect.

Resource management of CMake build.

---

synfig-studio/src/gui/instance.cpp
synfig-studio/src/gui/render.cpp
synfig-studio/src/gui/render.h

Check if target output has same name as existing files

---

synfig-core/src/synfig/loadcanvas.cpp
synfig-studio/src/gui/app.cpp

Use ScrolledWindow and label wrapping for message dialog

---

synfig-core/src/synfig/rendering/renderer.cpp
synfig-core/src/synfig/rendering/software/function/resample.cpp

> MSVC is not a C99 compiler, and does not support variable length arrays.
> At https://docs.microsoft.com/en-us/cpp/c-language/ansi-conformance MSVC is documented as conforming to C90.
Performance check code:
```
#include <cstdlib>
#include <vector>
#include <iostream>
#include <string>
#include <boost/date_time/posix_time/ptime.hpp>
#include <boost/date_time/microsec_time_clock.hpp>
class TestTimer
{
public:
TestTimer(const std::string & name) : name(name),
start(boost::date_time::microsec_clock<boost::posix_time::ptime>::local_time())
{
}
~TestTimer()
{
using namespace std;
using namespace boost;
posix_time::ptime now(date_time::microsec_clock<posix_time::ptime>::local_time());
posix_time::time_duration d = now - start;
cout << name << " completed in " << d.total_milliseconds() / …
```

Variable length array (VLA) replaced by std::vector class (fixes MSVC compilation)

---

CMakeLists.txt
cmake/Modules/SynfigFindGit.cmake
synfig-core/src/CMakeLists.txt
synfig-studio/images/CMakeLists.txt
synfig-studio/images/splash_screen_development.sh
synfig-studio/images/splash_screen_development.sif.in
synfig-studio/src/gui/CMakeLists.txt

Different CMake builds based on CMAKE_BUILD_TYPE.

---

synfig-core/src/synfig/threadpool.cpp
synfig-core/src/synfig/threadpool.h

deprecated Glib::Threads::Mutex and Cond

ThreadPool: prefer std::mutex and std::condition_variable

---

synfig-core/src/synfig/module.cpp
synfig-core/src/synfig/module.h
synfig-core/src/synfig/rendering/software/function/resample.cpp
synfig-core/src/synfig/version.h

and add module path specific to particular user in Windows and OSX too

Cleanup module.cpp a bit

---

synfig-core/src/modules/mod_geometry/advanced_outline.cpp

#1480 
But please test it... I'm tired lol
The cuspids are still sometimes ugly…
I didn't check unlooped splines or splines with 1 or more than 2 width points.

Try to fix adv outline rendering

---

synfig-studio/src/gui/exception_guard.h

and fix the documentation line for SYNFIG_EXCEPTION_GUARD_END_NO_RETURN()

improve documentation of exception_guard.h

---

1-setup-windows-msys2.sh
2-build-msys-cmake.sh
CMakeLists.txt
appveyor.yml
autobuild/msys2/appveyor.bat
autobuild/msys2/build_mlt.sh
cmake/InstallMSYS2.cmake
cmake/SynfigGettext.cmake
cmake/SynfigIntltool.cmake
synfig-core/src/CMakeLists.txt
synfig-studio/CMakeLists.txt
synfig-studio/plugins/CMakeLists.txt
synfig-studio/plugins/add-skeleton-simple/CMakeLists.txt
synfig-studio/plugins/lottie-exporter/CMakeLists.txt
synfig-studio/plugins/view-unhide-all-layers/CMakeLists.txt

Changes related to moving appveyor builds to CMake and ninja. 
Also #1488

Changes for appveyor build using CMake and ninja.

---

appveyor.yml
cmake/InstallMSYS2.cmake

Fixed Magick NoEncodeDelegateForThisImageFormat issues on appveyor build.

---

synfig-studio/plugins/lottie-exporter/common/Param.py
synfig-studio/plugins/lottie-exporter/settings.py

Added support for Dot Product convert method. Tested and works for me.
@AnishGG please review ^__^

[Lottie Exporter] Add support for dot product convert method

---

autobuild/build.sh

They currently don't support imagemagick

fix OSX High Sierra, Mojave and Catalina build

---

synfig-core/src/modules/mod_geometry/advanced_outline.cpp

fix dashed outline behavior in non homogeous outline

---

synfig-studio/src/gui/states/state_bone.cpp
synfig-studio/src/gui/workarea.cpp
synfig-studio/src/gui/workarea.h
synfig-studio/src/gui/workarearenderer/renderer_ducks.cpp

Skeleton Tool : Fixed Active Bone  rendering

---

synfig-studio/src/gui/states/state_bone.cpp

[Skeleton Tool] Skeleton Deformation Layer should be created as "disabled"

---

synfig-studio/plugins/lottie-exporter/common/Param.py
synfig-studio/plugins/lottie-exporter/settings.py

Added support for Logarithm convert method.
@AnishGG , please review ^__^

[Lottie Exporter] Add support for Logarithm convert method

---

synfig-studio/src/gui/asyncrenderer.cpp
synfig-studio/src/gui/asyncrenderer.h
synfig-studio/src/gui/docks/dock_info.cpp
synfig-studio/src/gui/docks/dock_info.h
synfig-studio/src/gui/render.cpp

Add button to stop rendering process

---

synfig-studio/src/gui/states/state_bone.cpp
synfig-studio/src/synfigapp/actions/valuedesccreatechildbone.cpp

Skeleton Tool : Fixed Deformation layer Highlighting

---

synfig-studio/src/gui/states/state_bone.cpp

[Skeleton Tool] Trigger visibility of Width Points depending on conditions

---

1-setup-windows-msys2.sh
autobuild/msys2/build_mlt.sh
synfig-core/src/modules/mod_ffmpeg/trgt_ffmpeg.cpp
synfig-core/src/modules/mod_ffmpeg/trgt_ffmpeg.h
synfig-core/src/synfig/soundprocessor.cpp
synfig-core/src/synfig/soundprocessor.h

Now sound is exported too when user renders to mp4/avi (ffmpeg target).

Export video files with sound

---

synfig-studio/src/gui/states/state_bone.cpp
synfig-studio/src/gui/workarea.cpp
synfig-studio/src/synfigapp/actions/valuedesccreatechildbone.cpp
synfig-studio/src/synfigapp/actions/valuenodesetactivebone.cpp

Issue #1535  
This is the current state. I'm sure I was  unable to do this much before. I just need to add a grouper here. 
I also closed some edge cases here.

[Skeleton Tool] Creating new Skeleton layer without a bone

---

synfig-studio/src/gui/states/state_bone.cpp

Skeleton tool : Conditional disable/enable of Deformation layer on tool switch

---

.vscode/c_cpp_properties.json
.vscode/launch.json
.vscode/settings.json

For MSYS2 environment.
Debugger working (path mapping configured).

Configuration for Visual Studio Code on Windows

---

synfig-studio/src/gui/app.cpp
synfig-studio/src/gui/app.h
synfig-studio/src/gui/dialogs/dialog_setup.cpp
synfig-studio/src/gui/dialogs/dialog_setup.h

Add "Scale to fit canvas" button to Import dialog

---

synfig-studio/src/gui/states/state_bone.cpp

[Skeleton Tool] Active bone not set for Skeleton Deformation

---

synfig-studio/src/synfigapp/actions/valuedesccreatechildbone.cpp

[Skeleton Tool] Remove "Create Child Bone" action menu

---

synfig-studio/src/synfigapp/actions/valuedescbonesetparent.cpp

[Skeleton Tool] Crash when calling "Make Parent To Active Bone"

---

synfig-studio/src/synfigapp/actions/valuedescbonesetparent.cpp

[Skeleton Tool] Rename "Make Parent To Active Bone"

---

synfig-studio/src/gui/states/state_bone.cpp

[Skeleton Tool] Synfig crashes when we try to edit any other duck other than a bone's

---

synfig-studio/src/gui/app.cpp

Dialog windows now return true only if button with id=1 (accept) is clicked

---

synfig-studio/plugins/lottie-exporter/layers/shape_solid.py
synfig-studio/plugins/lottie-exporter/synfig/animation.py

@AnishGG , added support for `not` convert method. 
Will run some tests and make changes accordingly.

[Lottie Exporter] Add support for not convert method

---

synfig-studio/src/gui/states/state_bone.cpp

[Skeleton Tool] Crash when switching to Skeleton Tool 

---

synfig-studio/src/gui/states/state_bone.cpp
synfig-studio/src/synfigapp/actions/valuedesccreatechildbone.cpp

[Skeleton Tool] Can't load saved file that has layers made with skeleton tool

---

synfig-studio/src/gui/trees/layertree.cpp

Order column values using label value of the parameter

---

synfig-studio/src/gui/states/state_bline.cpp
synfig-studio/src/gui/states/state_circle.cpp
synfig-studio/src/gui/states/state_gradient.cpp
synfig-studio/src/gui/states/state_polygon.cpp
synfig-studio/src/gui/states/state_rectangle.cpp
synfig-studio/src/gui/states/state_star.cpp
synfig-studio/src/gui/states/state_text.cpp

Don't hold layers selection when creating a new layer

---

synfig-studio/src/gui/states/state_bone.cpp

[Skeleton Tool] Crash when editing control point

---

synfig-studio/src/gui/states/state_bone.cpp
synfig-studio/src/gui/widgets/widget_soundwave.cpp
synfig-studio/src/synfigapp/actions/vectorization.cpp

I saw some more warning messages (as you had said), will try to fix them as well. But I will study this project first :)

Fixed GCC warnings (different signedness comparison)

---

synfig-studio/src/synfigapp/vectorizer/centerlineskeletonizer.cpp

This should close the issue #1756 .
Thanks :)

Fix GCC multi-line comment warning (-wcomment)

---

synfig-studio/src/gui/dials/jackdial.h

Changed FrameDial => JackDial in comment

Fixed wrong documented comment (FrameDial=>JackDial)

---

synfig-core/src/synfig/CMakeLists.txt
synfig-studio/src/gui/CMakeLists.txt

Please let me know if there is a better approach to fix :smiley:
Fixes #1730

[CMake] Fixed incomplete information in About dialog

---

synfig-studio/src/gui/duckmatic.cpp

Fix #1755 
This is a huge change :sweat_smile:
I have made sure there is no `-Wmisleading-indentation` warning from this file.

Fix whitespace indentation

---

synfig-studio/src/gui/canvasview.cpp
synfig-studio/src/gui/canvasview.h

Replaced gtk::HBox and gtk::VBox with gtk::Grid in synfig-studio CanvasVeiw

---

synfig-studio/src/gui/workarea.cpp

Resolve misleading indentation warning

---

ETL/ETL/_rect.h
synfig-core/src/synfig/base_types.h
synfig-core/src/synfig/canvasfilenaming.cpp
synfig-core/src/synfig/canvasfilenaming.h
synfig-core/src/synfig/paramdesc.cpp
synfig-core/src/synfig/paramdesc.h
synfig-core/src/synfig/rendering/common/task/tasktransformation.cpp
synfig-core/src/synfig/rendering/common/task/tasktransformation.h
synfig-core/src/synfig/rendering/software/surfacesw.h
synfig-core/src/synfig/rendering/task.cpp
synfig-core/src/synfig/rendering/task.h
synfig-core/src/synfig/synfig_export.h
synfig-core/src/synfig/type.cpp
synfig-core/src/synfig/type.h
synfig-studio/src/synfigapp/cvs.cpp

Continuing to fix MSVC build errors

MSVC build improvements

---

CMakeLists.txt
synfig-core/src/modules/CMakeLists.txt
synfig-core/src/synfig/rendering/software/function/resample.cpp
synfig-core/src/synfig/soundprocessor.cpp
synfig-core/src/tool/joblistprocessor.cpp
synfig-studio/CMakeLists.txt
synfig-studio/src/gui/CMakeLists.txt
synfig-studio/src/gui/app.cpp
synfig-studio/src/gui/docks/dockdialog.cpp
synfig-studio/src/gui/exception_guard.h
synfig-studio/src/gui/render.cpp
synfig-studio/src/gui/widgets/widget_soundwave.cpp
synfig-studio/src/gui/widgets/widget_timetrack.cpp

Continuing to fix MSVC build errors (Still)

MSVC build improvements #2

---

CMakeLists.txt
synfig-studio/src/gui/CMakeLists.txt
synfig-studio/src/gui/app.cpp
synfig-studio/src/gui/app.h
synfig-studio/src/gui/dials/framedial.cpp
synfig-studio/src/gui/dials/framedial.h
synfig-studio/src/gui/mainwindow.cpp
synfig-studio/ui/CMakeLists.txt
synfig-studio/ui/Makefile.am
synfig-studio/ui/shortcuts_window.glade

New window for quick keyboard shortcut reference
Fixes #1733

Implemented Gtk::ShortcutsWindow and improved navigation keyboard shortcuts

---

autobuild/msys2/build_mlt.sh

[Windows/MLT] Disabled lumas module. Greatly reduces installer size.

---

synfig-studio/src/gui/states/state_bone.cpp
synfig-studio/src/synfigapp/actions/valuedesccreatechildbone.cpp

[Skeleton Tool] Console warning when adding bone with a parent

---

synfig-studio/src/gui/states/state_draw.cpp

Don't hold layer selection for Draw Tool

---

synfig-studio/src/gui/resources/css/synfig.css
synfig-studio/src/gui/widgets/widget_coloredit.cpp
synfig-studio/src/gui/widgets/widget_coloredit.h
synfig-studio/src/gui/widgets/widget_defaults.cpp
synfig-studio/src/gui/widgets/widget_defaults.h
synfig-studio/src/gui/widgets/widget_enum.cpp
synfig-studio/src/gui/widgets/widget_value.cpp
synfig-studio/src/gui/widgets/widget_waypoint.cpp
synfig-studio/src/gui/widgets/widget_waypoint.h

Closes #1787
Also improved color edit widget UI:
- 
-

Migrate old containers from widget classes to new containers

---

synfig-core/src/modules/lyr_freetype/lyr_freetype.cpp

fix regression: text layer accepts font filename again

---

synfig-core/src/synfig/context.cpp
synfig-core/src/synfig/context.h
synfig-core/src/synfig/layers/layer_duplicate.cpp

fix Duplicate layer ignoring all layers but the first one

---

synfig-core/src/tool/optionsprocessor.cpp
synfig-core/src/tool/optionsprocessor.h

- Fixed incorrect FPS output
- Code cleanup

OptionsProcessor small cleanup

---

ETL/NEWS
synfig-core/NEWS
synfig-studio/NEWS

This is a commit from 1.4.x branch. ^__^

Update NEWS files for version 1.4.0

---

synfig-studio/src/gui/app.cpp

@ice0 This is the PR for the issue #1794 and in this i almost fixed every keyboard shortcut which i could with inkscape except few which i couldn't find or couldn't understand like mirror vertical and mirror horizontal. they must be named as something else. Kindly tell me that and I will fix that also. or you can check these changes first and fully merge them into code base  then we will move to the ones which were left. Your Call :)
Kindly review this PR . Thank You

Improving Keyboard Shortcuts for the toolbox items

---

synfig-studio/src/gui/workarearenderer/renderer_canvas.cpp

Limit background rendering to playback bounds

---

synfig-studio/src/gui/app.cpp
synfig-studio/src/gui/canvasview.cpp
synfig-studio/ui/shortcuts_window.glade

@ice0 @Keyikedalube This is the PR for the issue #1798 Kindly review this PR. I have also updated the Keyboard Shortcuts UI .glade file as per the changes I made. 
Thank You :+1:

Implementing Canvas Zoom Legacy Keyboard shortcuts

---

synfig-core/src/modules/lyr_freetype/lyr_freetype.cpp

finally (and really) closes #1766

fix regression: didn't load font with relative path

---

.travis.yml

https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing

[CI] Disabled macOS builds on Travis-CI

---

synfig-studio/src/gui/states/state_eyedrop.cpp

[Synfig Studio] Eyedropper tool: Added ability to select fill color using Ctrl+click

---

synfig-studio/src/gui/actionmanagers/groupactionmanager.cpp
synfig-studio/src/gui/actionmanagers/groupactionmanager.h
synfig-studio/src/gui/actionmanagers/keyframeactionmanager.cpp
synfig-studio/src/gui/actionmanagers/keyframeactionmanager.h
synfig-studio/src/gui/actionmanagers/layeractionmanager.cpp
synfig-studio/src/gui/actionmanagers/layeractionmanager.h
synfig-studio/src/gui/cellrenderer/cellrenderer_gradient.cpp
synfig-studio/src/gui/cellrenderer/cellrenderer_gradient.h
synfig-studio/src/gui/cellrenderer/cellrenderer_time.cpp
synfig-studio/src/gui/cellrenderer/cellrenderer_time.h
synfig-studio/src/gui/cellrenderer/cellrenderer_timetrack.cpp
synfig-studio/src/gui/cellrenderer/cellrenderer_timetrack.h
synfig-studio/src/gui/cellrenderer/cellrenderer_value.cpp
synfig-studio/src/gui/cellrenderer/cellrenderer_value.h
synfig-studio/src/gui/helpers.cpp
synfig-studio/src/gui/instance.cpp
synfig-studio/src/gui/instance.h

and a bit of #include reordering

[Synfig Studio] Removed unused headers

---

synfig-studio/src/gui/app.cpp
synfig-studio/src/gui/app.h
synfig-studio/src/gui/instance.cpp

[Synfig Studio] Added ability to select available Sets when adding Layers to Sets

---

cmake/InstallMSYS2.cmake
synfig-studio/src/gui/app.cpp

Fix https://github.com/synfig/synfig/issues/1909
@morevnaproject need to add `gspawn-win??-helper.exe` and `gspawn-win??-helper-console.exe` to builder.

[Synfig Studio/Windows] Fixed non-working command "Edit image editing in external tool..."

---

synfig-studio/src/gui/instance.cpp

[Synfig Studio] Fixed crash when right-clicking on group in the Sets panel

---

synfig-core/src/synfig/listimporter.cpp
synfig-core/src/synfig/listimporter.h

Fix https://github.com/synfig/synfig/issues/1898

[Synfig Studio] Fixed incorrect import of `lst` files when path contains non-Latin characters

---

synfig-studio/src/gui/states/state_eyedrop.cpp

[Synfig Studio] Add Eyedrop Tool legend in Toolbox

---

synfig-studio/src/gui/app.cpp

left by mistake by a4720773c9aeb35b31804166e32e6e4035d16866

[Synfig Studio] minor cleanup

---

synfig-studio/src/gui/widgets/widget_time.cpp

[Synfig Studio] Widget_Time scroll step size set to 1 or 10 with Ctrl modifier

---

synfig-studio/src/gui/dialogs/dialog_waypoint.cpp
synfig-studio/src/gui/widgets/widget_waypoint.cpp
synfig-studio/src/gui/widgets/widget_waypoint.h

[Synfig Studio] Waypoint Editor didn't properly support enums

---

synfig-studio/src/gui/docks/dockmanager.cpp

Synfig Studio restores the last position and size of Main Window
on launching.
If user had multiple monitors when closing Synfig last time he used it,
Main Window could be moved to a no-more existent monitor/area
and not be visible.
Some Window Managers (like on MS Windows case) does not prevents
opening a window on a invisible area.
On MS Windows, closing Synfig Studio app in a minified state
moves the window to position (-32000,-32000).
fix #1871

[Synfig Studio] fix mainwindow not showing when is offscreen

---

synfig-studio/po/POTFILES.in
synfig-studio/src/synfigapp/Makefile.am

In order to `make check` properly work

autotools: fix POTFILES.in again and Makefile.am

---

synfig-core/src/modules/mod_ffmpeg/trgt_ffmpeg.cpp
synfig-core/src/tool/joblistprocessor.cpp
synfig-studio/src/gui/render.cpp

Linked issue: https://github.com/synfig/synfig/issues/1885

[Synfig Studio/Windows] Fixed issue with rendering to file when using non-Latin filenames

---

synfig-core/src/synfig/loadcanvas.cpp
synfig-core/src/synfig/valuenodes/valuenode_average.cpp
synfig-core/src/synfig/valuenodes/valuenode_average.h

Linked issue: https://github.com/synfig/synfig/issues/402
Test file: [average.zip](https://github.com/synfig/synfig/files/5744310/average.zip)

[Synfig Core] Added support for loading `average` values

---

synfig-core/src/synfig/loadcanvas.cpp

Based on top of this PR (https://github.com/synfig/synfig/pull/1955)

[Core] A little refactoring of loadcanvas.cpp

---

synfig-studio/src/gui/selectdraghelper.h
synfig-studio/src/gui/widgets/widget_curves.cpp
synfig-studio/src/gui/widgets/widget_soundwave.cpp
synfig-studio/src/gui/widgets/widget_timegraphbase.cpp
synfig-studio/src/gui/widgets/widget_timegraphbase.h
synfig-studio/src/gui/widgets/widget_timetrack.cpp

[Synfig Studio] Implement Ctrl+Shift+Scroll to zoom horizontally in panels

---

synfig-studio/src/synfigapp/actions/valuedescblinelink.cpp

[Synfig Studio] fix "Link to Spline" showing when a vertex of spline itself is selected

---

synfig-core/src/modules/lyr_freetype/lyr_freetype.cpp
synfig-studio/src/gui/widgets/widget_fontfamily.cpp
synfig-studio/src/gui/widgets/widget_fontfamily.h

Fix https://github.com/synfig/synfig/issues/1873

[Core/Studio] Added support for user-installed fonts on Windows 10 (1809)

---

synfig-studio/src/gui/instance.cpp
synfig-studio/src/synfigapp/actions/blinepointtangentmerge.cpp
synfig-studio/src/synfigapp/actions/blinepointtangentmerge.h
synfig-studio/src/synfigapp/actions/blinepointtangentsplit.cpp
synfig-studio/src/synfigapp/actions/blinepointtangentsplit.h

[Synfig Studio] add support for merge/split tangents for multiple vertices of object

---

synfig-studio/src/gui/canvasview.cpp
synfig-studio/src/gui/docks/dock_history.cpp
synfig-studio/src/gui/docks/dock_keyframes.cpp
synfig-studio/src/gui/docks/dock_layergroups.cpp
synfig-studio/src/gui/docks/dock_layers.cpp
synfig-studio/src/gui/docks/dock_metadata.cpp
synfig-studio/src/gui/docks/dock_soundwave.cpp
synfig-studio/src/gui/modules/mod_palette/dock_paledit.cpp
synfig-studio/src/gui/widgets/widget_coloredit.cpp
synfig-studio/src/gui/widgets/widget_defaults.cpp

[Synfig Studio] Improve style context code to one line

---

synfig-studio/src/gui/dialogs/dialog_color.cpp

[Synfig Studio] Turn off color dialog's resizability

---

synfig-studio/src/gui/app.cpp
synfig-studio/src/gui/canvasview.cpp

I went with `Ctrl + Space`
Discussion to change/modify it is open
Fixes #2026

Implement toggle animate hotkey

---

synfig-studio/src/gui/app.cpp

Remember the Number of rendering thread

---

synfig-studio/src/gui/canvasview.cpp
synfig-studio/src/gui/resources/css/synfig.css

[Synfig Studio] Noticeable progress bar

---

synfig-core/configure.ac

and OpenCL, as it is used together with OpenGL only
fix #1843

[Autotools] remove support for broken OpenGL renderering

---

synfig-core/src/synfig/valuenodes/valuenode_timeloop.cpp
synfig-core/src/synfig/valuenodes/valuenode_timeloop.h
synfig-studio/src/synfigapp/instance.cpp

fix issue pointed in
https://forums.synfig.org/t/animate-a-parameter-converted-to-a-time-loop/11839

[Synfig Studio] make TimeLoop valuenode editable via workspace

---

synfig-core/src/synfig/valuenodes/valuenode_staticlist.cpp

[Synfig Studio] fix skeleton deformation duplication

---

autobuild/snap-stable/snapcraft.yaml
snap/local/readme.md
snap/snapcraft.yaml

Also removed slang dependency
and added `readme`

[Snapcraft] Added Lottie dependency (lxml)

---

synfig-studio/src/gui/app.cpp
synfig-studio/src/gui/dialogs/dialog_color.cpp
synfig-studio/src/gui/dialogs/dialog_gradient.cpp
synfig-studio/src/gui/dialogs/dialog_targetparam.cpp

This PR is for the issue Inconsistent Dialog Button Order #2038 .  and This PR is in continuation with my previous PR #2068 
@ice0

[Synfig Studio] Changed the order of buttons in various dialog boxes (Color, Paragraph, Gradient, Target options) 

---

synfig-studio/src/gui/canvasview.cpp
synfig-studio/src/gui/canvasview.h

[Synfig Studio] Seek to begin/end follow playback bounds set by user

---

synfig-studio/src/gui/docks/dockbook.cpp

Close tabs with middle mouse click

---

synfig-studio/src/gui/docks/dockbook.cpp

Fixes #2119
Thanks to rodolforg for pointing out my mistake.

[Synfig Studio] Fixed an issue due to which menus were not displayed on all panels except the canvas

---

synfig-studio/src/gui/trees/layertreestore.cpp

[Synfig Studio] Fixed crash when user drags a group to a child group

---

.github/ISSUE_TEMPLATE/bug-report--version-1-4.md
.github/ISSUE_TEMPLATE/bug-report--version-master.md
.github/ISSUE_TEMPLATE/feature_request.md

Added an option to report issue for master branch + some minor edits.

Update issue templates for GitHub

---

synfig-core/src/modules/lyr_freetype/CMakeLists.txt
synfig-core/src/modules/lyr_std/CMakeLists.txt
synfig-core/src/modules/mod_bmp/CMakeLists.txt
synfig-core/src/modules/mod_dv/CMakeLists.txt
synfig-core/src/modules/mod_example/CMakeLists.txt
synfig-core/src/modules/mod_ffmpeg/CMakeLists.txt
synfig-core/src/modules/mod_filter/CMakeLists.txt
synfig-core/src/modules/mod_geometry/CMakeLists.txt
synfig-core/src/modules/mod_gif/CMakeLists.txt
synfig-core/src/modules/mod_gradient/CMakeLists.txt
synfig-core/src/modules/mod_imagemagick/CMakeLists.txt
synfig-core/src/modules/mod_jpeg/CMakeLists.txt
synfig-core/src/modules/mod_magickpp/CMakeLists.txt
synfig-core/src/modules/mod_mng/CMakeLists.txt
synfig-core/src/modules/mod_noise/CMakeLists.txt
synfig-core/src/modules/mod_openexr/CMakeLists.txt
synfig-core/src/modules/mod_particle/CMakeLists.txt
synfig-core/src/modules/mod_png/CMakeLists.txt
synfig-core/src/modules/mod_ppm/CMakeLists.txt
synfig-core/src/modules/mod_svg/CMakeLists.txt
synfig-core/src/modules/mod_yuv420p/CMakeLists.txt

[CMake] Removed unnecessary dependencies in modules

---

appveyor.yml

Enabled AppVeyor artifacts back

---

synfig-core/src/synfig/loadcanvas.cpp
synfig-core/src/synfig/savecanvas.cpp

Such as 'average' and 'weighted_average'.
Every Dynamic List has loop parameter.

Fixed issue with saving `loop` flag in some dynamic lists (Such as `average` and `weighted_average`)

---

synfig-core/src/modules/lyr_std/perspective.cpp

fix Warp not properly clipping noise gradient layer

---

synfig-studio/src/gui/canvasview.cpp
synfig-studio/src/gui/canvasview.h

[Synfig Studio] Split top horizontal toolbar in two toolbars (horizontal+vertical)

---

synfig-studio/images/CMakeLists.txt

Temporary correct cmake icons build

---

synfig-studio/plugins/lottie-exporter/common/Canvas.py
synfig-studio/plugins/lottie-exporter/common/Param.py
synfig-studio/plugins/lottie-exporter/lottie-exporter.py
synfig-studio/plugins/lottie-exporter/settings.py

Fixes: #1243
Fixes: #1242
I have tested some sample files, and this fix works for them. @rodolforg can you please review this. ^__^

[Lottie exporter] Implement use-defs

---

synfig-studio/images/CMakeLists.txt
synfig-studio/images/Makefile.am
synfig-studio/images/resize_disabled_icon.sif
synfig-studio/images/resize_down_icon.sif
synfig-studio/images/resize_down_left_icon.sif
synfig-studio/images/resize_down_right_icon.sif
synfig-studio/images/resize_left_icon.sif
synfig-studio/images/resize_right_icon.sif
synfig-studio/images/resize_transparent_icon.sif
synfig-studio/images/resize_up_icon.sif
synfig-studio/images/resize_up_left_icon.sif
synfig-studio/images/resize_up_right_icon.sif

To be used by new "Canvas Resize..." dialog
The icons represent resize direction relative to the anchor point for
3x3 grid buttons

[Synfig Studio] New arrows icons

---

synfig-studio/src/gui/canvasview.cpp
synfig-studio/src/gui/dialogs/canvasproperties.cpp
synfig-studio/src/gui/dialogs/dialog_soundselect.cpp
synfig-studio/src/gui/dialogs/vectorizersettings.cpp
synfig-studio/src/gui/preview.cpp
synfig-studio/src/gui/renddesc.cpp
synfig-studio/src/gui/render.cpp
synfig-studio/src/gui/widgets/widget_defaults.cpp
synfig-studio/src/gui/widgets/widget_defaults.h

@rodolforg @Keyikedalube
After reading about alignment.h , I think that these are the most suitable changes ! If these are correct, then allow me to make these changes wherever possible ! 
Thanks [^_^]

Replaced deprecated Gtk::Alignment class using Widget margins

---

synfig-core/src/synfig/canvasfilenaming.cpp
synfig-core/src/synfig/valuenodes/valuenode_animatedfile.cpp
synfig-core/src/synfig/valuenodes/valuenode_animatedfile.h
synfig-studio/src/gui/app.cpp
synfig-studio/src/gui/canvasview.cpp
synfig-studio/src/gui/canvasview.h
synfig-studio/src/synfigapp/canvasinterface.cpp

fix #2169
Rhubarb Lip Sync:
https://github.com/DanielSWolf/rhubarb-lip-sync

Added support for Rhubarb Lip Sync TSV and XML file formats for ValueNode_AnimatedFile

---

synfig-studio/src/gui/trees/layergrouptree.cpp
synfig-studio/src/gui/trees/layergrouptree.h

[Studio] Layers in sets can now be selected with a single click, rather than a double click

---

synfig-studio/plugins/lottie-exporter/CMakeLists.txt
synfig-studio/plugins/lottie-exporter/canvas.py
synfig-studio/plugins/lottie-exporter/common/Activepoint.py
synfig-studio/plugins/lottie-exporter/common/ActivepointList.py
synfig-studio/plugins/lottie-exporter/common/DashItemList.py
synfig-studio/plugins/lottie-exporter/common/Makefile.am
synfig-studio/plugins/lottie-exporter/common/WidthPoint.py
synfig-studio/plugins/lottie-exporter/common/WidthPointList.py
synfig-studio/plugins/lottie-exporter/properties/shapePropKeyframe/advanced_outline.py

This puts us one step closer to this issue: #858.
Once this PR is resolved, I will move on to animation of Bline points addition/deletion.

[Lottie exporter] Add animation to addition/deletion of Width points and Dash items in advanced outline

---

ChangeLog.md
synfig-studio/plugins/lottie-exporter/properties/shapePropKeyframe/advanced_outline.py
synfig-studio/plugins/lottie-exporter/properties/shapePropKeyframe/outline.py

Backport Lottie Exported fixes for Advanced Outline for 1.4.2

---

synfig-studio/plugins/lottie-exporter/CMakeLists.txt
synfig-studio/plugins/lottie-exporter/common/Activepoint.py
synfig-studio/plugins/lottie-exporter/common/ActivepointList.py
synfig-studio/plugins/lottie-exporter/common/Angle.py
synfig-studio/plugins/lottie-exporter/common/Bline.py
synfig-studio/plugins/lottie-exporter/common/BlinePoint.py
synfig-studio/plugins/lottie-exporter/common/Makefile.am
synfig-studio/plugins/lottie-exporter/common/Vector.py
synfig-studio/plugins/lottie-exporter/properties/shapePropKeyframe/advanced_outline.py
synfig-studio/plugins/lottie-exporter/properties/shapePropKeyframe/constant_width_outline.py
synfig-studio/plugins/lottie-exporter/properties/shapePropKeyframe/helper.py
synfig-studio/plugins/lottie-exporter/properties/shapePropKeyframe/outline.py
synfig-studio/plugins/lottie-exporter/properties/shapePropKeyframe/region.py
synfig-studio/plugins/lottie-exporter/settings.py
synfig-studio/plugins/lottie-exporter/synfig/animation.py

Resolves: #858
A long time needed fix for outlines, advanced outlines, and region layer is finally here :smiley:

[Lottie exporter] Add animation to addtion/deletion of Bline points

---

synfig-core/src/synfig/valuenodes/valuenode_animatedfile.cpp

string, Angle (degrees), bool, integer, real, time and Vector
Useful for letting animation data (like object coordinates along
time) generated by another software to be used on Synfig.
closes #2211

[Core] ValueNode_AnimatedFile now supports more data types

---

synfig-studio/src/gui/canvasview.cpp

Reported-by: veermetri05
https://forums.synfig.org/t/synfig-crashes-while-trying-to-import-a-file-into-itself/12406

[Studio] Fixed a crash when trying to import a file into itself 

---

synfig-studio/org.synfig.SynfigStudio.appdata.xml.in

I finally managed to build binary packages for all platforms from master branch.
That means we're ready to release development version of Synfig with all latest changes! :tada: :boom: :boom: :boom:

[Release] Version 1.5.0 (development)

---

ChangeLog-development.md
ETL/configure.ac
synfig-core/configure.ac
synfig-studio/configure.ac
synfig-studio/org.synfig.SynfigStudio.appdata.xml.in

This will indicate next commits as belonging to next development version.

Bump version number for next development release (1.7.0)

---

version-release.sh

- check if the script is executed from testing branch
- do not push any tags (as we are doing everything through PRs now)

Update release scripts

---

synfig-studio/src/synfigapp/canvasinterface.cpp

Refactoring: duplicate code is extracted into a separate function.

Extracted layer size update as a separate function

---

synfig-studio/src/synfigapp/actions/valuedescset.cpp

when moving a child bone with Bones tool

Fix crash when moving origin point of child bone in Skeleton Deformation Layer using Bone Tool

---

synfig-studio/src/gui/app.cpp
synfig-studio/src/gui/canvasview.cpp
synfig-studio/src/gui/canvasview.h
synfig-studio/src/gui/workarea.cpp
synfig-studio/src/gui/workarea.h
synfig-studio/src/gui/workarearenderer/renderer_canvas.cpp

This pull request is aimed at introducing the ability for users to use `Onion Skin` with:
- Keyframes (as with previous versions of Synfig)
- Frames
Related issues: #1562, #1817
(Linking to related issues)
Fixes #1562
Fixes #1817

[Synfig Studio] Add Onion Skin ability to choose between Keyframes and Frames

---

synfig-studio/src/gui/widgets/widget_soundwave.cpp

[Synfig Studio] fix soundwave for some audio that couldn't be loaded

---

synfig-studio/src/gui/widgets/widget_timetrack.cpp
synfig-studio/src/gui/widgets/widget_timetrack.h

Update time track area when keyframe is changed from keyframe header

---

synfig-studio/src/gui/canvasview.cpp
synfig-studio/src/gui/canvasview.h
synfig-studio/src/gui/duckmatic.cpp
synfig-studio/src/gui/duckmatic.h
synfig-studio/src/gui/workarea.cpp

Added the ability to add a new vertex on a Spline by double-click

---

synfig-studio/src/synfigapp/canvasinterface.cpp

Select parent group after image import

---

synfig-studio/src/synfigapp/actions/layerduplicate.cpp

Crash caused by incorrect work with iterators
Fixes issue: #2259

Fixed crash of test on Void Linux

---

synfig-core/src/modules/mod_gif/trgt_gif.cpp

Fixed crash when rendering to gif target

---

synfig-core/src/modules/mod_svg/svg_parser.cpp
synfig-core/src/modules/mod_svg/svg_parser.h

- Outline width
- Fill x Outline z-order (paint-order)

Svg_parser: cleanups and some outline-related fixes

---

synfig-studio/src/gui/widgets/widget_vector.cpp
synfig-studio/src/gui/widgets/widget_vector.h

Added support for Widget_Vector to respond to Tab and Shift-Tab as described in https://github.com/synfig/synfig/issues/1208
Close #1208

Tab/Shift-Tab support for Widget_Vector

---

synfig-core/src/modules/mod_svg/svg_parser.cpp
synfig-core/src/modules/mod_svg/svg_parser.h

- linejoin "bevel"
- linecap "square"
- dashes ("dash_array" and "dash_offset")
* Something is off here, but better than nothing

Svg_parser: support more outline/stroke styles

---

synfig-studio/src/gui/widgets/widget_fontfamily.cpp

Add completion to Widget_FontFamily

---

synfig-studio/src/gui/cellrenderer/cellrenderer_timetrack.cpp
synfig-studio/src/gui/widgets/widget_curves.cpp
synfig-studio/src/gui/widgets/widget_timetrack.cpp

don't let user drag a waypoint to a time lower than current minimum

---

synfig-studio/src/gui/docks/dock_timetrack.cpp

Parameters and Timeline panels show the same row selected

---

synfig-core/src/synfig/loadcanvas.cpp
synfig-core/src/synfig/loadcanvas.h

Allow Bones parameters to be connected to exported value nodes

---

synfig-studio/src/gui/docks/dockable.cpp

Revert changes for Panel Tabs made in #2189

---

synfig-studio/src/gui/timeplotdata.cpp

Wider time track space at start and end

---

synfig-core/configure.ac

libpng provides the `.pc` file since (at least) 1.2.27 version (2008)

Autotools: detects libpng via pkg-config

---

synfig-studio/src/synfigapp/actions/valuedescset.cpp

No crashes in previous code, but it could eventually be a
false positive. Besides, it didn't make clear what it did.

[Studio] Bone Tool: fix how to check for skeleton deformation

---

3-package-osx-dmg.sh
ETL/configure.ac
synfig-core/configure.ac
synfig-core/src/modules/mod_gif/trgt_gif.cpp
synfig-core/src/modules/mod_magickpp/Makefile.am
synfig-core/src/synfig/filesystemnative.cpp
synfig-core/src/synfig/filesystemnative.h
synfig-core/src/synfig/layers/layer_pastecanvas.cpp
synfig-core/src/synfig/loadcanvas.cpp
synfig-core/src/synfig/loadcanvas.h
synfig-studio/configure.ac
synfig-studio/org.synfig.SynfigStudio.appdata.xml.in
synfig-studio/src/gui/CMakeLists.txt
synfig-studio/src/gui/app.cpp
synfig-studio/src/gui/canvasview.cpp
synfig-studio/src/gui/docks/dock_toolbox.cpp
synfig-studio/src/gui/docks/dockable.cpp
synfig-studio/src/gui/docks/dockdialog.cpp
synfig-studio/src/gui/docks/dockdialog.h
synfig-studio/src/gui/mainwindow.cpp
synfig-studio/src/gui/renddesc.cpp
synfig-studio/src/gui/renddesc.h
synfig-studio/src/synfigapp/actions/valuedescblinelink.cpp
synfig-studio/src/synfigapp/actions/valuedescexport.cpp
synfig-studio/src/synfigapp/canvasinterface.cpp

This is an update to stable branch (critical fixes).

Version 1.4.3

---

autobuild/build.sh

- Autodetect number of threads for compilation on MacOS
- Fixed CPP/LDFLAGS to correctly work with M1 Homebrew
- Fixed boost detection

[MacOS M1] Fixed autotools build

---

synfig-studio/src/synfigapp/actions/valuedescset.cpp

ValueDescSet Skeleton Deformation bone: minor refactoring

---

synfig-studio/src/gui/states/state_bone.cpp

Fix bone width handle visibility

---

synfig-studio/src/synfigapp/actions/valuedescset.cpp

otherwise rest bone won't be set. Sorry.

fix my mistake in #2458: it should not return at that point

---

synfig-studio/src/synfigapp/blineconvert.cpp

fix distortions at the end of lines made with the drawing tool

---

synfig-studio/src/gui/renddesc.cpp
synfig-studio/src/gui/renddesc.h

Make sure flags are correctly updated when setting renddesc

---

synfig-core/src/modules/lyr_freetype/lyr_freetype.cpp

Fix rendering of some glyphs (and some code cleanup)

---

synfig-studio/src/synfigapp/actions/valuedescset.cpp

minor cleanup on TypePair<Bone,Bone> usage

---

synfig-studio/src/gui/states/state_bone.cpp

Bone Tool: Fixed issue where skeleton "name" wasn't updated as new Layers are created

---

synfig-studio/src/gui/states/state_width.cpp

fix crash when using Width Tool on Skeleton Layer

---

synfig-core/src/modules/lyr_freetype/lyr_freetype.cpp

There were some floating point issues
fix #2508

fix text layer hit check once again: issue when size was too small

---

synfig-studio/src/brushlib/brush.hpp

fix Debian 9 building

---

synfig-core/src/modules/mod_svg/svg_parser.cpp
synfig-core/src/synfig/filesystemtemporary.cpp
synfig-core/src/synfig/loadcanvas.cpp
synfig-core/src/synfig/valuenodes/valuenode_animatedfile.cpp
synfig-core/src/tool/joblistprocessor.cpp
synfig-core/src/tool/main.cpp
synfig-studio/src/gui/app.cpp
synfig-studio/src/gui/dialogs/dialog_setup.cpp
synfig-studio/src/gui/dialogs/dialog_workspaces.cpp
synfig-studio/src/gui/docks/dockmanager.cpp
synfig-studio/src/gui/workspacehandler.cpp

V817. It is more efficient to search for 'X' character rather than a string.
https://pvs-studio.com/en/docs/warnings/v817/

Fixed PVS-Studio warning v817

---

synfig-studio/po/POTFILES.in
synfig-studio/src/gui/workarea.cpp
synfig-studio/src/gui/workarearenderer/CMakeLists.txt
synfig-studio/src/gui/workarearenderer/Makefile_insert
synfig-studio/src/gui/workarearenderer/renderer_bonedeformarea.cpp
synfig-studio/src/gui/workarearenderer/renderer_bonedeformarea.h

Show bone shape when Skeleton Deformation layer is disabled

---

synfig-studio/src/gui/states/state_bone.cpp

Bone Tool: fix selection of active bone when clicking on a bone duck

---

synfig-core/test/Makefile.am
synfig-core/test/bline.cpp
synfig-core/test/node.cpp
synfig-core/test/test_base.h

Two tests are currently failing:
- `set_node_guid_emits_signal_guid_changed()`
- `deleting_node_removes_it_as_parent_from_its_children`

create synfig::Node unit tests

---

synfig-studio/src/gui/workarearenderer/renderer_bonedeformarea.cpp

Fix Bone Shape of Skeleton Deformation affected by Transformations

---

synfig-core/src/synfig/guid.cpp

ensure computed GUID is not zero

---

synfig-core/test/node.cpp

`deleting_node_removes_it_as_parent_from_its_children()` keeps failing
I don't think if it is easy to solve without storing not only parents
nodes, but children also.

add more synfig::Node tests

---

ETL/ETL/_bezier.h
ETL/ETL/_hermite.h
ETL/ETL/_pen.h
synfig-core/src/modules/mod_gif/trgt_gif.h
synfig-core/src/modules/mod_png/trgt_png_spritesheet.h
synfig-core/src/modules/mod_svg/svg_parser.cpp
synfig-core/src/modules/mod_svg/svg_parser.h
synfig-core/src/synfig/layers/layer_shape.h
synfig-core/src/synfig/rendering/software/function/blur.h
synfig-core/src/synfig/rendering/surface.h
synfig-core/src/synfig/zstreambuf.cpp
synfig-core/src/tool/renderprogress.h
synfig-studio/src/gui/duckmatic.h
synfig-studio/src/synfigapp/vectorizer/centerlineskeletonizer.cpp
synfig-studio/src/synfigapp/vectorizer/centerlinetostrokes.cpp
synfig-studio/src/synfigapp/vectorizer/polygonizerclasses.h

V730. Not all members of a class are initialized inside the constructor.
https://pvs-studio.com/en/docs/warnings/v730/

Fixed PVS-Studio warning v730

---

synfig-studio/src/synfigapp/actions/layerduplicate.cpp

and remove the dependency on `canvas`

eliminate the need to set_time() on the search for bones

---

synfig-core/src/modules/mod_ffmpeg/trgt_ffmpeg.cpp
synfig-core/src/modules/mod_ffmpeg/trgt_ffmpeg.h

https://forums.synfig.org/t/any-good-way-to-export-a-single-video-with-alpha-transparency/12978
https://forums.synfig.org/t/transparent-background-for-videos/11381
https://github.com/synfig/synfig/issues/2161
https://github.com/synfig/synfig/issues/519
maybe:
https://github.com/synfig/synfig/issues/841

FFmpeg targets: allow to render alpha channel for webm and hap videos

---

synfig-studio/src/gui/widgets/widget_sublayer.cpp
synfig-studio/src/gui/widgets/widget_sublayer.h

also, make some method protected instead of public

simplify Widget_Sublayer by using Gtk::ComboBoxText

---

synfig-studio/src/gui/docks/dockmanager.cpp

Fixes #2584. Hiding a window causes it to be removed from Gtk::Application. When all windows are removed, the main event loop stops.

Fix crash when switching workspaces

---

synfig-core/src/modules/mod_particle/plant.cpp

prevent ambiguity of `abs(const Real&)` on Plant

---

synfig-studio/src/gui/trees/layertreestore.cpp

Reported-by: BigBang
https://forums.synfig.org/t/no-group-for-the-tones-of-papagayao/12849
fix #1804
guilty commit: f63ade3652fa6d9d41315c227f71cf2ec764e9ec
Test file: [test_pgo.zip](https://github.com/synfig/synfig/files/7814071/test_pgo.zip)

fix regression: importing papagayo file didn't show the expected layers

---

synfig-studio/src/gui/resources/ui/CMakeLists.txt
synfig-studio/src/gui/resources/ui/file_top_toolbar.glade
synfig-studio/src/gui/resources/ui/history_toolbar.glade
synfig-studio/src/gui/resources/ui/right_toolbar.glade
synfig-studio/src/gui/resources/ui/studio_menubar.xml
synfig-studio/src/gui/resources/ui/top_toolbar.glade

@ice0 This is the .xml menubar separated to its own file. Also, this include a .glade file for the history toolbar in the dock. This is used with gtk::builder in #2589

Added Synfig Studio menu and UI files

---

synfig-studio/src/gui/states/state_bline.cpp
synfig-studio/src/gui/states/state_circle.cpp
synfig-studio/src/gui/states/state_draw.cpp
synfig-studio/src/gui/states/state_gradient.cpp
synfig-studio/src/gui/states/state_lasso.cpp
synfig-studio/src/gui/states/state_polygon.cpp
synfig-studio/src/gui/states/state_rectangle.cpp
synfig-studio/src/gui/states/state_star.cpp
synfig-studio/src/gui/states/state_text.cpp

Fixed missing icons in tool options

---

synfig-studio/src/gui/instance.cpp
synfig-studio/src/synfigapp/actions/valuedescbonesetparent.cpp
synfig-studio/src/synfigapp/actions/valuedescbonesetparent.h

Fix https://github.com/synfig/synfig/issues/1669

[Studio] Hide "Make Parent To Active Bone" menu item when not using Skeleton Tool

---

synfig-studio/src/gui/app.cpp

Issue introduced in this PR: #2651
On Ubuntu 20.04 it works without problems

Fixed issue with python search on Ubuntu 18

---

synfig-studio/src/gui/pluginmanager.cpp

- python3 priority increased
- switched to `Glib::getenv(...)` for correct locale handling

Refactored python search algorithm

---

synfig-studio/src/gui/cellrenderer/cellrenderer_timetrack.cpp
synfig-studio/src/gui/widgets/widget_coloredit.cpp
synfig-studio/src/gui/widgets/widget_curves.cpp
synfig-studio/src/gui/widgets/widget_timegraphbase.cpp
synfig-studio/src/gui/widgets/widget_timeslider.cpp
synfig-studio/src/gui/workarearenderer/renderer_bbox.cpp
synfig-studio/src/gui/workarearenderer/renderer_dragbox.cpp
synfig-studio/src/gui/workarearenderer/renderer_ducks.cpp
synfig-studio/src/gui/workarearenderer/renderer_guides.cpp
synfig-studio/src/gui/workarearenderer/renderer_timecode.cpp
synfig-studio/src/gui/workarearenderer/workarearenderer.h

https://wiki.gnome.org/Projects/gtkmm/PortingToGtkmm3

Replaced deprecated Gdk::Color with Gdk:RGBA

---

synfig-core/src/synfig/valuenodes/valuenode_bone.cpp
synfig-core/src/synfig/valuenodes/valuenode_bone.h
synfig-studio/src/synfigapp/actions/valuedescbonesetparent.cpp
synfig-studio/src/synfigapp/actions/valuedescbonesetparent.h

Refactoring and bugfix for ValueDescBoneSetParent

---

synfig-studio/src/synfigapp/actions/blinepointtangentmerge.cpp
synfig-studio/src/synfigapp/actions/blinepointtangentsplit.cpp

fix: No context menu shown for Transformation parameter of Group Layer

---

synfig-core/src/synfig/valuenode_registry.cpp
synfig-core/src/synfig/valuenode_registry.h

Removed all unnecessary "magic"

refactor(core): Cleaned up registration function

---

synfig-studio/src/gui/widgets/widget_coloredit.cpp
synfig-studio/src/gui/widgets/widget_coloredit.h

Fix #2678
`are_close_colors` always returned true.

fix: Wrong color in HSV wheel when color was changed with paint bucket

---

synfig-studio/src/gui/app.cpp

A new clean PR from the orginal in #2588 , which will be closed but I'm just waiting for approval.

feat: Added support for `Ctr+Enter` to complete text input in Text tool dialog

---

ETL/test/angle.cpp

they are actually used in test/benchmark

test(etl): remove unused methods for etl::angle

---

ETL/ETL/_angle.h

BREAKING CHANGE: some etl::angle API changed - see related commits

refactor!: clean etl::angle

---

synfig-core/src/synfig/palette.cpp

fix: palette loading

---

synfig-studio/src/gui/widgets/widget_timetrack.cpp

fix: Indicate segments where points are disabled in Timetrack Panel (regression)

---

synfig-studio/src/gui/cellrenderer/cellrenderer_timetrack.cpp

They now show stuff like #2385 and #2719 do.

fix: Parameter & Library Panels are now more similar to TimeTrack Panel

---

synfig-studio/src/gui/states/state_bline.cpp

fix: Spline tool blocks hotkey presses

---

synfig-core/src/synfig/keyframe.cpp
synfig-core/src/synfig/keyframe.h
synfig-core/test/CMakeLists.txt
synfig-core/test/Makefile.am
synfig-core/test/keyframe.cpp

Also do a minor cleanup and improve docs.
BREAKING CHANGE: synfig API changed:
- removed synfig::Keyframe::dump()
- removed synfig::Keyframe::insert_time()

refactor!: clean `synfig::Keyframe`

---

synfig-studio/src/gui/instance.cpp

Fixes https://github.com/synfig-ru/synfig/issues/1

chore: Enabled some strings for translation

---

synfig-studio/src/languages.inc.c

chore: Fixed a typo in Preferences->Language dropdown

---

synfig-studio/src/gui/resources/ui/Makefile.am

Commit: 0b455f370fc7fcf3d640eecd4c988729af0d25d8

build(autotools): include UI files created via PR #2638

---

synfig-core/src/synfig/valuenodes/valuenode_bone.cpp

fix: using invalid iterator in ValueNode_Bone

---

synfig-studio/src/gui/app.cpp
synfig-studio/src/gui/app.h

s/detials/details/  
This change is untested, please review closely.

chore: fix source typos

---

synfig-core/src/synfig/listimporter.cpp

with the fix provided by PR #2789 (commit 25f28b14214bcc98d736ce88138e79f087d56510),
it was finally viable to implement this (simple) feature :)
fix #965

feat: added support for SVG image sequence with lst files

---

synfig-core/src/modules/mod_gradient/conicalgradient.cpp
synfig-core/src/modules/mod_gradient/curvegradient.cpp
synfig-core/src/modules/mod_gradient/lineargradient.cpp
synfig-core/src/modules/mod_gradient/radialgradient.cpp
synfig-core/src/modules/mod_gradient/spiralgradient.cpp
synfig-core/src/modules/mod_noise/noise.cpp
synfig-core/src/synfig/layers/layer_pastecanvas.cpp

fix: hit_check for gradient & paste_canvas layers with BEHIND and ONTO blends

---

synfig-core/src/synfig/gradient.cpp

1 issue:
"can't decrement vector iterator before begin"
2 issue:
"vector iterators incompatible"

fix(msvc): fixed debug build in MSVC

---

ETL/m4/subs.m4
synfig-core/m4/subs.m4
synfig-studio/m4/subs.m4

build(autotools): allow to compile release build with debug info

---

synfig-core/src/modules/mod_geometry/advanced_outline.cpp
synfig-core/src/modules/mod_geometry/advanced_outline.h
synfig-core/src/synfig/valuenodes/valuenode_dilist.cpp
synfig-core/src/synfig/valuenodes/valuenode_dilist.h

Reported-by: Svarov (https://forums.synfig.org/t/sunglasses-short-synfig-animation-detailled-analysis-for-optimization/13482)

perf: avoid double computation

---

cmake/InstallMSYS2.cmake

build(AppVeyor): added missing libpcre2

---

synfig-core/src/modules/mod_ffmpeg/trgt_ffmpeg.cpp

fix: missing last frame for ffmpeg target

---

synfig-studio/src/gui/instance.cpp

https://www.gnu.org/software/gettext/manual/gettext.html#Preparing-Strings

fix: use format string instead of string concatenation

---

synfig-studio/src/gui/app.cpp
synfig-studio/src/gui/app.h

and remove unneeded synfig::ChangeLocale here

refactor: rename load_file_window_size() to load_recent_files()

---

synfig-core/src/synfig/main.cpp

procfs path was wrong
https://stackoverflow.com/questions/1023306/finding-current-executables-path-without-proc-self-exe https://man.openbsd.org/OpenBSD-5.1/mount_procfs.8 https://www.freebsd.org/cgi/man.cgi?query=procfs&sektion=5

fix: get_binary_path() for FreeBSD, DragonFlyBSD, NetBSD and OpenBSD

---

synfig-studio/src/gui/canvasview.cpp
synfig-studio/src/gui/canvasview.h

previously it was just toggling the right toolbar visibility

fix: show/hide main window toolbar should affect both toolbars

---

autobuild/osx/app-template/Contents/Info.plist
synfig-studio/src/gui/dialogs/about.cpp
synfig-studio/src/gui/synfigstudio.rc

chore: bump  year to 2023

---

synfig-studio/src/gui/canvasview.cpp

fixes #2969 
But I haven't tested it enough I think so I will leave it as draft until I get enough time to do so.
@Svarov-RZM could you try it :)

fix: preview dialog now shows the correct start and end times

---

synfig-studio/src/gui/iconcontroller.cpp

refactor(iconcontroller): list icons in std::vector to better readability

---

synfig-studio/src/gui/preview.cpp
synfig-studio/src/gui/preview.h
synfig-studio/src/gui/states/state_bone.cpp
synfig-studio/src/gui/states/state_lasso.cpp
synfig-studio/src/gui/trees/childrentree.cpp
synfig-studio/src/gui/trees/childrentree.h
synfig-studio/src/gui/widgets/widget_value.cpp
synfig-studio/src/gui/widgets/widget_value.h

done:
- second and third row in preview window
- widget valueBase
- children tree
left:
~~- states bone and lasso~~

refactor: replace deprecated `Gtk::HBox` with `Gtk::Box`

---

synfig-core/src/synfig/context.h
synfig-core/src/synfig/layer.cpp
synfig-core/src/synfig/rendering/task.h
synfig-studio/src/gui/app.cpp
synfig-studio/src/gui/canvasview.cpp
synfig-studio/src/gui/splash.cpp

This includes
- typos in comments
- small grammar fixes in comments + in error.
- variable renaming due to typos. Hence the "refactor" in the title.

chore: fix various typos

---

synfig-core/src/tool/renderprogress.cpp
synfig-core/src/tool/renderprogress.h

Follow up for this https://github.com/synfig/synfig/pull/3018#discussion_r1136616032

feat: cleaner cli render progress output

---

synfig-core/src/modules/mod_bmp/trgt_bmp.cpp
synfig-core/src/modules/mod_bmp/trgt_bmp.h
synfig-core/src/modules/mod_dv/trgt_dv.cpp
synfig-core/src/modules/mod_dv/trgt_dv.h
synfig-core/src/modules/mod_ffmpeg/trgt_ffmpeg.cpp
synfig-core/src/modules/mod_gif/trgt_gif.cpp
synfig-core/src/modules/mod_imagemagick/trgt_imagemagick.cpp
synfig-core/src/modules/mod_imagemagick/trgt_imagemagick.h
synfig-core/src/modules/mod_jpeg/trgt_jpeg.cpp
synfig-core/src/modules/mod_jpeg/trgt_jpeg.h
synfig-core/src/modules/mod_magickpp/trgt_magickpp.cpp
synfig-core/src/modules/mod_mng/trgt_mng.cpp
synfig-core/src/modules/mod_mng/trgt_mng.h
synfig-core/src/modules/mod_openexr/trgt_openexr.cpp
synfig-core/src/modules/mod_openexr/trgt_openexr.h
synfig-core/src/modules/mod_png/trgt_png.cpp
synfig-core/src/modules/mod_png/trgt_png.h
synfig-core/src/modules/mod_png/trgt_png_spritesheet.cpp
synfig-core/src/modules/mod_png/trgt_png_spritesheet.h
synfig-core/src/modules/mod_ppm/mptr_ppm.cpp
synfig-core/src/modules/mod_ppm/trgt_ppm.cpp
synfig-core/src/modules/mod_ppm/trgt_ppm.h
synfig-core/src/modules/mod_yuv420p/trgt_yuv.cpp
synfig-core/src/synfig/filecontainerzip.cpp
synfig-core/src/synfig/filesystemnative.cpp
synfig-core/src/synfig/main.cpp
synfig-core/src/synfig/smartfile.h
synfig-core/src/synfig/target_null.h

And maybe it helps performance, if new array size is equal to previous one, because resize() wouldn't perform anything in this case.

refactor: code cleanup in Targets

---

synfig-core/test/Makefile.am
synfig-studio/test/Makefile.am

test: use preset variable of AutoTools to some directories

---

synfig-core/src/modules/lyr_std/bevel.cpp

feat: add handles to Bevel layer parameters

---

synfig-studio/src/gui/docks/dock_toolbox.cpp

Related to: PR #3012 (313878d4d12a32f24b533d0832a6660b63ee149a)

fix: toolbox panel wasn't updated on switching tools via shortcuts

---

synfig-studio/src/gui/app.cpp
synfig-studio/src/gui/canvasview.cpp

refactor: list document actions in a std::vector to better readability

---

synfig-studio/po/POTFILES.in
synfig-studio/src/gui/canvasview.cpp
synfig-studio/src/gui/dialogs/dialog_keyframe.cpp
synfig-studio/src/gui/trees/keyframetreestore.cpp
synfig-studio/src/synfigapp/Makefile.am
synfig-studio/src/synfigapp/action.cpp
synfig-studio/src/synfigapp/actions/CMakeLists.txt
synfig-studio/src/synfigapp/actions/keyframetoggl.cpp
synfig-studio/src/synfigapp/actions/keyframetoggle.cpp
synfig-studio/src/synfigapp/actions/keyframetoggle.h

and remove unused #include
BREAKING CHANGE: synfigapp API changed:
- action "KeyframeToggl" renamed as "KeyframeToggle"

refactor!: rename action "KeyframeToggl" as "KeyframeToggle"

---

synfig-studio/src/gui/duckmatic.cpp

Before this PR, it wouldn't get any second closest guide if it appears after the best match.

fix: find the second closest guide no matter the guide list order

---

synfig-core/src/modules/mod_png/mptr_png.cpp

And it's HUGE: the whole image.

fix: prevent memory leak on importing PNG files

---

synfig-studio/images/index.theme
synfig-studio/src/gui/dialogs/dialog_setup.cpp

Otherwise it is an invalid theme folder.
fix #3115

fix: preferences dialog should list only themes with index.theme file

---

synfig-studio/src/gui/dialogs/dialog_setup.cpp
synfig-studio/src/gui/dialogs/dialog_setup.h

A path is displayed which is non-editable and a button which opens up a file explorer tab to the path.
closes #3119

feat: added path and button to open plugin folder in Preferences window

---

synfig-core/src/synfig/layers/layer_motionblur.cpp
synfig-core/src/synfig/layers/layer_motionblur.h

set "Subsampling Type" to "None".
fix #3172

feat: layer Motion Blur now can create a non blurred trail

---

synfig-core/src/synfig/layers/layer_motionblur.cpp

the idea is to have a trail of duplicate canvas.
fix #3199

fix: new MotionBLur subsampling None used wrong blend method

---

synfig-core/src/synfig/layers/layer_sound.cpp

fix: preview window not showing when there is a Layer_Sound

---

synfig-core/po/POTFILES.in
synfig-core/src/synfig/filesystemtemporary.cpp
synfig-core/src/synfig/filesystemtemporary.h
synfig-studio/src/gui/app.cpp
synfig-studio/src/gui/instance.cpp

fix(Windows): plugins fail to run for files with non-latin characters

---

synfig-core/src/modules/mod_filter/chromakey.cpp
synfig-core/src/modules/mod_filter/chromakey.h

feat: add "invert" parameter to ChromaKey layer

---

synfig-studio/src/gui/docks/dock_toolbox.cpp
synfig-studio/src/gui/statemanager.cpp

fix: restore icons for Tools menu

---

README.md

Open source license requirement:
https://pvs-studio.com/en/order/open-source-license/

chore:  PVS-Studio has been added to the list of organizations

---

synfig-core/src/modules/mod_imagemagick/mptr_imagemagick.cpp
synfig-core/src/synfig/debug/debugsurface.cpp
synfig-core/src/synfig/debug/debugsurface.h
synfig-core/src/synfig/debug/log.cpp
synfig-core/src/synfig/debug/log.h
synfig-core/src/synfig/filesystemtemporary.cpp
synfig-core/src/synfig/filesystemtemporary.h
synfig-core/src/synfig/rendering/renderer.cpp
synfig-core/src/synfig/rendering/renderer.h
synfig-studio/src/gui/app.cpp
synfig-studio/src/gui/autorecover.cpp
synfig-studio/src/gui/dialogs/vectorizersettings.cpp
synfig-studio/src/gui/instance.cpp
synfig-studio/src/gui/pluginmanager.cpp
synfig-studio/src/synfigapp/instance.cpp
synfig-studio/src/synfigapp/instance.h
synfig-studio/src/synfigapp/vectorizer/centerlinevectorizer.cpp

focus on synfig::FileSystemTemporary this time

refactor: prefer synfig::filesystem::Path rather than synfig::String or std::string

---

synfig-core/src/synfig/distance.cpp
synfig-core/src/synfig/distance.h
synfig-studio/src/gui/states/state_bline.cpp
synfig-studio/src/gui/states/state_bone.cpp
synfig-studio/src/gui/states/state_circle.cpp
synfig-studio/src/gui/states/state_draw.cpp
synfig-studio/src/gui/states/state_lasso.cpp
synfig-studio/src/gui/states/state_polygon.cpp
synfig-studio/src/gui/states/state_rectangle.cpp
synfig-studio/src/gui/states/state_star.cpp
synfig-studio/src/gui/states/state_width.cpp

fix: units in Tool Options panel didn't follow app settings (regression)

---

synfig-core/src/modules/mod_bmp/mptr_bmp.cpp
synfig-core/src/modules/mod_ffmpeg/mptr_ffmpeg.cpp
synfig-core/src/modules/mod_magickpp/trgt_magickpp.cpp
synfig-core/src/modules/mod_png/mptr_png.cpp
synfig-core/src/modules/mod_ppm/mptr_ppm.cpp
synfig-core/src/synfig/importer.cpp
synfig-core/src/synfig/listimporter.cpp
synfig-core/src/synfig/loadcanvas.cpp

as c_str() means native encoding, not UTF-8.

fix: use u8_str() instead of c_str() for filesystem::Path

---

1-setup-linux-native.sh

And also fix Fedora version detection.

chore(build): add support for installing build dependencies in Red OS

---

autobuild/osx/app-template/Contents/Info.plist
synfig-studio/src/gui/dialogs/about.cpp
synfig-studio/src/gui/synfigstudio.rc

chore: bump year to 2024

---

synfig-studio/src/gui/resources/ui/dialog_pasteoptions.glade

feat: add missing scroll bar to Paste Layer dialog

---

synfig-core/src/synfig/loadcanvas.cpp

Due to changes in b172e3771a131dbd26879aae334b84ac26bcb6e6 (#2777)

fix: guide lines ignored on loading from old files

---

synfig-studio/src/gui/widgets/widget_curves.cpp

https://github.com/synfig/synfig/assets/5604544/04bc7c11-9b95-4438-9816-724c588585e3
Live switching (as shown in the video) is not available in this PR.
Will be added as a separate PR.

feat: added ability to set colors for a dark theme for curves

---

synfig-core/test/test_base.h

fix: build on OSX 10.9

---

synfig-studio/src/gui/workarearenderer/renderer_canvas.cpp

If thumbnail preview is disabled in Synfig Studio
settings, don't render them, instead of just hide them.
Related to #1413 (6709d28f77f8c3a568e200237221b12b87fd0b12)

perf(GUI): don't render frame thumbnails if disabled

---

ChangeLog-development.md
ChangeLog.md

Add missing entry - https://github.com/synfig/synfig/issues/3144

chore: update Change Log for 1.4.5

---

synfig-core/src/synfig/rendering/software/task/Makefile_insert

chore: Fix generation of source packages using Autotools (again)

---

ETL/ETL/_handle.h
synfig-core/test/handle.cpp

Split from PR #3071 . That one will be only about moving last ETL files to synfig-core.

refactor: add move constructor to handle/loose_handle/rhandle

---

synfig-core/src/modules/mod_imagemagick/mptr_imagemagick.cpp
synfig-core/src/modules/mod_imagemagick/trgt_imagemagick.cpp

On Windows (I built with CMake) for some weird reason calling ImageMagick's convert calls Windows/System32/convert.exe . It's odd because my Path env var seems to list the mingw64 directory first, but a solution is using the 'magick' syntax, where you just call 'magick' to convert as per https://imagemagick.org/script/command-line-tools.php
The problem is widely known as per https://stackoverflow.com/questions/3060205/error-invalid-parameter-fom-imagemagick-convert-on-windows , I was getting the same 'Invalid Parameter' error
The patch uses 'magick convert' (legacy syntax), instead of 'magick' for compatibility with ImageMagick 6, since many distros don't have official packages for ImageMagick 7, despite the release being over 5 years old: …

fix: change convert.exe syntax to avoid clash in Windows

---

synfig-studio/plugins/lottie-exporter/export_without_variable_width.py
synfig-studio/plugins/lottie-exporter/lottie-exporter.py

fix: Lottie export failure with Japanese locale setting in Windows

---

synfig-studio/src/gui/dialogs/dialog_pasteoptions.cpp
synfig-studio/src/gui/dialogs/dialog_pasteoptions.h
synfig-studio/src/gui/resources/ui/dialog_pasteoptions.glade

feat: add "copy all" for Paste Options dialog

---

synfig-studio/src/gui/widgets/widget_curves.cpp

fix: handle (Radial)Composite valuenodes via Widget_Curves

---

synfig-studio/src/gui/cellrenderer/cellrenderer_value.cpp

Introduced when fixing #3288 ( 483b5ed - PR 3373 ).
By the way, both commits fix another case:
(In Synfig <= 1.5.3)
1. Create a text layer
2. Create a star layer
3. Select the text layer
4. Click on color parameter of text layer to open Color editor
5. Select both layers (text and star)
6. Change the color in the previously opened Color editor
7. It changes the text color, but yells an error to star
The problem does not happen if you open color dialog after select both layers (step #5 above)
fix #3469

fix: regression: couldn't edit color or gradient of multiple layers

---

synfig-core/src/modules/lyr_std/julia.cpp
synfig-core/src/modules/lyr_std/julia.h

fix: julia Set used to ignore Bailout parameter

---

ETL/ETL/_handle.h
synfig-core/src/modules/lyr_std/perspective.cpp
synfig-core/src/synfig/layers/layer_meshtransform.cpp
synfig-core/src/synfig/layers/layer_shape.cpp
synfig-core/src/synfig/rendering/common/task/taskcontour.h
synfig-core/src/synfig/rendering/primitive/contour.cpp
synfig-core/src/synfig/rendering/primitive/contour.h
synfig-core/src/synfig/rendering/primitive/intersector.cpp
synfig-core/src/synfig/rendering/primitive/intersector.h

Random crashes :'(
fix https://github.com/synfig/synfig/issues/3493

fix: possible double free due to multithreading with Contour

---

synfig-studio/src/synfigapp/canvasinterface.cpp

but users asked for duplicate removal.

fix: importing image sequence failed when there was no duplicates

---

ETL/configure.ac
ETL/m4/ETL.m4
synfig-core/m4/ETL.m4
synfig-studio/m4/ETL.m4

related code was deleted or moved to synfig-core

build(ETL): cleanup dismissed ETL dependencies

---

synfig-studio/src/gui/docks/dock_params.cpp
synfig-studio/src/gui/docks/dock_params.h

fix(ui): refresh Parameters panel after undo/redo

---

synfig-core/src/modules/mod_gradient/conicalgradient.cpp
synfig-core/src/modules/mod_gradient/lineargradient.cpp
synfig-core/src/modules/mod_gradient/radialgradient.cpp
synfig-core/src/modules/mod_gradient/spiralgradient.cpp

partially revert commit 46013ffe667813998f024f9a96df0328f62403e1 (PR #3301)

fix: fix shift in gradient layers

---

autobuild/osx/app-template/Contents/Info.plist
synfig-studio/src/gui/dialogs/about.cpp
synfig-studio/src/gui/synfigstudio.rc

Based on the bumps from previous years

chore: bump year to 2025

---

synfig-core/src/modules/lyr_freetype/lyr_freetype.cpp

Addressed an issue where Text layers would render a corrupted string when using certain fonts (including Calibri and Consolas, among several others).
The corruption happens after the first instance of the font. The error can also be triggered by creating two Text layers with the same font, or by using the File>Revert menu item.
Fixes #3411
Fixes #3387

fix(text tool): some fonts render corrupted text
